"""senju.report — 日次戦況レポート(Markdown)の生成。"""
from __future__ import annotations

import datetime as _dt
from pathlib import Path

from .tournament import TournamentReport


def _bar(value: float, lo: float, hi: float, width: int = 24) -> str:
    if hi <= lo:
        return "-" * width
    frac = max(0.0, min(1.0, (value - lo) / (hi - lo)))
    filled = int(frac * width)
    return "█" * filled + "░" * (width - filled)


def render_markdown(report: TournamentReport, when: _dt.date | None = None) -> str:
    when = when or _dt.date.today()
    gens = report.generations
    lines: list[str] = []
    a = lines.append

    a(f"# Senju 戦況レポート — {when.isoformat()}")
    a("")
    a(f"シナリオ: **{report.scenario}**  /  世代数: **{len(gens)}**")
    a("")

    # 安全ステータス
    a("## 🛡 安全ステータス")
    if report.scope_violations:
        a(f"- ⚠️ スコープ違反検知: {len(report.scope_violations)} 件（下記）")
        for v in report.scope_violations[:20]:
            a(f"  - `{v}`")
    else:
        a("- ✅ スコープ違反ゼロ。全対戦はラボ標的内で完結（実在資産への接触なし）。")
    a("")

    if not gens:
        return "\n".join(lines) + "\n"

    first, last = gens[0], gens[-1]

    # サマリ
    a("## 📊 サマリ")
    a("")
    a("| 指標 | 初期世代 | 最終世代 | 変化 |")
    a("|---|---|---|---|")
    a(f"| レッド最高レート | {first.red_top_rating} | {last.red_top_rating} | {round(last.red_top_rating - first.red_top_rating,1):+} |")
    a(f"| ブルー最高レート | {first.blue_top_rating} | {last.blue_top_rating} | {round(last.blue_top_rating - first.blue_top_rating,1):+} |")
    a(f"| 総陥落数/世代 | {first.total_captures} | {last.total_captures} | {last.total_captures - first.total_captures:+} |")
    a(f"| 総検知数/世代 | {first.total_detections} | {last.total_detections} | {last.total_detections - first.total_detections:+} |")
    a("")

    # レーティング推移
    a("## 📈 レーティング推移（陣営最高レート）")
    a("")
    all_r = [g.red_top_rating for g in gens] + [g.blue_top_rating for g in gens]
    lo, hi = min(all_r), max(all_r)
    a("```")
    for g in gens:
        a(f"G{g.generation:>2} R {g.red_top_rating:>7.1f} |{_bar(g.red_top_rating, lo, hi)}|")
        a(f"     B {g.blue_top_rating:>7.1f} |{_bar(g.blue_top_rating, lo, hi)}|")
    a("```")
    a("")

    # 勝敗表
    a("## ⚔️ 世代別 勝敗")
    a("")
    a("| 世代 | 対戦 | レッド勝 | ブルー勝 | 引分 | レッド平均R | ブルー平均R |")
    a("|---|---|---|---|---|---|---|")
    for g in gens:
        a(f"| {g.generation} | {g.matches} | {g.red_wins} | {g.blue_wins} | {g.draws} | {g.red_avg_rating} | {g.blue_avg_rating} |")
    a("")

    # 弱点分析（最終世代）
    a("## 🔍 弱点分析（最終世代・陥落した脆弱性クラス）")
    a("")
    if last.vuln_capture_counts:
        a("| 脆弱性クラス | 陥落回数 |")
        a("|---|---|")
        for vc, n in last.vuln_capture_counts.items():
            a(f"| `{vc}` | {n} |")
        top = next(iter(last.vuln_capture_counts))
        a("")
        a(f"→ **防御の最優先事項: `{top}`**（最も突破されている面）。ブルー個体群の "
          f"`harden['{top}']` を上げる方向に淘汰圧をかけると良い。")
    else:
        a("- 最終世代でレッドの陥落なし。ブルー優勢。")
    a("")

    # チャンピオン
    if report.red_champion and report.blue_champion:
        rc, bc = report.red_champion, report.blue_champion
        a("## 🏆 チャンピオン")
        a("")
        a(f"- **レッド** `{rc.agent_id}` — R{rc.rating} / {rc.wins}勝{rc.losses}敗{rc.draws}分 / 第{rc.generation}世代")
        a(f"- **ブルー** `{bc.agent_id}` — R{bc.rating} / {bc.wins}勝{bc.losses}敗{bc.draws}分 / 第{bc.generation}世代")
        a("")

    a("---")
    a("_Generated by Senju adversarial security lab._")
    return "\n".join(lines) + "\n"


def write_report(report: TournamentReport, report_dir: str, when: _dt.date | None = None) -> Path:
    when = when or _dt.date.today()
    md = render_markdown(report, when)
    out_dir = Path(report_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"report-{when.isoformat()}.md"
    path.write_text(md, encoding="utf-8")
    # 最新レポートへのショートカット
    (out_dir / "latest.md").write_text(md, encoding="utf-8")
    return path
