"""senju.report — 日次戦況レポート(Markdown)＋JSONエクスポート。"""
from __future__ import annotations

import dataclasses
import datetime as _dt
import json
from pathlib import Path

from .tournament import TournamentReport


def _bar(value: float, lo: float, hi: float, width: int = 24) -> str:
    if hi <= lo:
        return "░" * width
    frac = max(0.0, min(1.0, (value - lo) / (hi - lo)))
    filled = int(frac * width)
    return "█" * filled + "░" * (width - filled)


def render_markdown(report: TournamentReport, when: _dt.date | None = None) -> str:
    when = when or _dt.date.today()
    gens = report.generations
    lines: list[str] = []
    a = lines.append

    a(f"# Senju 戦況レポート — {when.isoformat()}")
    a("")
    a(f"シナリオ: **{report.scenario}**  /  世代数: **{len(gens)}**")
    a("")

    a("## 🛡 安全ステータス")
    if report.scope_violations:
        a(f"- ⚠️ スコープ違反検知: {len(report.scope_violations)} 件")
        for v in report.scope_violations[:20]:
            a(f"  - `{v}`")
    else:
        a("- ✅ スコープ違反ゼロ。全対戦はラボ標的内で完結（実在資産への接触なし）。")
    a("")

    if not gens:
        return "\n".join(lines) + "\n"

    first, last = gens[0], gens[-1]

    a("## 📊 サマリ")
    a("")
    a("| 指標 | 初期世代 | 最終世代 | 変化 |")
    a("|---|---|---|---|")
    a(f"| レッド最高レート | {first.red_top_rating} | {last.red_top_rating} | {round(last.red_top_rating - first.red_top_rating,1):+} |")
    a(f"| ブルー最高レート | {first.blue_top_rating} | {last.blue_top_rating} | {round(last.blue_top_rating - first.blue_top_rating,1):+} |")
    a(f"| レッド総資産 | {first.red_resources} | {last.red_resources} | {round(last.red_resources - first.red_resources,1):+} |")
    a(f"| ブルー総資産 | {first.blue_resources} | {last.blue_resources} | {round(last.blue_resources - first.blue_resources,1):+} |")
    a(f"| 総陥落数/世代 | {first.total_captures} | {last.total_captures} | {last.total_captures - first.total_captures:+} |")
    a("")

    a("## 💀 戦争経済（死と繁殖・限定資源の争奪）")
    a("")
    a("| 世代 | R死 | R誕 | B死 | B誕 | R総資産 | B総資産 | R最富豪 | B最富豪 | 補給 |")
    a("|---|---|---|---|---|---|---|---|---|---|")
    for g in gens:
        a(f"| {g.generation} | {g.red_deaths} | {g.red_births} | {g.blue_deaths} | {g.blue_births} | "
          f"{g.red_resources} | {g.blue_resources} | {g.red_richest} | {g.blue_richest} | {g.reinforcement} |")
    a("")
    total_deaths = sum(g.red_deaths + g.blue_deaths for g in gens)
    total_births = sum(g.red_births + g.blue_births for g in gens)
    a(f"→ 累計 **{total_deaths} 体が淘汰**、**{total_births} 体が誕生**。有限資源を巡る攻防で世代交代が進行。")
    a("")

    a("## 📈 レーティング推移（陣営最高レート）")
    a("")
    all_r = [g.red_top_rating for g in gens] + [g.blue_top_rating for g in gens]
    lo, hi = min(all_r), max(all_r)
    a("```")
    for g in gens:
        a(f"G{g.generation:>2} R {g.red_top_rating:>7.1f} |{_bar(g.red_top_rating, lo, hi)}|")
        a(f"     B {g.blue_top_rating:>7.1f} |{_bar(g.blue_top_rating, lo, hi)}|")
    a("```")
    a("")

    a("## ⚔️ 世代別 勝敗")
    a("")
    a("| 世代 | 対戦 | レッド勝 | ブルー勝 | 引分 |")
    a("|---|---|---|---|---|")
    for g in gens:
        a(f"| {g.generation} | {g.matches} | {g.red_wins} | {g.blue_wins} | {g.draws} |")
    a("")

    a("## 🔍 弱点分析（最終世代・陥落した脆弱性クラス）")
    a("")
    if last.vuln_capture_counts:
        a("| 脆弱性クラス | 陥落回数 |")
        a("|---|---|")
        for vc, n in last.vuln_capture_counts.items():
            a(f"| `{vc}` | {n} |")
        top = next(iter(last.vuln_capture_counts))
        a("")
        a(f"→ **防御の最優先事項: `{top}`**（最も突破されている面）。")
    else:
        a("- 最終世代でレッドの陥落なし。ブルー優勢。")
    a("")

    if report.red_champion and report.blue_champion:
        rc, bc = report.red_champion, report.blue_champion
        a("## 🏆 チャンピオン（生存者中の最富豪＝戦争の勝者）")
        a("")
        a(f"- **レッド** `{rc.agent_id}` — 資産{round(rc.resources,1)} / R{rc.rating} / {rc.wins}勝{rc.losses}敗 / 第{rc.generation}世代")
        a(f"- **ブルー** `{bc.agent_id}` — 資産{round(bc.resources,1)} / R{bc.rating} / {bc.wins}勝{bc.losses}敗 / 第{bc.generation}世代")
        a("")

    a("---")
    a("_Generated by Senju adversarial security lab._")
    return "\n".join(lines) + "\n"


def to_dict(report: TournamentReport) -> dict:
    """ダッシュボード用のJSONシリアライズ可能な辞書。"""
    def champ(c) -> dict | None:
        if c is None:
            return None
        return {
            "agent_id": c.agent_id, "side": c.side, "rating": c.rating,
            "resources": round(c.resources, 2), "wins": c.wins, "losses": c.losses,
            "generation": c.generation,
        }

    return {
        "scenario": report.scenario,
        "generated_at": _dt.datetime.now().isoformat(timespec="seconds"),
        "scope_violations": report.scope_violations,
        "generations": [dataclasses.asdict(g) for g in report.generations],
        "red_champion": champ(report.red_champion),
        "blue_champion": champ(report.blue_champion),
    }


def write_report(report: TournamentReport, report_dir: str, when: _dt.date | None = None) -> Path:
    when = when or _dt.date.today()
    md = render_markdown(report, when)
    out_dir = Path(report_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"report-{when.isoformat()}.md"
    path.write_text(md, encoding="utf-8")
    (out_dir / "latest.md").write_text(md, encoding="utf-8")
    (out_dir / "latest.json").write_text(
        json.dumps(to_dict(report), ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return path
