"""senju.scripts.self_code_gen — Autonomous capability gap → PR generator.

Runs the lab_planner to identify coverage gaps, writes new lab manifests into
senju/labs/, commits them to a new branch, and opens a GitHub PR.
The auto-merge workflow absorbs the PR; next Senju cycle runs with new scenarios.

Safety: writes only JSON manifest files and state. No exploit code generated.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

REPO = os.environ.get("GITHUB_REPOSITORY", "MusicJapanLLC/test")
BASE_BRANCH = os.environ.get("BASE_BRANCH", "claude/employee-onboarding-setup-udm86")
RUN_ID = os.environ.get("GITHUB_RUN_ID", "local")


def git(*args: str) -> str:
    result = subprocess.run(["git", *args], capture_output=True, text=True, check=True)
    return result.stdout.strip()


def gh(*args: str) -> str:
    result = subprocess.run(["gh", *args], capture_output=True, text=True, check=True)
    return result.stdout.strip()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--summary", default="senju/state/last-evolution-summary.json")
    parser.add_argument("--labs-dir", default="senju/labs")
    parser.add_argument("--max-manifests", type=int, default=3)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    sys.path.insert(0, str(Path(__file__).parent.parent))
    from senju.lab_planner import plan

    labs_dir = Path(args.labs_dir)
    labs_dir.mkdir(parents=True, exist_ok=True)

    written = plan(args.summary, labs_dir, args.max_manifests)

    if not written:
        print("No coverage gaps found — no PR needed.")
        return 0

    print(f"Generated {len(written)} lab manifest(s):")
    for p in written:
        print(f"  {p}")

    if args.dry_run:
        print("[dry-run] Skipping branch/PR creation.")
        return 0

    branch = f"senju/auto-lab-gen-{RUN_ID}"
    git("checkout", "-b", branch)

    for p in written:
        git("add", str(p))

    manifest_names = ", ".join(p.stem for p in written)
    git("commit", "-m", f"feat(senju): auto-generate lab manifests for gap coverage\n\nManifests: {manifest_names}\nGenerated by self_code_gen.py run {RUN_ID}")

    git("push", "origin", branch)

    body = (
        "## Senju Auto-Lab Generation\n\n"
        f"Coverage gap analysis triggered automatic generation of {len(written)} lab manifest(s).\n\n"
        "**New manifests:**\n"
        + "\n".join(f"- `{p}`" for p in written)
        + "\n\nThese provide new attack surfaces for under-tested vulnerability classes. "
        "Will be auto-merged and active on the next Senju evolution cycle.\n\n"
        "---\n_Generated by [Claude Code](https://claude.ai/code)_"
    )

    result = gh(
        "pr", "create",
        "--repo", REPO,
        "--base", BASE_BRANCH,
        "--head", branch,
        "--title", f"feat(senju): auto-generate lab manifests [{RUN_ID}]",
        "--body", body,
    )
    print(f"PR created: {result}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
