'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{
const root=path.resolve('dist/client'),out='/workspace/scratch/1578a7a6e4ae/v18-review';fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let url=new URL(req.url,'http://localhost').pathname;url=url.replace(/^\/lantern-journey\//,'/');if(url==='/api/commerce/status'){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({available:false,owned:[]}));}const f=path.resolve(root,'.'+(url==='/'?'/index.html':url));if(!f.startsWith(root+'/')){res.statusCode=403;return res.end();}fs.stat(f,(err,st)=>{if(err||!st.isFile()){res.statusCode=404;return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.ogg':'audio/ogg','.mp3':'audio/mpeg','.wav':'audio/wav','.woff2':'font/woff2'})[path.extname(f)]||'application/octet-stream');const range=req.headers.range?.match(/bytes=(\d+)-(\d*)/);if(range){const start=+range[1],end=range[2]?Math.min(+range[2],st.size-1):st.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${st.size}`,'Content-Length':end-start+1});fs.createReadStream(f,{start,end}).pipe(res);}else fs.createReadStream(f).pipe(res);});});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:'/workspace/scratch/1578a7a6e4ae/browser-runtime/chromium',headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']}),errors=[],failed=[];
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const p=await context.newPage();p.setDefaultTimeout(6000);p.on('console',m=>{if(m.type()==='error')console.log(m.text())});p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failed.push(r.url());});
const act=async name=>{const m=p.locator('#modal:not([hidden]) [data-act="'+name+'"]:visible');return await m.count()?m.first().tap():p.locator('[data-act="'+name+'"]:visible').first().tap();},st=()=>p.evaluate(()=>LanternDebug.state()),settle=()=>p.waitForTimeout(950);
try{
await p.goto(origin+'/');await p.waitForFunction(()=>LanternDebug.diagnostics().ready);
const fixture=await p.evaluate(()=>{const R=LanternRPG,s=R.empty();s.scene='party';s.next=15;s.clears=s.clears.map((v,i)=>i<15?1:0);for(const id of [1,2,3,7,15,22])R.recruit(s,id);s.party=[0,1,2,3];s.decks[0]=s.party.slice();for(const h of s.heroes){h.xp=150;h.rank=1;h.skills={special:1,secondary:1,passive:1};}s.seen=['intro0','intro1','intro2','quartet','trio'];s.onboarding={version:1,step:'done'};s.daily={date:R.dateKey(),day:2};LanternJourney.ensure(s);LanternExpansion.ensure(s);LanternTrials.ensure(s);LanternRewards.ensure(s);LanternPass.sync(s);LanternFestival.ensure(s);LanternTrophies.ensure(s);LanternGuardians.ensure(s);s.expansion.tickets=12;s.journey.crystals.free=100;const sword=R.grant(s,'weapon',0,3,3);sword.rank=3;s.equipped[0].weapon=sword.id;if(!R.validate(s))throw Error('fixture invalid');return s;});
await p.route('**/fixture',route=>route.fulfill({body:'<html></html>',contentType:'text/html'}));
const loadFixture=async changes=>{await p.goto(origin+'/fixture');await p.evaluate(({s,c})=>{Object.assign(s,c);localStorage.setItem('lantern-journey-v09',JSON.stringify(s));},{s:fixture,c:changes||{}});await p.goto(origin+'/');await p.waitForFunction(()=>LanternDebug.diagnostics().ready);await act('enter');await p.waitForTimeout(700);};
await loadFixture();await p.locator('[data-act="developmentTab"][data-key="equipment"]').tap();await settle();assert.equal(await p.locator('.slots .rarity-badge').count(),5);assert((await p.locator('.slots').innerText()).includes('装備中'));await p.screenshot({path:out+'/equipment.png'});
await p.locator('[data-act="slot"][data-slot="weapon"]').tap();assert((await p.locator('#modal').innerText()).includes('装備中'));await p.screenshot({path:out+'/inventory.png'});await act('close');
await p.locator('[data-act="guardianChoose"][data-id="0"]').tap();await act('guardianSummonGo');await settle();await p.screenshot({path:out+'/guardians-summon.png'});await p.locator('[data-act="guardianRoll"][data-count="10"]').tap();await act('yes');await settle();assert.equal((await st()).guardians.pulls,10);assert.equal((await st()).expansion.tickets,2);await p.screenshot({path:out+'/guardians-result.png'});await act('guardianOpen');await p.locator('[data-act="guardianChoose"][data-id="0"]').tap();await p.locator('[data-act="guardianEquip"]:enabled').first().tap();await settle();const equipped=(await st()).guardians.equipped[0];assert(equipped);await p.screenshot({path:out+'/guardians-loadout.png'});await p.reload();await p.waitForFunction(()=>LanternDebug.diagnostics().ready);assert.equal((await st()).guardians.equipped[0],equipped);await act('enter');await settle();if(await p.locator('#modal:not([hidden]) [data-act="close"]').count())await act('close');
const current=await st();fixture.guardians=current.guardians;fixture.expansion=current.expansion;
for(const size of [{width:320,height:568},{width:390,height:844},{width:430,height:932}]){await p.setViewportSize(size);const battle=await p.evaluate(s=>{s.scene='battle';s.run=LanternCombat.start(s,8);LanternCombat.nextWave(s);LanternCombat.nextWave(s);s.run.enemy=s.run.enemies[0];s.story={pages:LanternStoryV17.boss(s,2),index:0,after:'resume'};return s;},fixture);await loadFixture(battle);await p.waitForFunction(()=>HearthStage.available(LanternDebug.state()));const voices=await p.evaluate(()=>HearthAudio.getDiagnostics().playedCues.filter(x=>x.startsWith('v17-voice')).length);await act('storyNext');await p.waitForTimeout(400);assert.equal(await p.evaluate(()=>HearthAudio.getDiagnostics().playedCues.filter(x=>x.startsWith('v17-voice')).length),voices);const b=await p.locator('#modal .window').boundingBox();assert(b.y>size.height*.45&&b.y+b.height<=size.height+1);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert(await p.locator('#enemy-hud').isVisible());await p.screenshot({path:out+'/boss-dialogue-'+size.width+'.png'});await act('storySkip');await p.waitForTimeout(180);assert(await p.locator('#encounter-slate').isVisible());await p.screenshot({path:out+'/boss-entry-'+size.width+'.png'});await p.waitForTimeout(1600);await p.screenshot({path:out+'/battle-four-'+size.width+'.png'});}
await act('speed');await act('auto');let guardianSeen=false,enemySeen=false;for(let i=0;i<80&&!guardianSeen;i++){await p.evaluate(()=>LanternDebug.advance());const e=await p.evaluate(()=>LanternDebug.lastEvent());enemySeen=enemySeen||!!e?.enemyAttack;guardianSeen=guardianSeen||!!e?.guardian;if(guardianSeen){await p.waitForTimeout(150);await p.screenshot({path:out+'/guardian-battle.png'});}else await p.waitForTimeout(70);}assert(guardianSeen);assert(enemySeen);
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);fs.writeFileSync('tests/results/v18-review.json',JSON.stringify({passed:true,widths:[320,390,430],equipmentRarityAndOwner:true,guardian10Summon:true,guardianEquipAndReload:true,storyVoicesAbsent:true,bossVisibleDuringDialogue:true,waveSlate:true,guardianCombatAt2x:true,enemyTurns:true,errors,failed},null,2));console.log('PASS v18 equipment, guardian summon/equip/reload, silent story, boss dialogue/slates and four allies at 3 widths');
}catch(e){console.log(JSON.stringify({errors,failed,diagnostics:await p.evaluate(()=>LanternDebug.diagnostics())}));await p.screenshot({path:out+'/failure.png'});throw e;}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
