'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{
const root=path.resolve('dist/client'),out='/workspace/scratch/1578a7a6e4ae/v18-check';fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let url=new URL(req.url,'http://localhost').pathname;url=url.replace(/^\/lantern-journey\//,'/');if(url==='/api/commerce/status'){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({available:false,owned:[]}));}const f=path.resolve(root,'.'+(url==='/'?'/index.html':url));if(!f.startsWith(root+'/')){res.statusCode=403;return res.end();}fs.stat(f,(err,st)=>{if(err||!st.isFile()){res.statusCode=404;return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.ogg':'audio/ogg','.mp3':'audio/mpeg','.wav':'audio/wav','.woff2':'font/woff2'})[path.extname(f)]||'application/octet-stream');const range=req.headers.range?.match(/bytes=(\d+)-(\d*)/);if(range){const start=+range[1],end=range[2]?Math.min(+range[2],st.size-1):st.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${st.size}`,'Content-Length':end-start+1});fs.createReadStream(f,{start,end}).pipe(res);}else fs.createReadStream(f).pipe(res);});});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:'/workspace/scratch/1578a7a6e4ae/browser-runtime/chromium',headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']}),errors=[],failed=[];
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const p=await context.newPage();p.setDefaultTimeout(6000);p.on('console',m=>{if(m.type()==='error')console.log(m.text())});p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failed.push(r.url());});
const act=async name=>{const m=p.locator('#modal:not([hidden]) [data-act="'+name+'"]:visible');return await m.count()?m.first().tap():p.locator('[data-act="'+name+'"]:visible').first().tap();},st=()=>p.evaluate(()=>LanternDebug.state()),settle=()=>p.waitForTimeout(950);
try{
await p.goto(origin+'/lantern-journey/');await p.waitForFunction(()=>LanternDebug.diagnostics().ready);await p.locator('.title-copy').tap();await p.waitForFunction(()=>HearthAudio.getDiagnostics().loops.includes('coast'),null,{timeout:15000});assert.equal((await p.evaluate(()=>HearthAudio.getDiagnostics())).scene,'title');await p.screenshot({path:out+'/title.png'});
await act('enter');await settle();assert(await p.locator('.dialogue-copy').isVisible());await p.screenshot({path:out+'/story.png'});await act('storySkip');await act('tutorialBattle');await act('tutorialFight');await p.waitForFunction(()=>HearthStage.available(LanternDebug.state()));await p.waitForTimeout(900);assert.equal(await p.locator('#masthead').isVisible(),false);assert.equal(await p.locator('#ledger').isVisible(),false);await p.screenshot({path:out+'/battle.png'});
for(let i=0;i<350&&(await st()).scene==='battle';i++){if(await p.locator('[data-act="storySkip"]:visible').count())await act('storySkip');await p.evaluate(()=>LanternDebug.advance());await p.waitForTimeout(25);}
assert.equal((await st()).run.reason,'won');await settle();assert((await p.evaluate(()=>HearthAudio.getDiagnostics().playedCues)).some(x=>x.startsWith('v17-voice-')));await p.screenshot({path:out+'/result.png'});
const before=await p.locator('.result-heading').boundingBox();await p.locator('.result-scroll').evaluate(e=>e.scrollTop=9999);const after=await p.locator('.result-heading').boundingBox();assert.equal(before.y,after.y);assert.equal(before.height,after.height);assert(await p.locator('.result-actions').isVisible());
await act('continue');await act('storySkip');assert.equal((await st()).scene,'summon');assert.equal((await st()).expansion.tickets,10);await act('tutorialDraw');assert.equal((await st()).expansion.pulls,10);assert.equal((await st()).expansion.tickets,0);await p.screenshot({path:out+'/summon.png'});await act('tutorialDone');assert.equal((await st()).onboarding.step,'done');
await settle();if(await p.locator('#modal:not([hidden]) [data-act="close"]').count())await act('close');await p.locator('[data-act="nav"][data-view="town"]').tap();await settle();if(await p.locator('#modal:not([hidden]) [data-act="close"]').count())await act('close');await p.screenshot({path:out+'/home.png'});await p.locator('.quest-launch').tap();await settle();assert.equal((await st()).scene,'map');
await act('achievements');await settle();await p.screenshot({path:out+'/trophies.png'});assert((await p.locator('.trophy-summary').innerText()).includes('150'));await act('trophyClaimAll');const coins=(await st()).resources.coin;assert(await p.locator('[data-act="trophyClaimAll"]').isDisabled());await act('close');
await p.reload();await p.waitForFunction(()=>LanternDebug.diagnostics().ready);assert.equal((await st()).resources.coin,coins);assert.equal((await st()).onboarding.step,'done');await act('enter');await settle();if(await p.locator('#modal:not([hidden]) [data-act="close"]').count())await act('close');
const sizes=[{width:320,height:568},{width:390,height:844},{width:430,height:932}];for(const size of sizes){await p.setViewportSize(size);await p.locator('[data-act="nav"][data-view="town"]').tap();await settle();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(await p.locator('img:visible').evaluateAll(xs=>xs.filter(x=>!x.complete||!x.naturalWidth).map(x=>x.src)),[]);await p.screenshot({path:out+'/home-'+size.width+'.png'});}
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);fs.mkdirSync('tests/results',{recursive:true});fs.writeFileSync('tests/results/v18-smoke.json',JSON.stringify({passed:true,sizes,titleAmbience:true,freshTutorialThrough10Summons:true,resultHeaderAnchored:true,trophyClaimsIdempotent:true,reload:true,errors,failed},null,2));console.log('PASS v18 fresh tutorial, title ambience, immersive combat, anchored result, 10 summons, trophies, reload, 3 widths');
}catch(e){console.log(JSON.stringify({errors,failed,state:await st()}));await p.screenshot({path:out+'/failure.png'});throw e;}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
