// Copies the self-hosted web fonts from @fontsource into dist/assets/fonts
// and writes dist/assets/fonts.css. Run once after changing fonts:
//   npm install && npm run fonts
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

const root = process.cwd();
const modules = join(root, "node_modules");
const outDir = join(root, "dist/assets/fonts");
mkdirSync(outDir, { recursive: true });

// [package, css file, predicate on the @font-face block]
const sources = [
  ["@fontsource-variable/inter-tight", "wght.css", (b) => /latin(-ext)?-wght-normal/.test(b)],
  ["@fontsource-variable/bodoni-moda", "opsz.css", (b) => /latin(-ext)?-opsz-normal/.test(b)],
  ["@fontsource-variable/bodoni-moda", "opsz-italic.css", (b) => /latin(-ext)?-opsz-italic/.test(b)],
  ["@fontsource-variable/newsreader", "opsz.css", (b) => /latin(-ext)?-opsz-normal/.test(b)],
  ["@fontsource-variable/newsreader", "opsz-italic.css", (b) => /latin(-ext)?-opsz-italic/.test(b)],
  ["@fontsource/shippori-mincho-b1", "400.css", () => true],
  ["@fontsource/shippori-mincho-b1", "600.css", () => true]
];

let css = "/* Generated by scripts/fonts.mjs — do not edit by hand */\n";
let count = 0;
for (const [pkg, file, keep] of sources) {
  const source = readFileSync(join(modules, pkg, file), "utf8");
  for (const block of source.split(/(?=\/\*)/)) {
    if (!block.includes("@font-face") || !keep(block)) continue;
    const woff2 = block.match(/url\(\.\/files\/([^)]+\.woff2)\)/);
    if (!woff2) continue;
    copyFileSync(join(modules, pkg, "files", woff2[1]), join(outDir, basename(woff2[1])));
    css += block
      .replace(/src:[^;]+;/, `src: url(/assets/fonts/${woff2[1]}) format("woff2");`)
      .trim() + "\n";
    count += 1;
  }
}
writeFileSync(join(root, "dist/assets/fonts.css"), css);
process.stdout.write(`fonts: ${count} faces written\n`);
