/* Deterministic rules used by both the live auto battle and campaign balance checks. */
(()=>{'use strict';const R=window.LanternRPG,C=window.LanternContent,stages=C.chapters.flatMap(c=>c.stages),X=()=>window.LanternExpansion,traits={mend:'仲間を癒す',volley:'全体魔法',poison:'毒の牙',strike:'攻撃',ward:'護りをまとう',regen:'体力を回復',hunt:'弱った仲間を狙う',drain:'技ゲージを吸う',shatter:'護りを砕く',charge:'大振りを準備',heavy:'大振り',freeze:'霜で技を遅らせる',chant:'詠唱準備 → 全体魔法',aim:'狙撃準備 → 弱った仲間',eruption:'全体魔法 · 弱点／崩しで中断',snipe:'狙撃 · 弱点／崩しで中断',interrupted:'中断 · 次の行動は休み'};
function enemies(index,wave,difficulty){const st=stages[index],c=Math.max(st.chapter,difficulty===2?6:difficulty===1?4:0),n=st.number-1,size=[1,2,2,3,3,4,4][c],d=R.difficulties[difficulty],boss=wave===2,template=boss?st.boss:st.waves[wave].enemy;
 return Array.from({length:boss?1:2},(_,i)=>{const hp=Math.min(50000,Math.round((boss?(64+c*35+n*12)*(st.chapterBoss?1.23:1):(24+c*14+n*5)*(wave?1.12:1))*size*d.hp*(boss?1+Math.min(.35,c*.06):1+Math.min(.2,c*.04))));const foe={...R.copy(!boss&&index>=2&&i===1&&X()?X().monsters[(index+wave)%X().monsters.length]:template),trait:template.mechanics[0]||'strike',boss,hp,maxHp:hp,atk:Math.round((boss?13+c*6+n*2:9+c*4+n)*d.atk*(boss?1+c*.085:1+c*.04)),def:1+c*2+(difficulty>0&&index%3===0?difficulty*4:0),ward:0,poise:0,charge:0,marks:0,enraged:false};if(index>=6&&!boss&&i===1&&foe.kind==='wisp'){foe.name='燠喰いの詠唱灯';foe.pattern=['charge','volley','mend','strike'];foe.trait='charge';foe.tip='溜めた次の巡に全体魔法 · 弱点攻撃か護り崩しで中断';}if(index>=6&&!boss&&i===1&&foe.kind==='harpy'){foe.name='赤嵐の狙撃翼';foe.pattern=['charge','hunt','strike','volley'];foe.trait='charge';foe.tip='弱った仲間への狙撃 · 弱点で中断、霜や堅守で軽減';}if(!foe.weak)foe.weak=['frost','storm','gale','fire','tide','light'][(index+wave+i)%6];if(difficulty>0){foe.hp=foe.maxHp=Math.min(50000,Math.round(foe.maxHp*(1+index*(difficulty===2?.035:.025))));foe.atk=Math.round(foe.atk*(1+index*(difficulty===2?.06:.035)));foe.pattern=foe.pattern.slice();foe.pattern[difficulty===2?0:1]=['ward','poison','volley'][index%3];if(difficulty===2)foe.pattern[2]='shatter';}return foe;});}
function start(s,index,difficulty=s.difficulty){if(!window.LanternTrials.can(s,index,difficulty))return null;const run={stage:index,wave:0,difficulty,route:stages[index].route,visual:stages[index].visual,round:0,totalRounds:0,cursor:0,target:0,resonance:0,tonics:0,party:s.party.map(id=>({id,joined:true,hp:R.stats(s,id).hp,maxHp:R.stats(s,id).hp,charge:0,shield:0,slow:0})),enemies:enemies(index,0,difficulty),reward:{coin:0,dust:0,books:0,crests:0},notes:[],events:[],phase:'party',foeCursor:0};window.LanternTrials.wave(s,run);return run;}
function chargedKind(e){return ['oracle','wisp'].includes(e.kind)?'eruption':e.kind==='harpy'?'snipe':'heavy';}
function intent(r,e){if(e.interrupted===true)return 'interrupted';if(e.charge)return chargedKind(e);const next=e.pattern[r.round%e.pattern.length]||'strike';return next==='charge'?chargedKind(e)==='eruption'?'chant':chargedKind(e)==='snipe'?'aim':'charge':next;}
function heal(r,p,n){const old=p.hp;p.hp=Math.min(p.maxHp,p.hp+n);return p.hp-old;}
function strike(e,n,pierce=false,meta={}){let damage=Math.max(1,Math.round(n)-(pierce?0:e.def));if(e.ward){damage=Math.max(1,Math.round(damage*.62));e.ward--;if(!e.ward)e.poise=1;}if(e.poise){damage=Math.round(damage*1.18);meta.critical=true;}if(e.marks){damage+=e.marks*3;e.marks--;}damage=Math.min(e.hp,damage);e.hp-=damage;return damage;}
function hit(event,r,index,n,pierce=false){const e=r.enemies[index],ward=e.ward,meta={};const damage=strike(e,n,pierce,meta);event.numbers.push({enemy:index,n:damage,...meta});if(ward&&!e.ward){event.broken=true;(event.breakTargets||(event.breakTargets=[])).push(index);}if(meta.critical)event.critical=true;return damage;}
function selectTarget(r){if(r.manualTarget&&r.enemies[r.target]?.hp>0)return r.target;r.manualTarget=false;return r.enemies.map((e,i)=>({i,score:e.hp<=0?-999:(e.pattern.includes('mend')?50:0)+(e.charge?20:0)+(1-e.hp/e.maxHp)*10})).sort((a,b)=>b.score-a.score)[0].i;}
function step(s){const r=s.run;if(!r||r.reason)return null;const living=r.party.filter(p=>p.hp>0);if(!living.length)return{done:'defeat'};if(r.enemies.every(e=>e.hp<=0))return{done:r.wave===2?'won':'wave'};
 if(r.phase==='party'&&r.resonance>=100&&s.seen.includes('trio')&&r.party.length>=3){r.resonance=0;const n=living.reduce((v,p)=>v+R.stats(s,p.id).atk,0)*1.45,event={kind:'burst',unit:0,actor:r.party[0].id,targetEnemy:r.target,title:s.seen.includes('quartet')?'灯路の四重奏':'暁の三重奏',numbers:[]};const targets=r.enemies.flatMap((e,i)=>e.hp>0?[i]:[]);for(const i of targets)hit(event,r,i,n/targets.length,true);r.enemy=r.enemies[r.target]||r.enemies[0];return event;}
 if(r.phase==='party'){
  if(r.dotRound!==r.round){r.dotRound=r.round;const tick={kind:'dot',unit:0,actor:r.party[0].id,targetEnemy:0,title:'継続ダメージ',numbers:[]};for(const [i,e] of r.enemies.entries())if(e.hp>0&&e.burn){e.burn--;const n=Math.min(e.hp,Math.max(2,Math.round(e.maxHp*.035)));e.hp-=n;tick.numbers.push({enemy:i,n});}for(const [i,p] of r.party.entries())if(p.hp>0&&p.poison){p.poison--;const n=Math.min(p.hp,Math.max(1,Math.round(p.maxHp*.035)));p.hp-=n;tick.numbers.push({unit:i,n});}if(tick.numbers.length)return tick;}
  while(r.cursor<r.party.length&&r.party[r.cursor].hp<=0)r.cursor++;
  if(r.cursor>=r.party.length){r.phase='enemy';r.foeCursor=0;return step(s);}
  const unit=r.cursor++,p=r.party[unit],id=p.id,role=R.role(id),h=s.heroes[id],z=R.stats(s,id),weak=living.slice().sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0],target=selectTarget(r);r.target=target;const e=r.enemies[target],chargedBefore=!!e.charge,event={unit,actor:id,targetEnemy:target,kind:['slash','shoot','light','light'][role],numbers:[],title:''};
  const defensive=s.settings.policy==='defensive',aggressive=s.settings.policy==='aggressive';
  if(weak.hp/weak.maxHp<(defensive?.55:.35)&&r.tonics<2&&s.tonic.count>0){s.tonic.count--;r.tonics++;event.kind='heal';event.target=r.party.indexOf(weak);event.title='灯の薬';event.numbers.push({unit:event.target,n:heal(r,weak,Math.round(weak.maxHp*(.38+s.tonic.level*.04)+z.heal)),heal:true});}
  else if(role===2&&h.skills.secondary&&weak.hp/weak.maxHp<(aggressive?.4:.72)&&p.charge>=35){p.charge-=35;event.kind='heal';event.target=r.party.indexOf(weak);event.title=R.chars[id].secondary;event.numbers.push({unit:event.target,n:heal(r,weak,Math.round(z.heal*(2+h.skills.secondary*.35))),heal:true});}
  else if(p.charge>=100&&h.skills.special){p.charge=0;event.kind='skill';event.title=R.chars[id].special;const mode=X()?.style(s,id)||0;event.style=mode;event.title=X()?.styles[id][mode]||event.title;const amount=z.atk*(2.25+h.skills.special*.25);if(mode===2){for(const [i,foe] of r.enemies.entries())if(foe.hp>0)hit(event,r,i,amount*.65,role>=2);if(role>=2){for(const [i,q] of r.party.entries())if(q.hp>0)event.numbers.push({unit:i,n:heal(r,q,z.heal),heal:true});}else{for(const q of living)q.shield=Math.min(1000,q.shield+Math.round(z.atk*.35));}}else hit(event,r,target,amount*(mode===1?1.22:1),mode===1||role>=2);if(role===3)for(let i=0;i<r.party.length;i++)if(r.party[i].hp>0){r.party[i].shield=Math.min(1000,r.party[i].shield+z.heal);event.numbers.push({unit:i,n:heal(r,r.party[i],z.heal),heal:true});}}
  else if(h.skills.secondary&&p.charge>=60&&role===1&&e.ward){p.charge-=35;e.ward=0;e.poise=2;e.marks=2;event.kind='snare';event.title='風縛り';event.broken=true;event.breakTargets=[target];hit(event,r,target,z.atk*(1.3+h.skills.secondary*.15),true);}
  else if(h.skills.secondary&&p.charge>=60&&[0,3].includes(role)&&!aggressive&&living.some(p=>p.hp/p.maxHp<.72)){p.charge-=40;event.kind='guard';event.title=R.chars[id].secondary;for(const q of living)q.shield=Math.min(1000,q.shield+Math.round(z.atk*(.7+h.skills.secondary*.2)));}
  else {hit(event,r,target,z.atk*(aggressive?1.12:1),role===2);if(role>=2)e.marks=Math.min(3,e.marks+1);p.charge=Math.min(100,p.charge+(p.slow?15:30)+(h.skills.passive?3:0));p.slow=Math.max(0,p.slow-1);}
  if(s.seen.includes('trio')&&r.party.length>=3)r.resonance=Math.min(100,r.resonance+7);const baseHits=event.numbers.length;X()?.modify(s,event);window.LanternTrials.afterAction(s,event);const followups=event.numbers.slice(baseHits).filter(v=>v.enemy!==undefined&&!v.heal&&v.n>0);for(const v of followups)v.followup=true;if(followups.length)event.chain=followups.length;if(chargedBefore&&e.hp>0&&(event.broken||event.weak||event.interrupted)){e.charge=0;e.interrupted=true;event.interrupted=true;event.counter='溜めを中断 · 敵の次手を封じた';}event.killed=e.hp===0;if(event.broken&&!event.counter)event.counter='護りを崩した';if(event.weak&&!event.counter)event.counter='弱点を突いた';if(event.critical&&!event.title)event.title='隙を突く会心';if(r.festival===undefined)window.LanternRewards?.observe(s,event);r.enemy=e;return event;
 }
 while(r.foeCursor<r.enemies.length&&r.enemies[r.foeCursor].hp<=0)r.foeCursor++;
 if(r.foeCursor>=r.enemies.length){r.round++;r.totalRounds=(r.totalRounds||0)+1;r.cursor=0;r.phase='party';for(const e of r.enemies)e.poise=Math.max(0,e.poise-1);return step(s);}
 const attacker=r.foeCursor++,e=r.enemies[attacker],type=intent(r,e),event={enemyAttack:true,attacker,targetEnemy:attacker,kind:'enemy',enemyType:type,targets:[],numbers:[],title:traits[type],heavy:['heavy','eruption','snipe'].includes(type)};r.enemy=e;
 if(type==='interrupted'){e.interrupted=false;e.charge=0;event.title='体勢を崩して動けない';return event;}if(type==='ward'){e.ward=2;return event;}if(['charge','chant','aim'].includes(type)){e.charge=1;event.channel=chargedKind(e);return event;}if(type==='regen'){if(!e.marks&&!e.poise){const n=Math.min(e.maxHp-e.hp,Math.round(e.maxHp*.09));e.hp+=n;event.numbers.push({enemy:attacker,n,heal:true});}else event.title='回復を阻止';return event;}
 if(type==='mend'){const q=r.enemies.filter(a=>a.hp>0).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];const n=q.burn?0:Math.min(q.maxHp-q.hp,Math.round(e.maxHp*.14));if(q.burn){event.title='燃焼で回復を阻止';event.counter='回復を阻止';if(r.festival===undefined)window.LanternRewards?.observe(s,event);}q.hp+=n;event.numbers.push({enemy:r.enemies.indexOf(q),n,heal:true});return event;}const target=['hunt','snipe'].includes(type)?r.party.indexOf(living.slice().sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0]):r.party.indexOf(living[(r.round+attacker)%living.length]);event.targets=(type==='heavy'&&e.boss||['volley','eruption'].includes(type))?r.party.flatMap((p,i)=>p.hp>0?[i]:[]):[target];
 for(const i of event.targets){const p=r.party[i],z=R.stats(s,p.id);let n=Math.max(2,e.atk-z.def+(r.round>=6?(r.round-5)*3:0));if(type==='heavy')n=Math.round(n*1.55);if(type==='volley')n=Math.round(n*.65);if(type==='eruption')n=Math.round(n*.9);if(type==='snipe')n=Math.round(n*1.45);if(e.chill){n=Math.round(n*.65);}if(type==='poison')p.poison=2;if(s.settings.policy==='defensive')n=Math.round(n*.88);if(type==='shatter')p.shield=0;const block=Math.min(p.shield,n);p.shield-=block;n=Math.min(p.hp,n-block);p.hp-=n;if(type==='drain')p.charge=Math.max(0,p.charge-25);if(type==='freeze')p.slow=1;event.numbers.push({unit:i,n});}if(e.chill){event.counter='凍気で攻撃を軽減';if(r.festival===undefined)window.LanternRewards?.observe(s,event);}e.chill=0;e.charge=0;e.enraged=r.round>=6;return event;
}
function nextWave(s){const r=s.run;if(r.festival===undefined)X()?.countWave(s);r.wave++;r.dotRound=-1;r.round=0;r.cursor=0;r.phase='party';r.foeCursor=0;r.target=0;r.manualTarget=false;r.enemies=enemies(r.stage,r.wave,r.difficulty);X()?.tune(s,r);window.LanternTrials.wave(s,r);window.LanternFestival?.tune(s,r);for(const p of r.party)if(p.hp>0)heal(r,p,Math.round(p.maxHp*.2));return r;}
function finish(s,reason){const r=s.run;if(r.reason)return false;if(r.festival!==undefined)return window.LanternFestival.finish(s,reason);r.reason=reason;s.scene='result';r.events=[];s.tonic.count=Math.min(99,s.tonic.count+r.tonics);if(reason!=='won'){X()?.record(s);return true;}if(r.tower){X().towerFinish(s);window.LanternRewards?.record(s);return true;}const st=stages[r.stage],first=r.stage===window.LanternTrials.progress(s,r.difficulty),m=R.difficulties[r.difficulty].reward;r.first=first;r.reward={coin:Math.round((12+st.chapter*5+st.number*2)*m),dust:Math.round((3+st.chapter)*m),books:(first?2:st.chapterBoss?1:0)+r.difficulty,crests:first&&st.chapterBoss?2+r.difficulty:r.difficulty===2?1:0};for(const k in r.reward)s.resources[k]=Math.min(999999,s.resources[k]+r.reward[k]);r.xp=R.difficulties[r.difficulty].xp;r.levels=[];for(const id of s.unlocked){const before=R.level(s.heroes[id].xp);s.heroes[id].xp=Math.min(1000000,s.heroes[id].xp+r.xp);const after=R.level(s.heroes[id].xp);if(after>before)r.levels.push({id,before,after});}r.loot=Array.from({length:1+r.difficulty+(st.chapterBoss?1:0)},()=>R.roll(s,st,r.difficulty));if(r.difficulty===0){s.clears[r.stage]=Math.max(s.clears[r.stage],1);if(first)s.next=Math.min(21,s.next+1);}
 if(first&&r.difficulty===0){for(const l of st.learns){if(l.memberId==='party'){s.seen.push(l.id);r.events.push(l);}else{const id=R.chars.findIndex(c=>c.key===l.memberId),key=l.id.includes('finisher')?'special':'secondary';s.heroes[id].skills[key]=Math.max(1,s.heroes[id].skills[key]);r.events.push(l);}}
 const ch=C.chapters[st.chapter];if(st.chapterBoss&&ch.recruit){const id=R.chars.findIndex(c=>c.key===ch.recruit.memberId);R.recruit(s,id);r.recruit=id;}if(st.chapterBoss)r.ending=R.copy(ch.ending);}
 window.LanternJourney?.complete(s);window.LanternTrials.finish(s);X()?.record(s);window.LanternRewards?.record(s);
 // Supplies replace only the potions spent; ordinary replay can never mint extra potions
 return true;}
function trophyStep(s){const event=step(s);window.LanternTrophies?.observe(s,event);return event;}
function trophyFinish(s,reason){const result=finish(s,reason);if(result)window.LanternTrophies?.record(s);return result;}
window.LanternCombat=Object.freeze({stages,traits,start,enemies,intent,step:trophyStep,nextWave,finish:trophyFinish});})();
