/* Original effect choreography, bounded to the visible battlefield. */
(()=>{'use strict';
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,keys=['hero','mina','rio','noah'];
const clamp=x=>Math.max(0,Math.min(1,x)),colors=['#ffbd70','#8afad1','#c9b5ff','#91dfff'];
function ring(c,x,y,r,color,width=2,flat=1){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.ellipse(x,y,r,r*flat,0,0,Math.PI*2);c.stroke();}
function line(c,x,y,xx,yy,color,width=2){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(x,y);c.lineTo(xx,yy);c.stroke();}
function glow(c,x,y,r,color){const g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'#00000000');c.fillStyle=g;c.fillRect(x-r,y-r,2*r,2*r);}
function debris(c,x,y,phase,color,n=30,radius=115){if(phase<0||phase>1)return;for(let j=0;j<n;j++){const angle=j*2.399,rad=phase*(radius+(j%7)*9);c.globalAlpha=1-phase;c.fillStyle=j%4===0?'#fff8d9':color;c.fillRect(x+Math.cos(angle)*rad,y+Math.sin(angle)*rad*.65-phase*10,2+j%4,2+j%3);}c.globalAlpha=1;}
function impact(c,x,y,age,at,color,size=70){const p=(age-at)/.42;if(p<0||p>1)return;glow(c,x,y,size*(.5+p),color+'60');ring(c,x,y,8+p*size,color,4*(1-p)+1);ring(c,x,y,5+p*size*.66,'#fff6d5',2);debris(c,x,y,p,color,28,size);}
function arrow(c,ox,oy,x,y,p,color){if(p<=0||p>=1)return;const xx=ox+(x-ox)*p,yy=oy+(y-oy)*p,an=Math.atan2(y-oy,x-ox);line(c,xx-Math.cos(an)*44,yy-Math.sin(an)*44,xx,yy,color,4);line(c,xx-Math.cos(an)*22,yy-Math.sin(an)*22,xx,yy,'#fff6d4',2);line(c,xx,yy,xx-Math.cos(an+.5)*9,yy-Math.sin(an+.5)*9,'#faffdf',2);line(c,xx,yy,xx-Math.cos(an-.5)*9,yy-Math.sin(an-.5)*9,'#faffdf',2);}
function badge(c,l,x,y,text,color){c.save();c.globalCompositeOperation='source-over';c.font="14px 'Journey JP',monospace";c.textAlign='center';const width=c.measureText(text).width+16,xx=Math.max(width/2+4,Math.min(l.fieldWidth-width/2-4,x)),yy=Math.max(l.ceiling+18,y);c.fillStyle='#091b2be8';c.fillRect(xx-width/2,yy-14,width,21);c.fillStyle=color;c.fillRect(xx-width/2,yy+6,width,2);c.fillText(text,xx,yy+1);c.restore();}
function fracture(c,x,y,p){if(p<0||p>1)return;for(let i=0;i<6;i++){const an=i*Math.PI/3,dr=12+p*48,xx=x+Math.cos(an)*dr,yy=y+Math.sin(an)*dr*.65;c.save();c.translate(xx,yy);c.rotate(an+p*.6);c.globalAlpha=1-p;c.fillStyle=i%2?'#8bf1dd':'#e5fff5';c.beginPath();c.moveTo(-7,-16);c.lineTo(9,-10);c.lineTo(4,12);c.lineTo(-6,6);c.closePath();c.fill();c.restore();}}
function draw(c,l,t,s,a){if(!s.run||!l.enemy)return;const r=s.run,e=l.enemy,x=e.x,y=e.y-e.size*.54,age=a?t-a.start:99,skill=a?.kind==='skill',burst=a?.kind==='burst',duration=skill||burst?1.8:.92;
 c.save();c.beginPath();c.rect(0,l.ceiling,l.fieldWidth,l.bottom-l.ceiling+12);c.clip();
 for(const [i,target]of r.enemies.entries()){const q=l.enemies[i];if(!q||target.hp<=0||!target.charge)continue;const xx=q.x,yy=q.y-q.size*.54,magic=['oracle','wisp'].includes(target.kind),co=magic?'#d4b8ff':'#ffbd86';ring(c,xx,yy,30+(reduced?0:Math.sin(t*3)*3),co+'99',2);c.setLineDash([6,5]);ring(c,xx,yy,42,co+'77',2);c.setLineDash([]);if(magic&&!reduced)for(let n=0;n<3;n++){const an=t*1.4+n*Math.PI*2/3;glow(c,xx+Math.cos(an)*36,yy+Math.sin(an)*22,8,'#e9caff88');}if(target.kind==='harpy'){const weak=r.party.filter(p=>p.hp>0).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0],victim=l[keys[r.party.indexOf(weak)]];if(victim){const vy=victim.y-victim.size*.5;c.strokeStyle=co;c.lineWidth=2;c.strokeRect(victim.x-14,vy-17,28,34);line(c,victim.x-21,vy,victim.x-10,vy,co,2);line(c,victim.x+10,vy,victim.x+21,vy,co,2);}}}
 if(age<0||age>duration){c.restore();return;}
 const p=l[keys[a.unit]||'hero'],px=p.x,py=p.y-p.size*.56,id=window.LanternRPG.role(a.actor??0),color=window.LanternRPG.chars[a.actor??0].color;
 if(reduced){for(const v of a.numbers||[]){const q=v.enemy!==undefined?l.enemies[v.enemy]:l[keys[v.unit]];if(q)ring(c,q.x,q.y-40,24,v.heal?'#8bf7b8':v.critical?'#ffe2a1':color,3);}if(a.broken||a.critical||a.chain||burst)badge(c,l,x,y-24,burst?'RESONANCE':a.broken?'BREAK':a.critical?'CRITICAL ×1.18':'CHAIN +'+a.chain,burst||a.critical?'#ffe2a1':'#a6ffe0');c.restore();return;}
 c.globalCompositeOperation='screen';
 if(!a.enemyAttack){
  glow(c,px,py,26+Math.sin(Math.min(age,.3)*9)*16,color+'55');
  if(['slash','counter'].includes(a.kind)){for(let j=0;j<3;j++){const f=clamp((age-.08-j*.025)/.28);if(f<=0||f>=1)continue;c.save();c.translate(x,y);c.rotate(-.62);c.strokeStyle=j===0?'#fff7d5':color;c.lineWidth=10-j*2;c.beginPath();c.ellipse(0,0,30+f*43,12+f*9,0,-2.8+f,1.3+f);c.stroke();c.restore();}impact(c,x,y,age,.23,color,38);}
  if(['shoot','snare','break'].includes(a.kind)){arrow(c,px,py,x,y,clamp((age-.05)/.25),'#a2ffe1');impact(c,x,y,age,.29,'#a2ffe1',a.broken?68:40);if(a.kind==='snare')for(let j=0;j<5;j++)ring(c,x,y-26+j*13,28+j*3,'#8effd988',2,.26);}
  if(a.kind==='light'){const f=clamp((age-.08)/.22),xx=px+(x-px)*f,yy=py+(y-py)*f;glow(c,xx,yy,22,color+'88');ring(c,xx,yy,7,'#fff7ca',3);for(let j=0;j<6;j++){const an=j*Math.PI/3+age*10;line(c,xx+Math.cos(an)*9,yy+Math.sin(an)*9,xx+Math.cos(an)*17,yy+Math.sin(an)*17,color,2);}impact(c,x,y,age,.3,color,46);}
  if(['heal','guard'].includes(a.kind)){for(let i=0;i<r.party.length;i++){if(a.kind==='heal'&&a.target!==undefined&&i!==a.target)continue;const q=l[keys[i]],yy=q.y-q.size*.5;ring(c,q.x,q.y-3,18+age*24,a.kind==='heal'?'#b6ffe0':'#98ddff',2,.25);for(let j=0;j<12;j++){const phase=(age+j*.06)%1;c.globalAlpha=1-phase;c.fillStyle=a.kind==='heal'?'#aeffbf':'#a1dfff';c.fillRect(q.x+Math.sin(j*2.4)*20,q.y-phase*q.size,3,5);}c.globalAlpha=1;glow(c,q.x,yy,50,'#a2ffd32e');if(a.kind==='guard'){c.strokeStyle='#9fdbff99';c.lineWidth=3;c.beginPath();c.ellipse(q.x,yy,25,40,0,0,Math.PI*2);c.stroke();}}}
 }
 if(a.enemyAttack){for(const v of a.numbers||[])if(v.heal){const q=l.enemies[v.enemy];if(q){ring(c,q.x,q.y-q.size*.4,20+age*28,'#a6f0c6',3);glow(c,q.x,q.y-q.size*.4,50,'#99ecbd55');}}const victims=a.targets||[];for(const i of victims){const q=l[keys[i]],yy=q.y-q.size*.5;if(age<.4){c.globalAlpha=.7;c.setLineDash([5,6]);line(c,x,y,q.x,yy,'#ffa780',2);c.setLineDash([]);ring(c,q.x,q.y,25+age*20,'#ffb59a',2,.25);c.globalAlpha=1;}else impact(c,q.x,yy,age,.46,a.heavy?'#ffc194':'#ef9c84',a.heavy?74:32);}
  if(victims.length){for(const i of victims){const q=l[keys[i]],yy=q.y-q.size*.5,hit=clamp((age-.40)/.40),charge=age<.40?clamp(age/.40):0;
 if(a.enemyType==='volley'){for(let j=0;j<5;j++){const f=clamp((age-.06-j*.035)/.38);arrow(c,x,y-15+j*5,q.x+(j-2)*6,yy,f,'#ffb390');}}
 else if(['poison','drain','freeze'].includes(a.enemyType)){const co=a.enemyType==='poison'?'#bb84eb':a.enemyType==='freeze'?'#a1dcff':'#eb869f';for(let j=0;j<4;j++){const f=clamp((age-.08-j*.045)/.38),xx=x+(q.x-x)*f,by=y+(yy-y)*f+Math.sin(f*Math.PI*2+j)*10;glow(c,xx,by,8+j*2,co+'99');}if(hit>0){ring(c,q.x,yy,15+hit*42,co+'aa',3);debris(c,q.x,yy,hit,co,22,55);}}
 else if(a.heavy){if(charge){c.globalAlpha=.35*charge;c.fillStyle='#ff826c';c.fillRect(q.x-25,l.ceiling,50,l.space);c.globalAlpha=1;}if(hit>0&&hit<1){for(let j=0;j<9;j++){const an=j*.65,rr=hit*(35+j*6);line(c,q.x,yy,q.x+Math.cos(an)*rr,yy+Math.sin(an)*rr*.6,'#ffcea3',4*(1-hit)+1);}debris(c,q.x,q.y-5,hit,'#e2b18e',25,90);}}
 else if(age>.26&&age<.7){const f=clamp((age-.26)/.4);for(let j=0;j<3;j++){const dx=(j-1)*11;line(c,q.x+dx-18+f*15,yy-27,q.x+dx+12+f*15,yy+22,'#ffbc99',4*(1-f)+1);}}}}
 if(a.enemyType==='eruption'){for(const i of victims){const q=l[keys[i]],yy=q.y-q.size*.5;for(let j=0;j<3;j++)ring(c,q.x,yy,14+clamp((age-.35-j*.05)/.45)*54,'#d4b8ff88',3);if(age>.3&&age<.65){line(c,q.x,l.ceiling,q.x,yy,'#d0a8ff55',18);line(c,q.x,l.ceiling,q.x,yy,'#f5e6ffaa',3);}}}if(a.enemyType==='snipe')for(const i of victims){const q=l[keys[i]];arrow(c,x,y,q.x,q.y-q.size*.5,clamp((age-.10)/.36),'#ffcc94');}
  if(a.heavy&&age>.46){const f=clamp((age-.46)/.4);ring(c,x,y,15+f*l.fieldWidth,'#ffa57a55',6);for(let j=0;j<12;j++)line(c,x,y,x+Math.cos(j*.523)*f*180,y+Math.sin(j*.523)*f*100,'#ffc59966',3);}
 }
 if(a.killed)debris(c,x,y,(age-.3)/.85,'#ffe1a1',42,110);
 if(a.broken){for(const i of a.breakTargets||[a.targetEnemy]){const q=l.enemies[i];if(!q)continue;fracture(c,q.x,q.y-q.size*.54,(age-.22)/.55);}if(age>.22&&age<.82)badge(c,l,x,y-35,'BREAK','#a6ffe0');}
 if(a.critical){for(const v of a.numbers.filter(v=>v.critical)){const q=l.enemies[v.enemy];if(!q)continue;const xx=q.x,yy=q.y-q.size*.5,f=(age-.26)/.35;if(f>0&&f<1){for(let j=0;j<8;j++){const an=j*Math.PI/4+.3,rr=(j%2?23:42)*(1+f);line(c,xx+Math.cos(an)*10,yy+Math.sin(an)*10,xx+Math.cos(an)*rr,yy+Math.sin(an)*rr,'#ffe8ac',3*(1-f)+1);}impact(c,xx,yy,age,.26,'#ffe3a0',55);}}if(!a.broken&&age>.25&&age<.85)badge(c,l,x,y-35,'CRITICAL ×1.18','#ffe2a1');}
 if(a.chain){for(const [j,v]of a.numbers.filter(v=>v.followup).entries()){const q=l.enemies[v.enemy];if(!q)continue;const xx=q.x,yy=q.y-q.size*.5,at=.37+j*.06;arrow(c,px,py-12-j*6,xx,yy,clamp((age-at)/.18),color);impact(c,xx,yy,age,at+.18,color,27);}if(age>.50&&age<.89)badge(c,l,x,y+6,'CHAIN +'+a.chain,color);}
 if(skill||burst){
  // Pixel speed trails gather toward the hit, then open into a gold shock front.
  const wind=clamp((age-.12)/.35)*clamp((1.18-age)/.45);
  if(wind>0){for(let j=0;j<18;j++){const yy=l.ceiling+(j*47)%Math.max(1,l.space),span=24+(j%5)*14,xx=((age*510+j*79)%l.fieldWidth);c.globalAlpha=wind*(j%3?.26:.5);c.fillStyle=j%3?color:'#fff0cc';c.fillRect(Math.round(xx-span),Math.round(yy),span,1+j%2);}c.globalAlpha=1;}
  if(age>.63&&age<.94){const phase=(age-.63)/.31;c.globalAlpha=(1-phase)*.65;for(let j=0;j<3;j++)ring(c,x,y,24+phase*(110+j*28),j===0?'#fff0ca':color,Math.max(1,5*(1-phase)),.65);c.globalAlpha=1;}
  // A single focus pulse and expanding impact star, contained to the field.
  const pulse=clamp(1-Math.abs(age-.68)/.18);if(pulse>0){c.globalCompositeOperation='screen';glow(c,x,y,100+pulse*70,color+'88');for(let i=0;i<10;i++){const an=i*Math.PI/5,rr=35+pulse*100;line(c,x+Math.cos(an)*15,y+Math.sin(an)*15,x+Math.cos(an)*rr,y+Math.sin(an)*rr*.6,i%2?color:'#fff2ca',i%2?2:4);}}
  c.globalCompositeOperation='source-over';c.fillStyle='rgba(5,13,31,.30)';c.fillRect(0,l.ceiling,l.fieldWidth,l.space+12);c.globalCompositeOperation='screen';
  const charge=clamp(age/.3),fade=clamp((1.8-age)/.5);glow(c,px,py,40+charge*25,color+'77');ring(c,px,py,12+charge*32,color,2);
  if(skill&&id===0){for(let j=0;j<3;j++){const at=.30+j*.30,f=(age-at)/.27;if(f>0&&f<1){c.save();c.translate(x,y);c.rotate(j===1?.65:-.7);c.lineWidth=11*(1-f)+2;c.strokeStyle=j===2?'#fff6ba':'#ffb564';c.beginPath();c.ellipse(0,0,45+f*65,13+f*14,0,-3+f*.5,1.6+f*.5);c.stroke();c.lineWidth=2;c.strokeStyle='#ffffff';c.stroke();c.restore();}impact(c,x,y,age,at+.1,j===2?'#ffd79b':'#ffb35f',j===2?100:66);}for(let j=0;j<5;j++)line(c,px-j*12,py+j*5,x-30,y+j*5,'#ffa87333',3);}
  if(skill&&id===1){for(let j=0;j<7;j++){const at=.18+j*.075;arrow(c,px-j*9,py-20+j*6,x+Math.sin(j)*14,y+Math.cos(j)*15,clamp((age-at)/.34),j%2?'#a8ffd7':'#d6ffb6');impact(c,x+Math.sin(j)*12,y+Math.cos(j)*15,age,at+.34,'#8df0c7',38);}ring(c,x,y,18+clamp((age-.62)/.8)*90,'#b5ffe555',3);}
  if(skill&&id===2){const f=clamp((age-.36)/.35),ox=x-70,oy=l.ceiling-35,xx=ox+(x-ox)*f,yy=oy+(y-oy)*f;if(age>.25&&age<.82){line(c,xx-38,yy-100,xx,yy,'#a7a2ff99',18);line(c,xx-24,yy-65,xx,yy,'#e8daff',7);glow(c,xx,yy,36,'#e5b9ffbb');}for(let j=0;j<3;j++){const at=.58+j*.15;impact(c,x+(j-1)*14,y,age,at,j===0?'#e3ccff':'#c2aeff',j===0?108:68);}for(let j=0;j<4;j++){const radius=36+j*12;c.strokeStyle='#d9c8ff88';c.lineWidth=2;c.beginPath();c.ellipse(x,y,radius,radius*.3,age*.6,0,Math.PI*2);c.stroke();}debris(c,x,y,(age-.67)/.9,'#d7beff',44,140);}
  if(skill&&id===3){for(let j=0;j<5;j++){const f=clamp((age-.24-j*.1)/.85);if(f>0&&f<1)ring(c,px,py,10+f*l.fieldWidth,'#b4e9ff'+Math.round((1-f)*170).toString(16).padStart(2,'0'),4);}for(let i=0;i<r.party.length;i++){const q=l[keys[i]];glow(c,q.x,q.y-35,60,'#94f2df44');ring(c,q.x,q.y,25+Math.sin(age*6)*5,'#a3f5eecc',3,.3);for(let j=0;j<5;j++){const f=(age+j*.13)%1;c.globalAlpha=(1-f)*fade;c.fillStyle='#ceffff';c.fillRect(q.x+Math.sin(j*2)*24,q.y-f*q.size,3,8);}c.globalAlpha=1;}impact(c,x,y,age,.70,'#b0eaff',86);}
  if(burst){for(let i=0;i<r.party.length;i++){const q=l[keys[i]],co=window.LanternRPG.chars[r.party[i].id].color;c.strokeStyle=co;c.lineWidth=age<.5?2:5*fade;c.beginPath();c.moveTo(q.x,q.y-q.size*.5);c.quadraticCurveTo(l.fieldWidth*.48,l.ceiling+20,x,y);c.stroke();}impact(c,x,y,age,.62,'#ffe5ab',145);for(let j=0;j<4;j++)ring(c,x,y,20+clamp((age-.62)/.8)*(70+j*25),colors[j]+'88',3);debris(c,x,y,(age-.62)/1.1,'#ffe6ac',55,175);}
  c.globalCompositeOperation='source-over';if(age>.48&&age<1.4){c.fillStyle=color;c.font="13px 'Journey JP',monospace";c.textAlign='right';c.fillText(burst?'RESONANCE':id===0?'3連斬':id===1?'星彩の矢':id===2?'流星の光':'癒しの輪唱',l.fieldWidth-12,l.ceiling+25);}
 }

 if(a.element&&(skill||burst||a.runeName)){const el=a.element,co=window.LanternExpansion.elements[el].color,f=clamp((age-.18)/.7);c.globalCompositeOperation='screen';
 for(const v of a.numbers.filter(v=>v.rune||v.heal||a.actor>=4)){const q=v.enemy!==undefined?l.enemies[v.enemy]:l[keys[v.unit]];if(!q)continue;const xx=q.x,yy=q.y-q.size*.5;glow(c,xx,yy,50+f*45,co+'55');
 if(el==='fire'){for(let j=0;j<14;j++){const phase=(f+j*.053)%1;c.globalAlpha=1-phase;c.fillStyle=j%2?'#ffe8a8':co;c.fillRect(xx+Math.sin(j*2.4)*25*(1-phase),yy+24-phase*100,4+j%3,12*(1-phase)+3);}}
 if(el==='frost'){for(let j=0;j<8;j++){const an=j*Math.PI/4;line(c,xx,yy,xx+Math.cos(an)*(18+f*55),yy+Math.sin(an)*(18+f*55),co,3);line(c,xx+Math.cos(an)*(18+f*55),yy+Math.sin(an)*(18+f*55),xx+Math.cos(an+.18)*(8+f*32),yy+Math.sin(an+.18)*(8+f*32),'#e4fbff',2);}}
 if(el==='storm'){for(let j=0;j<3;j++){c.beginPath();c.moveTo(xx-15+j*15,l.ceiling);for(let n=1;n<=8;n++)c.lineTo(xx+Math.sin(n*8+j+Math.floor(age*18))*18,l.ceiling+(yy-l.ceiling)*n/8);c.strokeStyle=j===1?'#fff7dd':co;c.lineWidth=j===1?2:4;c.stroke();}}
 if(el==='gale'){for(let j=0;j<4;j++){c.strokeStyle=co;c.lineWidth=3;c.beginPath();c.ellipse(xx,yy-25+j*15,15+f*52,8+f*8,age*2,age*9+j,age*9+j+4);c.stroke();}}
 if(el==='tide'){for(let j=0;j<3;j++)ring(c,xx,yy+20,12+f*(50+j*16),co,4,.45);debris(c,xx,yy,f,co,18,65);}
 if(el==='light'){ring(c,xx,yy,15+f*58,co,3);for(let j=0;j<6;j++){const an=j*Math.PI/3+age;line(c,xx+Math.cos(an)*20,yy+Math.sin(an)*20,xx+Math.cos(an)*(30+f*70),yy+Math.sin(an)*(30+f*70),'#fff1c1',3);}}
 c.globalAlpha=1;impact(c,xx,yy,age,.35,co,64);}
 c.globalCompositeOperation='source-over';if(a.weak){c.font="14px 'Journey JP',monospace";c.fillStyle='#ffe197';c.textAlign='right';c.fillText('WEAK ×1.5',l.fieldWidth-12,l.ceiling+45);}}
 if(skill&&a.style===1){c.globalCompositeOperation='screen';for(let j=0;j<5;j++)line(c,px,py-j*3,x,y-j*3,j===0?'#fff4cb':color,3);impact(c,x,y,age,.55,color,115);}
 if(skill&&a.style===2){c.globalCompositeOperation='screen';for(const q of l.enemies)impact(c,q.x,q.y-q.size*.5,age,.6,color,100);for(let j=0;j<3;j++)ring(c,px,py,20+clamp((age-.2-j*.1)/1)*l.fieldWidth,color+'77',3,.6);}
 if(a.kind==='dot'){for(const v of a.numbers){const q=v.enemy!==undefined?l.enemies[v.enemy]:l[keys[v.unit]];if(q)debris(c,q.x,q.y-q.size*.45,clamp(age/.8),v.enemy!==undefined?'#ffb06c':'#c5a0ee',14,35);}}
 c.restore();}
window.LanternEffects=Object.freeze({draw});})();
