/* v12: earned summons, build-defining sigils, contracts and the thirty-floor tower. */
(()=>{'use strict';const R=window.LanternRPG,J=window.LanternJourney;
const elements={fire:{name:'焔',color:'#ffad68',effect:'追撃＋2回の燃焼'},frost:{name:'霜',color:'#a3eaff',effect:'追撃＋敵の攻撃を1回弱体化'},gale:{name:'風',color:'#a4f6ca',effect:'敵全体へ追撃'},storm:{name:'雷',color:'#d6b2ff',effect:'防御を無視して追撃'},tide:{name:'潮',color:'#7cdeed',effect:'追撃＋最も傷ついた仲間を回復'},light:{name:'光',color:'#ffe7a6',effect:'追撃＋仲間全体へ護り'}};
const sigils=[['fire','燠火の牙',0],['frost','冬花の欠片',0],['gale','風渡りの羽',0],['storm','雷鳴の小鈴',0],['tide','潮騒の真珠',0],['light','道しるべの星',0],['fire','紅蓮の狼王',1],['frost','氷海の王冠',1],['gale','翠嵐の翼',1],['tide','深海の聖歌',1],['storm','天雷の神槍',2],['light','暁を呼ぶ灯',2]].map(([element,name,rarity],id)=>({id,element,name,rarity}));
const rarities=['R','SR','SSR','UR'],monsters=[{kind:'wolf',name:'燠火の猟狼',pattern:['hunt','poison','charge','strike'],weak:'frost',tip:'毒と狙撃　霜の紋章で攻撃を弱める'},{kind:'oracle',name:'深潮の祈祷師',pattern:['mend','drain','volley','strike'],weak:'storm',tip:'仲間を回復　先に狙って倒す'},{kind:'golem',name:'遺跡の重装兵',pattern:['ward','charge','heavy','shatter'],weak:'gale',tip:'護りと溜め攻撃　風の追撃で押し切る'},{kind:'wolf',name:'灰燼の疾走者',pattern:['poison','hunt','hunt','strike'],weak:'tide',tip:'毒を重ねる　潮の回復が有効'},{kind:'oracle',name:'鏡霜の詠唱者',pattern:['freeze','mend','volley','drain'],weak:'fire',tip:'技を遅らせる　焔の燃焼で回復を妨げる'},{kind:'golem',name:'暁の鐘衛',pattern:['shatter','ward','charge','heavy'],weak:'light',tip:'護りを砕く　溜め後は全体攻撃'},
{kind:'crab',name:'晶甲の潮蟹',pattern:['ward','strike','charge','heavy'],weak:'storm',tip:'硬い殻を張る　ミナの風縛りやロゼで護りを崩す'},
{kind:'wisp',name:'迷い灯の魔霊',pattern:['mend','volley','drain','mend'],weak:'fire',tip:'回復を繰り返す　焔の紋章で燃焼を与える'},
{kind:'harpy',name:'赤嵐の翼獣',pattern:['charge','hunt','volley','strike'],weak:'frost',tip:'溜めから強襲　霜で弱めるか、ダリオで溜めを解除'},
{kind:'serpent',name:'深碧の海蛇',pattern:['poison','drain','poison','heavy'],weak:'gale',tip:'毒と吸収　ユナやルチアの解毒と回復で耐える'}];
function seed(){return{version:12,tickets:0,shards:0,pity:0,rarePity:0,pulls:0,starter:false,levels:Array(12).fill(0),equipped:Array(R.chars.length).fill(null),styles:Array(R.chars.length).fill(0),tower:0,kills:Array(12).fill(0),daily:{date:R.dateKey(),wins:0,kills:0,tower:0,claims:[false,false,false]},history:[]};}
function ensure(s){const x=s.expansion||(s.expansion=seed());while(x.kills.length<12)x.kills.push(0);return x;}
const int=(v,max=999999)=>Number.isInteger(v)&&v>=0&&v<=max;
function valid(x){return x&&x.version===12&&['tickets','shards','pulls'].every(k=>int(x[k]))&&int(x.pity,29)&&int(x.rarePity,9)&&typeof x.starter==='boolean'&&Array.isArray(x.levels)&&x.levels.length===12&&x.levels.every(v=>int(v,5))&&Array.isArray(x.equipped)&&(x.equipped.length>=4&&x.equipped.length<=R.chars.length)&&x.equipped.every(v=>v===null||int(v,11)&&x.levels[v]>0)&&new Set(x.equipped.filter(v=>v!==null)).size===x.equipped.filter(v=>v!==null).length&&Array.isArray(x.styles)&&(x.styles.length>=4&&x.styles.length<=R.chars.length)&&x.styles.every(v=>int(v,2))&&int(x.tower,30)&&Array.isArray(x.kills)&&[8,12].includes(x.kills.length)&&x.kills.every(v=>int(v))&&/^\d{4}-\d{2}-\d{2}$/.test(x.daily?.date)&&['wins','kills','tower'].every(k=>int(x.daily[k]))&&Array.isArray(x.daily.claims)&&x.daily.claims.length===3&&x.daily.claims.every(v=>typeof v==='boolean')&&Array.isArray(x.history)&&x.history.length<=30&&x.history.every(v=>int(v,11));}
function today(s){const x=ensure(s),date=R.dateKey();if(date>x.daily.date)x.daily={date,wins:0,kills:0,tower:0,claims:[false,false,false]};return x.daily;}
function starter(s){const x=ensure(s);if(x.starter||s.next<1)return false;x.starter=true;x.tickets+=10;x.levels[0]=Math.max(1,x.levels[0]);if(x.equipped[0]===null)x.equipped[0]=0;return true;}
function summonCost(s,n){const x=ensure(s),tickets=Math.min(x.tickets,n);return{tickets,crystal:(n-tickets)*10};}
function summon(s,n,rng=Math.random){if(![1,10].includes(n)||s.next<1)return false;const x=ensure(s),c=summonCost(s,n);if(J.ensure(s).crystals.free<c.crystal)return false;x.tickets-=c.tickets;s.journey.crystals.free-=c.crystal;const result=[];for(let k=0;k<n;k++){const roll=rng(),rarity=x.pity>=29?2:roll<.05?2:x.rarePity>=9?1:roll<.30?1:0,pool=sigils.filter(a=>a.rarity===rarity),item=pool[Math.min(pool.length-1,Math.floor(rng()*pool.length))],duplicate=x.levels[item.id]>0,shards=duplicate?[4,12,40][rarity]:0;if(!duplicate)x.levels[item.id]=1;else x.shards=Math.min(999999,x.shards+shards);x.pity=rarity===2?0:x.pity+1;x.rarePity=rarity>=1?0:x.rarePity+1;x.pulls=Math.min(999999,x.pulls+1);x.history.unshift(item.id);result.push({...item,duplicate,shards});}x.history=x.history.slice(0,30);return result;}
function equip(s,id,rune){const x=ensure(s);if(!s.unlocked.includes(id)||!Number.isInteger(rune)||!sigils[rune]||!x.levels[rune])return false;x.equipped=x.equipped.map(v=>v===rune?null:v);x.equipped[id]=rune;return true;}
function upgrade(s,id){const x=ensure(s),lv=x.levels[id];if(!lv||lv>=5||x.shards<6*lv||s.resources.coin<20*lv)return false;x.shards-=6*lv;s.resources.coin-=20*lv;x.levels[id]++;return true;}
function exchange(s,id){const x=ensure(s),r=sigils[id];if(!r||x.levels[id])return false;const price=[24,72,200][r.rarity];if(x.shards<price)return false;x.shards-=price;x.levels[id]=1;return true;}
function rune(s,id){const x=s.expansion,key=x?.equipped[id];return key!==null&&key!==undefined?{...sigils[key],level:x.levels[key]}:null;}
function bonus(s,id){const a=rune(s,id);if(!a)return null;const n=a.level+a.rarity;return{hp:n*4,atk:['fire','storm','gale'].includes(a.element)?n:0,def:['frost','light'].includes(a.element)?n:0,heal:a.element==='tide'?n*2:0};}
const styles=[['陽炎連斬','焔の一閃','灯火の円舞'],['星彩乱射','貫星の一矢','翠雨の斉射'],['天光の流星','星砕き','星巡りの祈り'],['黎明の輪唱','深海の独唱','帰路の大合唱'],...R.chars.slice(4).map(c=>[c.special,c.special+'・穿',c.special+'・環'])];
function style(s,id){return s.expansion?.styles[id]||0;}
function setStyle(s,id,value){if(!s.unlocked.includes(id)||!Number.isInteger(value)||value<0||value>2||R.level(s.heroes[id].xp)<[1,4,8][value])return false;ensure(s).styles[id]=value;return true;}
function modify(s,event){const r=s.run;if(event.enemyAttack||!event.numbers?.some(v=>v.enemy!==undefined)||event.kind==='burst')return;const p=r.party[event.unit],a=rune(s,p.id);if(!a)return;p.runeTurns=(p.runeTurns||0)+1;if(p.runeTurns%3!==0&&event.kind!=='skill')return;event.element=a.element;event.runeName=a.name;const target=r.enemies[event.targetEnemy],z=R.stats(s,p.id),weak=target.weak===a.element,mul=.30+a.level*.06+a.rarity*.05,damage=Math.max(1,Math.round(z.atk*mul*(weak?1.5:1)));event.weak=weak;event.title+=' · '+elements[a.element].name;const hit=(enemy,i,n)=>{const amount=Math.min(enemy.hp,n);enemy.hp-=amount;if(amount)event.numbers.push({enemy:i,n:amount,rune:true});};if(a.element==='gale')r.enemies.forEach((e,i)=>hit(e,i,damage));else hit(target,event.targetEnemy,a.element==='storm'?Math.round(damage*1.4):damage);if(a.element==='fire')target.burn=2;if(a.element==='frost')target.chill=1;if(a.element==='tide'){const q=r.party.filter(p=>p.hp>0).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0],n=Math.min(q.maxHp-q.hp,Math.round(damage*.8));q.hp+=n;if(n)event.numbers.push({unit:r.party.indexOf(q),n,heal:true});}if(a.element==='light')for(const q of r.party)if(q.hp>0)q.shield=Math.min(1000,q.shield+Math.round(damage*.6));event.killed=target.hp===0;}
function towerSpec(floor){const group=Math.floor((floor-1)/5),stage=Math.min(20,group*3+2),mod=(floor-1)%5;return{floor,stage,required:stage+1,multiplier:1.08+mod*.16,name:['堅殻','猛毒','詠唱','疾風','守門'][mod],description:['敵の護りが厚い','毒の敵が多い','回復役を先に狙おう','敵の攻撃力が高い','ボスの全体攻撃に備えよう'][mod]};}
function canTower(s,f){return Number.isInteger(f)&&f>=1&&f<=30&&f<=ensure(s).tower+1&&s.next>=towerSpec(f).required;}
function tune(s,r){if(!r.tower)return;const spec=towerSpec(r.tower);for(const [i,e] of r.enemies.entries()){const m=monsters[(r.tower+r.wave+i)%monsters.length];Object.assign(e,m,{trait:m.pattern[0]==='heavy'?'charge':['mend','volley','poison'].includes(m.pattern[0])?'strike':m.pattern[0]});e.maxHp=e.hp=Math.min(50000,Math.round(e.maxHp*spec.multiplier));e.atk=Math.round(e.atk*(1.04+(r.tower-1)%5*.06));if(spec.name==='堅殻')e.ward=2;e.name=(e.boss?'守門・':'')+m.name;}}
function towerFinish(s){const r=s.run,x=ensure(s),first=r.tower>x.tower;x.tower=Math.max(x.tower,r.tower);r.first=first;r.reward={coin:30+r.tower*5,dust:5+Math.floor(r.tower/2),books:first?3:1,crests:first&&r.tower%5===0?2:0};J.credit(s,r.reward);r.extraReward={tickets:first?1:0,crystal:first?15:0};x.tickets=Math.min(999999,x.tickets+r.extraReward.tickets);J.credit(s,{crystal:r.extraReward.crystal});r.loot=[R.roll(s,window.LanternCombat.stages[r.stage],r.tower%5===0?2:1)];r.levels=[];for(const id of s.unlocked){const before=R.level(s.heroes[id].xp);s.heroes[id].xp=Math.min(1000000,s.heroes[id].xp+12);const after=R.level(s.heroes[id].xp);if(after>before)r.levels.push({id,before,after});}record(s);}
const monsterKeys=['stag','warden','moth','knight','wyrm','wolf','oracle','golem','crab','wisp','harpy','serpent'];
function countWave(s){const r=s.run,x=ensure(s);if(r.countedWave===r.wave)return;r.countedWave=r.wave;let count=0;for(const e of r.enemies)if(e.hp===0){const i=monsterKeys.indexOf(e.kind);if(i>=0)x.kills[i]=Math.min(999999,x.kills[i]+1);count++;}const d=today(s);d.kills=Math.min(999999,d.kills+count);}
function record(s){const r=s.run;if(r.expansionRecorded)return;r.expansionRecorded=true;countWave(s);const x=ensure(s),d=today(s);if(r.reason==='won'){d.wins=Math.min(999999,d.wins+1);if(r.tower)d.tower=Math.min(999999,d.tower+1);else{J.credit(s,{crystal:r.first?5:1});r.extraReward={crystal:r.first?5:1,tickets:0};}}}
const contracts=[{name:'道をつなぐ',key:'wins',target:3,tickets:1,coin:40},{name:'里を守る',key:'kills',target:10,tickets:1,coin:50},{name:'塔へ挑む',key:'tower',target:1,tickets:2,coin:80}];
function claim(s,index){const d=today(s),c=contracts[index];if(!c||d.claims[index]||d[c.key]<c.target)return false;d.claims[index]=true;const x=ensure(s);x.tickets=Math.min(999999,x.tickets+c.tickets);J.credit(s,{coin:c.coin});return c;}
function goldBuy(s,id){const products=[{price:60,reward:{dust:12}},{price:90,reward:{books:4}},{price:150,reward:{crests:2}}],p=products[id];if(!p||s.resources.coin<p.price)return false;s.resources.coin-=p.price;J.credit(s,p.reward);return p;}
window.LanternExpansion=Object.freeze({ensure,valid,today,starter,sigils,rarities,elements,monsters,summonCost,summon,equip,upgrade,exchange,rune,bonus,styles,style,setStyle,modify,towerSpec,canTower,tune,towerFinish,record,countWave,monsterKeys,contracts,claim,goldBuy});})();
