/* Permanent, free local event. Rewards and progress are isolated from the campaign. */
(()=>{'use strict';
const R=window.LanternRPG,D=window.LanternFestivalContent;
function ensure(s){if(!s.festival)s.festival={version:1,wins:[0,0,0],best:[0,0,0],heard:[]};return s.festival;}
function valid(s){const f=s.festival;if(!f||f.version!==1||!['wins','best'].every(k=>Array.isArray(f[k])&&f[k].length===3&&f[k].every(n=>Number.isInteger(n)&&n>=0&&n<=100000))||!Array.isArray(f.heard)||f.heard.length>32||f.heard.some(x=>typeof x!=='string'||x.length>80))return false;const id=s.run?.festival;return id===undefined||(Number.isInteger(id)&&id>=0&&id<3&&s.next>=id+1&&(id===0||f.wins[id-1]>0)&&s.run.stage===0&&s.run.difficulty===0&&!s.run.tower);}
function open(s,id){return Number.isInteger(id)&&id>=0&&id<3&&s.next>=id+1&&(id===0||ensure(s).wins[id-1]>0);}
function tune(s,r){if(r.festival===undefined)return;const c=D.challenges[r.festival],waves=c.battle.waves;r.route=c.battle.route;r.visual=c.battle.visual;r.enemies=R.copy(waves?waves[r.wave].enemies:c.battle.enemies);for(const e of r.enemies){e.hp=e.maxHp;e.boss=r.wave===2;e.poise=e.poise||0;e.charge=0;e.marks=0;}r.enemy=r.enemies[0];r.target=0;}
function start(s,id){ensure(s);if(!open(s,id))return null;const r=window.LanternCombat.start(s,0,0);r.festival=id;tune(s,r);return r;}
function finish(s,reason){const r=s.run;if(!r||r.festival===undefined||r.reason)return false;r.reason=reason;s.scene='result';r.events=[];s.tonic.count=Math.min(99,s.tonic.count+r.tonics);if(reason!=='won')return true;const f=ensure(s),id=r.festival,c=D.challenges[id],first=f.wins[id]===0,g=first?c.firstReward:c.repeatReward;r.first=first;r.reward={coin:0,dust:0,books:0,crests:0,...g.resources};for(const k in r.reward)s.resources[k]=Math.min(999999,s.resources[k]+r.reward[k]);window.LanternJourney.ensure(s);window.LanternExpansion.ensure(s);s.journey.crystals.free=Math.min(999999,s.journey.crystals.free+g.crystal);s.expansion.tickets=Math.min(999999,s.expansion.tickets+g.tickets);r.extraReward={crystal:g.crystal};r.extraTickets=g.tickets;r.xp=g.xp;r.levels=[];for(const id of s.party){const before=R.level(s.heroes[id].xp);s.heroes[id].xp=Math.min(1000000,s.heroes[id].xp+g.xp);const after=R.level(s.heroes[id].xp);if(after>before)r.levels.push({id,before,after});}r.loot=[];f.wins[id]=Math.min(100000,f.wins[id]+1);const turns=Math.min(100000,1+(r.totalRounds||r.round));f.best[id]=f.best[id]?Math.min(f.best[id],turns):turns;r.ending=first?R.copy(c.after):[];if(first&&id===2)r.ending.push(...R.copy(D.completion.after));return true;}
window.LanternFestival=Object.freeze({data:D,ensure,valid,open,start,tune,finish});
})();
