/* Persistent v10 systems. No payment balance can be issued by the client. */
(()=>{'use strict';
const R=window.LanternRPG,integer=(v,max=999999)=>Number.isInteger(v)&&v>=0&&v<=max;
const setNames=['道しるべ','深森の風','護石の誓い','潮白の祈り','鏡星の記憶','嵐夜の和音','暁光の帰路'];
function seed(){return{version:10,crystals:{free:0,paid:0},quest:[0,0],known:Array(35).fill(false),mastery:Array(21).fill(0),claims:Array(21).fill(0),setClaims:Array(7).fill(false),dismantled:0,upgrades:0,victories:0,dailyCrystalDate:null,heard:[]};}
function valid(j){return !!j&&j.version===10&&integer(j.crystals?.free)&&j.crystals?.paid===0&&Array.isArray(j.quest)&&j.quest.length===2&&j.quest.every(v=>integer(v,3))&&Array.isArray(j.known)&&j.known.length===35&&j.known.every(v=>typeof v==='boolean')&&['mastery','claims'].every(k=>Array.isArray(j[k])&&j[k].length===21&&j[k].every(v=>integer(v,15)))&&j.claims.every((v,i)=>(v&j.mastery[i])===v)&&Array.isArray(j.setClaims)&&j.setClaims.length===7&&j.setClaims.every(v=>typeof v==='boolean')&&['dismantled','upgrades','victories'].every(k=>integer(j[k]))&&(j.dailyCrystalDate===null||/^\d{4}-\d{2}-\d{2}$/.test(j.dailyCrystalDate))&&Array.isArray(j.heard)&&j.heard.length<=80&&j.heard.every(v=>typeof v==='string'&&v.length<=50);}
function ensure(s){if(!s.journey)s.journey=seed();collect(s);return s.journey;}
function collect(s){const j=s.journey;if(!j)return;for(const x of s.gear)if(x.rarity>=1)j.known[(x.tier-1)*5+R.slots.indexOf(x.slot)]=true;}
function setInfo(s,equipment){const counts=Array(7).fill(0);for(const id of Object.values(equipment||{})){const x=s.gear.find(x=>x.id===id);if(x?.rarity>=1)counts[x.tier-1]++;}return counts.map((n,i)=>({tier:i+1,name:setNames[i],count:n,bonus:{hp:n>=2?6+(i+1)*2:0,def:n>=2?1:0,atk:n>=4?2+Math.floor((i+1)/2):0,heal:n>=4?i+1:0}})).filter(x=>x.count);}
function bonus(s,equipment){const b={hp:0,def:0,atk:0,heal:0};for(const x of setInfo(s,equipment))for(const k in b)b[k]+=x.bonus[k];return b;}
function credit(s,reward){ensure(s);for(const [k,n]of Object.entries(reward))if(k==='crystal')s.journey.crystals.free=Math.min(999999,s.journey.crystals.free+n);else s.resources[k]=Math.min(999999,s.resources[k]+n);}
function complete(s){const j=ensure(s),r=s.run;if(r.reason!=='won'||r.journeyRecorded)return;r.journeyRecorded=true;j.victories=Math.min(999999,j.victories+1);let mask=1;if(r.party.every(p=>p.hp>0))mask|=2;if(r.tonics===0)mask|=4;if(r.difficulty>=1)mask|=8;j.mastery[r.stage]|=mask;collect(s);}
const masteryNames=['踏破','全員生還','薬なし','HARD以上'];
function claimMastery(s,index){const j=ensure(s),bits=j.mastery[index]&~j.claims[index];if(!bits)return false;const n=[1,2,4,8].filter(b=>bits&b).length;j.claims[index]|=bits;const reward={crystal:n*5,coin:n*5};credit(s,reward);return reward;}
function claimSet(s,tier){const j=ensure(s);if(!integer(tier,7)||tier<1||j.setClaims[tier-1]||!j.known.slice((tier-1)*5,tier*5).every(Boolean))return false;j.setClaims[tier-1]=true;const reward={crystal:25,crests:2};credit(s,reward);return reward;}
const products=[{id:'supplies',name:'灯宿の育成包',description:'コイン120・灯晶20・技書6',price:20,reward:{coin:120,dust:20,books:6}},{id:'awakening',name:'灯守りの覚醒印箱',description:'覚醒印4・技書4',price:25,reward:{crests:4,books:4}},{id:'forge',name:'鍛冶師の素材箱',description:'コイン200・灯晶35',price:30,reward:{coin:200,dust:35}}];
function buy(s,id){const item=products.find(p=>p.id===id),j=ensure(s);if(!item||j.crystals.free<item.price)return false;j.crystals.free-=item.price;credit(s,item.reward);return item;}
function craftCost(tier,rarity){return{coin:12+tier*6+rarity*10,dust:4+tier*2+rarity*4};}
function craft(s,{tier,rarity,slot,role}){if(!integer(tier,7)||tier<1||tier>Math.min(7,Math.floor(s.next/3)+1)||![1,2].includes(rarity)||!R.slots.includes(slot)||!s.unlocked.includes(role)||s.gear.length>=300)return false;const c=craftCost(tier,rarity);if(s.resources.coin<c.coin||s.resources.dust<c.dust)return false;for(const k in c)s.resources[k]-=c[k];const x=R.grant(s,slot,role,tier,rarity);x.locked=true;x.affix=slot==='weapon'?'edge':slot==='armor'||slot==='helm'?'ward':'heart';collect(s);return x;}
function condition(s,c){if(c.id==='all')return c.conditions.every(x=>condition(s,x));if(c.id==='campaign_started')return s.scene!=='prologue';if(c.id==='sidequest_step_complete'){const n=c.stepId.startsWith('hana')?0:1;return ensure(s).quest[n]>=Number(c.stepId.split('_').at(-1));}if(!c.type&&c.id==='win_hard_stage')return window.LanternTrials.progress(s,1)>c.stageIndex;if(!c.type&&['clear_stage','win_chapter_boss'].includes(c.id))return s.clears[c.stageIndex]>=(c.requiredStars||1);switch(c.type){case 'stage_clear':return s.clears[c.stageIndex]>0;case 'chapter_boss_clear':return s.clears[c.stageIndex]>0;case 'equip_five':return R.slots.every(k=>s.equipped[c.memberId??0][k]);case 'upgrade_any':return ensure(s).upgrades>=1||s.gear.some(x=>x.rank>=1);case 'dismantle_count':return ensure(s).dismantled>=c.count;case 'hard_clear':return window.LanternTrials.progress(s,1)>c.stageIndex;default:return false;}}
function quest(s,n){const chain=window.LanternNarrative?.quests?.[n];if(!chain)return null;const index=ensure(s).quest[n];return{chain,index,step:chain.steps[index]||null};}
const rewards=[{coin:20,dust:5,crystal:10},{coin:30,books:3,crystal:15},{coin:50,crests:2,crystal:20}];
function claimQuest(s,n){const q=quest(s,n);if(!q?.step||!condition(s,q.step.unlock)||!condition(s,q.step.condition))return false;ensure(s).quest[n]++;credit(s,rewards[q.index]);return{step:q.step,reward:rewards[q.index]};}
function daily(s,date){const j=ensure(s);if(j.dailyCrystalDate&&date<=j.dailyCrystalDate)return false;j.dailyCrystalDate=date;credit(s,{crystal:5});return true;}
window.LanternJourney=Object.freeze({ensure,valid,collect,setInfo,bonus,setNames,complete,masteryNames,claimMastery,claimSet,products,buy,craftCost,craft,condition,quest,claimQuest,rewards,daily,credit});
})();
