/* Local loot instances, honest stat comparisons and deterministic equipped IDs. */
(()=>{'use strict';
const rarities=[{name:'旅装',color:'#c6d2c6',bonus:1},{name:'上質',color:'#87d7b4',bonus:2},{name:'希少',color:'#8ac7f3',bonus:4},{name:'英雄',color:'#d7abfa',bonus:6}];
function empty(){return{serial:0,bag:[],equipped:Array.from({length:3},()=>({weapon:null,armor:null,charm:null}))};}
function restore(v,equipment,owned){if(!v)return empty();if(!Number.isInteger(v.serial)||v.serial<0||v.serial>1e7||!Array.isArray(v.bag)||v.bag.length>200||!Array.isArray(v.equipped)||v.equipped.length!==3)return null;const ids=new Set();for(const x of v.bag){if(!x||typeof x.id!=='string'||!/^drop\d+$/.test(x.id)||ids.has(x.id)||Number(x.id.slice(4))>v.serial||Number(x.id.slice(4))<1||!Object.hasOwn(equipment,x.base)||!owned.includes(x.base)||!Number.isInteger(x.rarity)||x.rarity<0||x.rarity>3||!Number.isInteger(x.power)||x.power<1||x.power>12||!Number.isInteger(x.defense)||x.defense<0||x.defense>5)return null;ids.add(x.id);}const equippedIds=new Set();for(let i=0;i<3;i++)for(const slot of['weapon','armor','charm']){const id=v.equipped[i]?.[slot];if(id===null)continue;if(equippedIds.has(id))return null;equippedIds.add(id);const x=v.bag.find(x=>x.id===id),e=x&&equipment[x.base];if(!e||e.slot!==slot||slot==='weapon'&&e.role!==i)return null;}const out=JSON.parse(JSON.stringify(v));for(const x of out.bag){if(x.level!==undefined&&(!Number.isInteger(x.level)||x.level<0||x.level>5)||x.locked!==undefined&&typeof x.locked!=='boolean'||x.affix!==undefined&&!['edge','ward','heart',null].includes(x.affix))return null;x.level??=0;x.locked??=false;x.affix??=null;}return out;}
function grant(s,base,rarity=1,power=1){const x={id:'drop'+(++s.loot.serial),base,rarity,power,defense:0,level:0,locked:false,affix:null};s.loot.bag.push(x);if(!s.progress.owned.includes(base))s.progress.owned.push(base);return x;}
function roll(s,r,equipment){const slot=Math.random()<.65?'weapon':Math.random()<.55?'armor':'charm',role=Math.floor(Math.random()*(r.roster||3)),pool=Object.entries(equipment).filter(([,e])=>e.slot===slot&&(slot!=='weapon'||e.role===role));const [base]=pool[Math.floor(Math.random()*pool.length)],chance=Math.random(),rarity=chance>.96?3:chance>.78?2:chance>.40?1:0,tier=r.difficulty===2?Math.max(2,rarity):r.node===2||r.difficulty===1?Math.max(1,rarity):rarity,power=Math.min(12,rarities[tier].bonus+Math.floor(Math.random()*3)+(r.route==='tide'?1:0)),x={id:'drop'+(++s.loot.serial),base,rarity:tier,power,level:0,locked:false,affix:tier>=1?['edge','ward','heart'][Math.floor(Math.random()*3)]:null,defense:slot==='armor'?Math.min(5,1+Math.floor(power/3)):slot==='charm'&&Math.random()<.3?1:0};s.loot.bag.push(x);if(!s.progress.owned.includes(base))s.progress.owned.push(base);if(s.loot.bag.length>200){s.loot.bag.pop();const dust=window.LanternForge.value(x);s.forge.dust=Math.min(999999,s.forge.dust+dust);r.overflowDust=(r.overflowDust||0)+dust;x.converted=true;x.id=null;}return x;}
function itemStats(base,x){if(!x)return{attack:0,heal:0,defense:0};const lv=x.level||0;return{attack:(base.slot==='weapon'?x.power+lv*2:base.slot==='charm'?x.power+lv:0)+(x.affix==='edge'?2:0),heal:(base.slot==='weapon'?x.power+lv:0)+(x.affix==='heart'?3:0),defense:x.defense+(base.slot==='armor'?lv:0)+(x.affix==='ward'?1:0)};}
function score(base,x,role){const z=itemStats(base,x);if(base.slot==='weapon')return(base.attack||0)+(base.mark||0)*.2+(base.heal||0)*.65+z.attack*1.8+z.heal*.3+z.defense*3;return base.slot==='armor'?(base.name==='石守りの羽織'?3:0)+z.defense*6+z.attack*1.8+z.heal*.3:(base.name==='琥珀の灯石'?2:base.name==='護石のかけら'?5:3)+z.attack+z.defense*5+z.heal*.3;}
function stats(s,unit){const l=s.loot.equipped[unit],total={attack:0,heal:0,defense:0};for(const slot of ['weapon','armor','charm']){const x=s.loot.bag.find(x=>x.id===l[slot]);if(!x)continue;const z=itemStats({slot},x);for(const key in total)total[key]+=z[key];}return total;}
function recommend(s,equipment){const used=new Set();for(let unit=0;unit<(s.campaign?.roster||3);unit++)for(const slot of['weapon','armor','charm']){const all=Object.entries(equipment).filter(([id,e])=>s.progress.owned.includes(id)&&e.slot===slot&&(slot!=='weapon'||e.role===unit)).map(([base,e])=>({base,id:null,value:score(e,null,unit)}));for(const x of s.loot.bag){const e=equipment[x.base];if(!used.has(x.id)&&e.slot===slot&&(slot!=='weapon'||e.role===unit))all.push({base:x.base,id:x.id,value:score(e,x,unit)});}all.sort((a,b)=>b.value-a.value||String(a.id).localeCompare(String(b.id)));s.loadouts[unit][slot]=all[0].base;s.loot.equipped[unit][slot]=all[0].id;if(all[0].id)used.add(all[0].id);}return true;}
function label(x,equipment){return rarities[x.rarity].name+' '+equipment[x.base].name+((x.level||0)?' 強化+'+x.level:'');}
function surplus(s,equipment){return s.loot.bag.filter(x=>!window.LanternForge.protectedItem(s,x.id)&&!x.level&&x.rarity<2&&s.loot.bag.some(y=>y.id!==x.id&&y.base===x.base&&(score(equipment[y.base],y,0)>score(equipment[x.base],x,0)||score(equipment[y.base],y,0)===score(equipment[x.base],x,0)&&Number(y.id.slice(4))<Number(x.id.slice(4))))).map(x=>x.id);}
function prune(s,equipment){return window.LanternForge.dismantle(s,surplus(s,equipment));}
window.LanternLoot=Object.freeze({rarities,empty,restore,roll,grant,score,stats,recommend,label,prune,surplus,itemStats});
})();
