/* Original allies: one identity, combat trait and portrait per character. */
window.LanternRosterData=[
 {catalogId:'ally.sera',name:'セラ',job:'紅蓮の双剣',role:0,element:'fire',rarity:1,trait:'burn',hp:75,atk:17,def:3,heal:0,special:'紅蓮の舞踏',secondary:'火守り',passive:'残り火',color:'#ff9672',bio:'灰の谷から来た双剣士　消えた故郷の炉を、もう一度灯したい',traitText:'攻撃するたび燃焼を2回付与'},
 {catalogId:'ally.balt',name:'バルト',job:'霜壁の守護者',role:0,element:'frost',rarity:0,trait:'guard',hp:102,atk:10,def:8,heal:0,special:'不動の氷城',secondary:'氷の城壁',passive:'老兵の誓い',color:'#b4e3ff',bio:'北の関所を守り続けた老騎士　逃げる人の背中に、盾を向けることはない',traitText:'各WAVE開始時、全員に自身の防御×2の盾'},
 {catalogId:'ally.finn',name:'フィン',job:'梟の狩人',role:1,element:'gale',rarity:0,trait:'execute',hp:65,atk:16,def:3,heal:0,special:'梟影の一矢',secondary:'獣縛り',passive:'狩人の眼',color:'#b1e998',bio:'道を失った旅人を森から導く狩人　梟だけが彼の本名を知っている',traitText:'体力35%以下の敵へ攻撃力35%の追撃'},
 {catalogId:'ally.lyra',name:'ライラ',job:'雷紋の賢者',role:2,element:'storm',rarity:2,trait:'chain',hp:59,atk:17,def:2,heal:6,special:'天雷の連鎖',secondary:'雷灯の癒し',passive:'雷の残響',color:'#d2afff',bio:'嵐の図書館で鐘の音を研究する学者　雷もまた、空が鳴らす音だという',traitText:'攻撃時、別の敵へ攻撃力30%の連鎖'},
 {catalogId:'ally.yuna',name:'ユナ',job:'真珠の祈り手',role:2,element:'tide',rarity:0,trait:'cleanse',hp:67,atk:9,def:4,heal:16,special:'満ち潮の祈り',secondary:'真珠の手当て',passive:'澄んだ潮',color:'#9cebe3',bio:'沈んだ灯台で一人、灯を守っていた癒し手　今度は誰も置いていかない',traitText:'行動するたび最も傷ついた味方を癒力25%回復し解毒'},
 {catalogId:'ally.leon',name:'レオン',job:'白陽の聖騎士',role:3,element:'light',rarity:1,trait:'bulwark',hp:95,atk:13,def:7,heal:8,special:'白陽の聖域',secondary:'光の誓約',passive:'白陽の護り',color:'#ffe2a1',bio:'王都を離れた若き騎士　守るべきものは旗ではなく、目の前の暮らしだ',traitText:'自身の行動後、味方全員に防御50%の盾'},
 {catalogId:'ally.kagetsu',name:'カゲツ',job:'灰燼の追刃',role:0,element:'fire',rarity:0,trait:'drain',hp:70,atk:18,def:2,heal:0,special:'灰燼の六閃',secondary:'影纏い',passive:'帰るための刃',color:'#ff9a73',bio:'かつて鐘を盗んだ一族の末裔　彼の刃は今、帰る道を切り開く',traitText:'与えたダメージの12%で自分を回復'},
 {catalogId:'ally.iris',name:'イリス',job:'鏡霜の魔女',role:2,element:'frost',rarity:1,trait:'chill',hp:61,atk:16,def:3,heal:9,special:'静寂の氷華',secondary:'雪解けの灯',passive:'止まる一瞬',color:'#cfddff',bio:'凍った湖に閉じ込められた歌を集める魔女　温かい紅茶には少し弱い',traitText:'通常攻撃など3回ごと、敵の次の攻撃を35%軽減'},
 {catalogId:'ally.nene',name:'ネネ',job:'翠風の奏者',role:3,element:'gale',rarity:0,trait:'haste',hp:68,atk:10,def:4,heal:12,special:'旅立ちの風歌',secondary:'風の和音',passive:'軽やかな足取り',color:'#9ee9ae',bio:'旅の見聞を歌にする楽師　まだ誰も知らない七つ目の旋律を探している',traitText:'行動するたび、生存中の味方の技ゲージ+5'},
 {catalogId:'ally.zeno',name:'ゼノ',job:'紫電の槍士',role:0,element:'storm',rarity:1,trait:'pierce',hp:80,atk:17,def:4,heal:0,special:'紫電一閃',secondary:'雷槍の構え',passive:'貫く覚悟',color:'#b7bdff',bio:'空の裂け目を渡ってきた槍士　行き先よりも、同行者を信じる',traitText:'攻撃時、攻撃力20%の防御無視追撃'},
 {catalogId:'ally.marina',name:'マリナ',job:'蒼潮の船長',role:1,element:'tide',rarity:0,trait:'plunder',hp:76,atk:15,def:4,heal:0,special:'蒼潮の斉射',secondary:'碇の鎖',passive:'船長の分け前',color:'#96e5ee',bio:'地図から消えた港を探す船長　見つけた宝は、必ず仲間と分け合う',traitText:'編成して勝利するとゴールド報酬+15%'},
 {catalogId:'ally.aster',name:'アステル',job:'暁星の観測者',role:2,element:'light',rarity:2,trait:'nova',hp:66,atk:18,def:4,heal:10,special:'暁星の超新星',secondary:'星の再生',passive:'星巡り',color:'#ffe0a2',bio:'夜空にあるはずのない星を追う観測者　その星は、里の鐘が鳴るたび近づく',traitText:'必殺技で敵全体に攻撃力60%の追撃'},
 {catalogId:'ally.rose',name:'ロゼ',job:'焔潮の海賊',role:0,element:'fire',rarity:1,trait:'shatterer',hp:78,atk:16,def:4,heal:0,special:'緋潮の三日月',secondary:'帆影の護り',passive:'錨砕き',color:'#ff9d6b',bio:'嵐に沈んだ船の鐘を探す海賊　敵の堅い殻を割る一撃が、再出航の合図になる',traitText:'攻撃後、敵の護りを1段階削る　護りを割ると体勢を崩す'},
 {catalogId:'ally.gald',name:'ガルド',job:'氷峡の盾兵',role:0,element:'frost',rarity:0,trait:'rampart',hp:105,atk:10,def:8,heal:0,special:'氷峡の防波堤',secondary:'砕けぬ盾',passive:'氷の備え',color:'#b7e5ff',bio:'山峡の避難路を守っていた盾兵　里の子供がくれた貝殻を、盾の内側に結んでいる',traitText:'各WAVE開始時に全員へ防御×2の盾　自分にはさらに防御×2'},
 {catalogId:'ally.koharu',name:'コハル',job:'風駆けの射手',role:1,element:'gale',rarity:0,trait:'hunter',hp:65,atk:16,def:3,heal:0,special:'風切りの照準',secondary:'葉隠れの罠',passive:'隙を射る',color:'#adeba1',bio:'森の郵便を運ぶ弩使い　届かなかった最後の手紙を、まだ懐にしまっている',traitText:'溜め中の敵に攻撃力40%の追撃　技ゲージも+10'},
 {catalogId:'ally.dario',name:'ダリオ',job:'雷雲の巡礼者',role:2,element:'storm',rarity:1,trait:'disrupt',hp:72,atk:14,def:4,heal:8,special:'雷雲の封鐘',secondary:'巡礼の手当て',passive:'詠唱を断つ',color:'#d2b2ff',bio:'鳴らない鐘を巡る旅の僧　雷鳴の直前に訪れる静寂を、武器に変える',traitText:'必殺技で敵の溜めを解除し、次の攻撃を35%弱める'},
 {catalogId:'ally.lucia',name:'ルチア',job:'深潮の錬金術師',role:2,element:'tide',rarity:2,trait:'remedy',hp:70,atk:11,def:4,heal:16,special:'蒼き生命の雫',secondary:'海薬の調合',passive:'解毒の滴',color:'#98e8f6',bio:'潮の満ち引きで薬を作る錬金術師　毒に沈んだ入り江を、生き物の戻る海へ変えたい',traitText:'3行動ごとに生存中の全員を解毒・癒力50%回復'},
 {catalogId:'ally.sol',name:'ソル',job:'日輪の鐘守',role:3,element:'light',rarity:2,trait:'daybreak',hp:83,atk:12,def:6,heal:12,special:'日輪の福音',secondary:'光輪の調べ',passive:'夜明けの合図',color:'#ffe2a0',bio:'日の出に合わせて鐘を磨く青年　音を失った里にも、朝が来ることを信じている',traitText:'各WAVE開始時、全員の技ゲージ+20　必殺技で全員へ+10'},
 {catalogId:'ally.lumina',name:'ルミナ',job:'星海の記録者',role:2,element:'storm',rarity:3,trait:'starlight',hp:67,atk:18,def:3,heal:10,special:'星海のアストラル',secondary:'星の還流',passive:'星座の導き',color:'#e3bfff',bio:'消えた星の名を覚えている記録者　里の鐘に反応した星図をたどり、この港へ来た',traitText:'弱点属性の追撃が発動すると、別の敵へ攻撃力50%の追撃'},
 {catalogId:'ally.orphe',name:'オルフェ',job:'暁冠の騎士',role:0,element:'light',rarity:3,trait:'oath',hp:94,atk:17,def:6,heal:0,special:'暁冠のエクレール',secondary:'暁の誓約',passive:'帰還の誓い',color:'#ffd38d',bio:'帰らなかった騎士の名を背負う旅人　今度こそ、最後の一人まで連れ帰ると誓った',traitText:'必殺技で全員に攻撃力50%の盾　体力半分以下の味方へ同量の回復'}
];
