/* Shared rules: the exact same stats drive combat, equipment previews and power. */
(()=>{'use strict';
const slots=['weapon','armor','helm','accessory','relic'];
const slotNames={weapon:'武器',armor:'防具',helm:'頭装備',accessory:'アクセサリー',relic:'灯具'};
const chars=[
 {id:0,key:'hero',catalogId:'story.allen',name:'アレン',job:'灯の剣士',hp:78,atk:15,def:4,heal:0,special:'陽炎連斬',secondary:'灯の誓い',passive:'不屈の灯',color:'#ffbd70'},
 {id:1,key:'mina',catalogId:'story.mina',name:'ミナ',job:'風の弓手',hp:66,atk:14,def:3,heal:0,special:'星彩乱射',secondary:'風縛り',passive:'風読み',color:'#8aeed1'},
 {id:2,key:'rio',catalogId:'story.rio',name:'リオ',job:'星の癒し手',hp:62,atk:11,def:3,heal:11,special:'天光の流星',secondary:'灯の手当て',passive:'星の護り',color:'#c8b5ff'},
 {id:3,key:'noah',catalogId:'story.noah',name:'ノア',job:'潮の吟遊詩人',hp:68,atk:10,def:4,heal:12,special:'黎明の輪唱',secondary:'守りの和音',passive:'響きの絆',color:'#91d9ff'}];
chars.push(...window.LanternRosterData.map((c,i)=>({...c,id:i+4,key:'ally'+i})));
const role=id=>chars[id]?.role??id;
const rarities=[{name:'N 旅装',color:'#c2d0c5'},{name:'R 上質',color:'#8fe0bc'},{name:'SR 希少',color:'#8bc9ff'},{name:'SSR 英雄',color:'#dbadff'},{name:'UR 神話',color:'#ffe19a'}];
const prefixes=[{id:'edge',name:'猛攻',atk:2,hp:0,def:0,heal:0},{id:'ward',name:'堅守',atk:0,hp:0,def:1,heal:0},{id:'vital',name:'生命',atk:0,hp:10,def:0,heal:0},{id:'heart',name:'慈愛',atk:0,hp:0,def:0,heal:3}];
const difficulties=[{name:'NORMAL',hp:2.05,atk:1.6,reward:1,xp:12},{name:'HARD',hp:3.1,atk:2.3,reward:3,xp:36},{name:'EXPERT',hp:5.2,atk:3.8,reward:7,xp:72}];
const int=(n,a,b)=>Number.isInteger(n)&&n>=a&&n<=b,copy=o=>JSON.parse(JSON.stringify(o));
function level(xp){return Math.min(60,xp<522?1+Math.floor(xp/18):30+Math.floor((xp-522)/60));}
function empty(){const s={version:9,scene:'prologue',next:0,selectedChapter:0,difficulty:0,resources:{coin:60,dust:18,books:4,crests:0},heroes:chars.map(()=>({xp:0,rank:0,skills:{special:0,secondary:0,passive:0}})),unlocked:[0],party:[0],decks:[[0],null,null],deck:0,gear:[],equipped:chars.map(()=>Object.fromEntries(slots.map(k=>[k,null]))),serial:0,clears:Array(21).fill(0),tonic:{count:3,level:0},daily:{date:null,day:0},story:null,run:null,settings:{music:.65,effects:.8,ambience:.4,speed:1,auto:true,policy:'balanced',autoNext:false},seen:[]};for(const slot of slots){const x=grant(s,slot,slot==='weapon'?0:null,1,0);x.rank=1;s.equipped[0][slot]=x.id;}window.LanternTrials?.ensure(s);return s;}
function gearName(x){const stem=x.slot==='weapon'?['潮騒の剣','風読みの弓','星灯の杖','海歌の竪琴'][role(x.role)]:{armor:'旅人の外套',helm:'灯守りの冠',accessory:'潮色の指輪',relic:'帰路の灯石'}[x.slot];return (x.tempered===2?'覇・':x.tempered===1?'鋼・':'')+(x.tier>1?['','', '深森','護石','潮白','鏡星','嵐夜','暁光'][x.tier]+'の':'')+stem+(x.rank?' +'+x.rank:'');}
function grant(s,slot,role,tier=1,rarity=0){const x={id:'g'+(++s.serial),slot,role:slot==='weapon'?role:null,tier,rarity,rank:0,locked:false,affix:null};s.gear.push(x);return x;}
function gearStats(x){const t=x.tier,r=x.rarity,n=x.rank,z={hp:0,atk:0,def:0,heal:0};if(x.slot==='weapon'){z.atk=3+t+r*2+n*2;if(role(x.role)>=2)z.heal=1+r+n;}if(x.slot==='armor'){z.hp=9+t*3+r*5+n*5;z.def=1+Math.floor((t+r+n)/2);}if(x.slot==='helm'){z.hp=5+t*2+r*3+n*3;z.def=1+Math.floor((r+n)/3);}if(x.slot==='accessory'){z.atk=1+Math.floor((t+r+n)/2);z.heal=1+r+Math.floor(n/2);}if(x.slot==='relic'){z.hp=t*3+n*2;z.atk=Math.floor((t+r+n)/3);z.def=Math.floor((t+n)/3);z.heal=1+Math.floor((r+n)/2);}const a=prefixes.find(a=>a.id===x.affix);if(a)for(const k in z)z[k]+=a[k]*(1+Math.floor(t/3));if(x.tempered)for(const k in z)z[k]=Math.round(z[k]*(1+x.tempered*.22));return z;}
function stats(s,id,equipment=s.equipped[id]){const c=chars[id],h=s.heroes[id],lv=level(h.xp),z={hp:c.hp+(lv-1)*7+h.rank*8,atk:c.atk+(lv-1)*2+h.rank*2,def:c.def+Math.floor((lv-1)/3)+h.rank,heal:c.heal?c.heal+(lv-1)*2+h.rank*2:0};for(const slot of slots){const x=s.gear.find(x=>x.id===equipment[slot]);if(x){const a=gearStats(x);for(const k in z)z[k]+=a[k];}}z.atk+=h.skills.passive;z.def+=h.skills.passive;const set=window.LanternJourney?.bonus(s,equipment);if(set)for(const k in z)z[k]+=set[k];const bonds=s.trials?.bonds?.[id]||0;z.hp+=bonds*6;z.atk+=bonds;z.def+=Math.floor(bonds/2);const sigil=window.LanternExpansion?.bonus(s,id);if(sigil)for(const k in z)z[k]+=sigil[k];const guardian=window.LanternGuardians?.bonus(s,id);if(guardian)for(const k in z)z[k]+=guardian[k]||0;return z;}
function power(z){return z.hp+z.atk*5+z.def*8+z.heal*2;}
function total(s,party=s.party,equipped=s.equipped){return party.reduce((p,id)=>p+power(stats(s,id,equipped[id])),0);}
function compare(s,id,newEquipment){const before=stats(s,id),after=stats(s,id,newEquipment);return{before,after,beforePower:power(before),afterPower:power(after)};}
function recommend(s,party=s.party){const draft=copy(s.equipped),used=new Set();for(const id of party){let chosen=null,chosenPower=-1;const current=draft[id];if(slots.every(slot=>!current[slot]||!used.has(current[slot]))){chosen={...current};chosenPower=power(stats(s,id,chosen));}for(let tier=0;tier<=7;tier++){const load={};for(const slot of slots){const items=s.gear.filter(x=>x.slot===slot&&(slot!=='weapon'||x.role===id)&&!used.has(x.id)&&(!tier||x.tier===tier&&x.rarity>=1));items.sort((a,b)=>power(gearStats(b))-power(gearStats(a)));load[slot]=items[0]?.id||null;}const p=power(stats(s,id,load));if(p>chosenPower){chosen=load;chosenPower=p;}}for(let pass=0;pass<2;pass++)for(const slot of slots){for(const x of s.gear){if(x.slot!==slot||slot==='weapon'&&x.role!==id||used.has(x.id))continue;const load={...chosen,[slot]:x.id},p=power(stats(s,id,load));if(p>chosenPower){chosen=load;chosenPower=p;}}}draft[id]=chosen;for(const key of Object.values(chosen))if(key)used.add(key);}for(const id of chars.map(c=>c.id).filter(id=>!party.includes(id)))for(const slot of slots)if(used.has(draft[id][slot]))draft[id][slot]=null;return draft;}
function equip(s,id,gearId){const x=s.gear.find(x=>x.id===gearId);if(!x||!s.unlocked.includes(id)||x.slot==='weapon'&&x.role!==id)return false;for(const load of s.equipped)for(const slot of slots)if(load[slot]===gearId)load[slot]=null;s.equipped[id][x.slot]=gearId;return true;}
function upgradeCost(x){return{coin:4*(x.rank+1),dust:x.rank+1};}
function salvage(x){return 1+x.rarity*2+Math.floor(x.rank*(x.rank+1)/4);}
function protectedItem(s,x){return x.locked||s.equipped.some(l=>Object.values(l).includes(x.id));}
function dismantle(s,ids){if(!Array.isArray(ids)||!ids.length||new Set(ids).size!==ids.length)return false;const xs=ids.map(id=>s.gear.find(x=>x.id===id));if(xs.some(x=>!x||protectedItem(s,x)))return false;const n=xs.reduce((a,x)=>a+salvage(x),0);window.LanternJourney?.collect(s);if(s.journey)s.journey.dismantled=Math.min(999999,s.journey.dismantled+ids.length);s.gear=s.gear.filter(x=>!ids.includes(x.id));s.resources.dust=Math.min(999999,s.resources.dust+n);return n;}
function upgrade(s,id){const x=s.gear.find(x=>x.id===id);if(!x||x.rank>=5)return false;const c=upgradeCost(x);if(s.resources.coin<c.coin||s.resources.dust<c.dust)return false;s.resources.coin-=c.coin;s.resources.dust-=c.dust;x.rank++;if(s.journey)s.journey.upgrades=Math.min(999999,s.journey.upgrades+1);return true;}
function rankCost(s,id){const n=s.heroes[id].rank+1;return{coin:20*n,crests:n};}
function skillCost(s,id,key){const h=s.heroes[id],n=h.skills[key]+1;return{coin:6*n,books:n,level:key==='passive'?2:key==='secondary'?3:3};}
function grow(s,id,key){if(!s.unlocked.includes(id))return false;const h=s.heroes[id];if(key==='rank'){if(h.rank>=5)return false;const c=rankCost(s,id);if(s.resources.coin<c.coin||s.resources.crests<c.crests)return false;s.resources.coin-=c.coin;s.resources.crests-=c.crests;h.rank++;return true;}if(!['special','secondary','passive'].includes(key)||h.skills[key]>=3||key!=='passive'&&h.skills[key]===0)return false;const c=skillCost(s,id,key);if(level(h.xp)<c.level||s.resources.coin<c.coin||s.resources.books<c.books)return false;s.resources.coin-=c.coin;s.resources.books-=c.books;h.skills[key]++;return true;}
function recruit(s,id){if(s.unlocked.includes(id))return false;s.unlocked.push(id);s.heroes[id].xp=Math.max(0,Math.max(...s.heroes.map(h=>h.xp))-12);for(const slot of slots){if(s.gear.length>=300)break;const x=grant(s,slot,slot==='weapon'?id:null,Math.max(1,Math.ceil(s.next/3)),1);s.equipped[id][slot]=x.id;}if(id>=4)s.heroes[id].skills={special:1,secondary:1,passive:0};if(id<4&&s.party.length<4)s.party.push(id);s.decks[s.deck]=s.party.slice();return true;}
function autoParty(s){const pool=s.unlocked.slice().sort((a,b)=>power(stats(s,b))-power(stats(s,a))||a-b),healer=pool.find(id=>role(id)===2),guard=pool.find(id=>chars[id].trait==='guard'||id===3),party=[];for(const id of [0,healer,guard,...pool])if(id!==undefined&&!party.includes(id)&&party.length<4)party.push(id);return party;}
function roll(s,stage,difficulty){const preferred=stage.preferredSlot||'weapon',slot=Math.random()<.58?preferred:slots[Math.floor(Math.random()*slots.length)],role=s.unlocked[Math.floor(Math.random()*s.unlocked.length)],roll=Math.random();let rarity=roll<.43?0:roll<.78?1:roll<.96?2:3;rarity=Math.max(rarity,difficulty===2?3:difficulty===1?2:0);const x=grant(s,slot,role,Math.max(stage.chapter+1,difficulty===2?7:difficulty===1?4:1),rarity);x.tempered=difficulty;if(rarity)x.affix=prefixes[Math.floor(Math.random()*prefixes.length)].id;if(s.gear.length>300){s.gear.pop();s.resources.dust=Math.min(999999,s.resources.dust+salvage(x));x.converted=true;}return x;}
function dateKey(now=Date.now()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(now));}
function dailyReward(day){return{coin:12+day*2,dust:2+Math.floor(day/2),books:day===2||day===5?2:0,crests:day===6?2:0};}
function claimDaily(s,now=Date.now()){const date=dateKey(now);if(s.daily.date&&date<=s.daily.date)return false;const day=s.daily.day%7,r=dailyReward(day);for(const k in r)s.resources[k]=Math.min(999999,s.resources[k]+r[k]);s.daily={date,day:s.daily.day+1};return r;}
function validate(v){if(v?.onboarding&&!(v.onboarding.version===1&&['prologue','map','battle','fighting','reward','summon','drawn','done'].includes(v.onboarding.step)))return null;if(!v||v.version!==9||!['prologue','town','map','battle','result','forge','party','growth','summon'].includes(v.scene)||!int(v.next,0,21)||!int(v.selectedChapter,0,6)||!int(v.difficulty,0,2)||!v.resources||!['coin','dust','books','crests'].every(k=>int(v.resources[k],0,999999))||!Array.isArray(v.heroes)||!int(v.heroes.length,4,chars.length)||v.heroes.some(h=>!int(h.xp,0,1000000)||!int(h.rank,0,5)||!h.skills||!['special','secondary','passive'].every(k=>int(h.skills[k],0,3)))||!Array.isArray(v.unlocked)||!v.unlocked.includes(0)||new Set(v.unlocked).size!==v.unlocked.length||v.unlocked.some(id=>!int(id,0,v.heroes.length-1))||!Array.isArray(v.party)||!v.party.length||v.party.length>4||new Set(v.party).size!==v.party.length||v.party.some(id=>!v.unlocked.includes(id))||!Array.isArray(v.decks)||v.decks.length!==3||v.decks.some(d=>d!==null&&(!Array.isArray(d)||!d.length||d.length>4||new Set(d).size!==d.length||d.some(id=>!v.unlocked.includes(id))))||!int(v.deck,0,2)||!int(v.serial,0,10000000)||!Array.isArray(v.gear)||v.gear.length>300||!Array.isArray(v.equipped)||v.equipped.length!==v.heroes.length||!Array.isArray(v.clears)||v.clears.length!==21||v.clears.some((x,i)=>!int(x,0,3)||i<v.next&&x===0||i>=v.next&&x!==0)||!v.tonic||!int(v.tonic.count,0,99)||!int(v.tonic.level,0,5)||!v.daily||!(v.daily.date===null||typeof v.daily.date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v.daily.date))||!int(v.daily.day,0,100000))return null;
 const ids=new Set();for(const x of v.gear){if(!x||typeof x.id!=='string'||!/^g\d+$/.test(x.id)||ids.has(x.id)||!int(Number(x.id.slice(1)),1,v.serial)||!slots.includes(x.slot)||!(x.slot==='weapon'?int(x.role,0,chars.length-1):x.role===null)||!int(x.tier,1,7)||!int(x.rarity,0,4)||(x.tempered!==undefined&&!int(x.tempered,0,2))||!int(x.rank,0,5)||typeof x.locked!=='boolean'||!([null,...prefixes.map(x=>x.id)].includes(x.affix)))return null;ids.add(x.id);}
 if((v.next<3&&v.unlocked.length!==1)||(v.next>=3&&!v.unlocked.includes(1))||(v.next<9&&v.unlocked.includes(2))||(v.next>=9&&!v.unlocked.includes(2))||(v.next<15&&v.unlocked.includes(3))||(v.next>=15&&!v.unlocked.includes(3)))return null;
 const used=new Set();for(let id=0;id<v.equipped.length;id++)for(const slot of slots){const key=v.equipped[id]?.[slot];if(key===null)continue;const x=v.gear.find(x=>x.id===key);if(!x||x.slot!==slot||slot==='weapon'&&x.role!==id||used.has(key))return null;used.add(key);}
 if(!v.settings||(v.settings.voices!==undefined&&(!Number.isFinite(v.settings.voices)||v.settings.voices<0||v.settings.voices>1))||(v.settings.reactions!==undefined&&typeof v.settings.reactions!=='boolean')||(v.settings.festival!==undefined&&typeof v.settings.festival!=='boolean')||(v.settings.voice!==undefined&&typeof v.settings.voice!=='boolean')||!['music','effects','ambience'].every(k=>typeof v.settings[k]==='number'&&Number.isFinite(v.settings[k])&&v.settings[k]>=0&&v.settings[k]<=1)||![1,2].includes(v.settings.speed)||typeof v.settings.auto!=='boolean'||typeof v.settings.autoNext!=='boolean'||!['balanced','aggressive','defensive'].includes(v.settings.policy))return null;if(v.story&&(!(typeof v.story.after==='string'&&['town','next','resume','map','tutorialMap','tutorialSummon','festival','festival:0','festival:1','festival:2','depart:0','depart:1','depart:2','depart:3','depart:4','depart:5','depart:6','depart:7','depart:8','depart:9','depart:10','depart:11','depart:12','depart:13','depart:14','depart:15','depart:16','depart:17','depart:18','depart:19','depart:20'].includes(v.story.after))||!Array.isArray(v.story.pages)||!int(v.story.index,0,v.story.pages.length-1)||v.story.pages.length>24||v.story.pages.some(p=>typeof p.who!=='string'||p.who.length>50||typeof p.text!=='string'||p.text.length>300)))return null;
 if(['battle','result'].includes(v.scene)){const r=v.run;if(!r||!int(r.stage,0,20)||r.stage>v.next||!int(r.wave,0,2)||!int(r.difficulty,0,2)||!int(r.round,0,1000)||!int(r.cursor,0,v.party.length)||!int(r.target,0,1)||!int(r.resonance,0,100)||!int(r.tonics,0,2)||!['party','enemy'].includes(r.phase)||!int(r.foeCursor,0,2)||!Array.isArray(r.party)||new Set(r.party.map(p=>p.id)).size!==r.party.length||r.party.length<1||r.party.length>4||(v.scene==='battle'&&r.party.length!==v.party.length)||r.party.some((p,i)=>!int(p.id,0,v.heroes.length-1)||!v.unlocked.includes(p.id)||(v.scene==='battle'&&p.id!==v.party[i])||p.joined!==true||!int(p.hp,0,5000)||!int(p.maxHp,1,5000)||p.hp>p.maxHp||!int(p.charge,0,100)||!int(p.shield,0,1000)||!int(p.slow,0,2))||!Array.isArray(r.enemies)||!r.enemies.length||r.enemies.length>2||r.enemies.some(e=>typeof e.name!=='string'||e.name.length>80||!Array.isArray(e.pattern)||e.pattern.length!==4||e.pattern.some(k=>!['strike','ward','regen','hunt','drain','shatter','charge','heavy','freeze','mend','volley','poison'].includes(k))||!int(e.hp,0,50000)||!int(e.maxHp,1,50000)||e.hp>e.maxHp||!int(e.atk,1,5000)||!int(e.def,0,500)||!int(e.ward,0,3)||!int(e.poise,0,3)||(e.interrupted!==undefined&&typeof e.interrupted!=='boolean')||!int(e.charge,0,1)||!int(e.marks,0,3)||!['stag','warden','moth','knight','wyrm','wolf','oracle','golem','crab','wisp','harpy','serpent'].includes(e.kind)||!['ward','regen','hunt','drain','shatter','charge','freeze','strike'].includes(e.trait))||!int(r.reward?.coin,0,999999)||!int(r.reward?.dust,0,999999)||!int(r.reward?.books,0,999999)||!int(r.reward?.crests,0,999999))return null;if(v.scene==='battle'&&r.party.every(p=>p.hp===0)||v.scene==='result'&&!['won','defeat','retreat'].includes(r.reason))return null;}
 if((v.festival||v.run?.festival!==undefined)&&window.LanternFestival&&!window.LanternFestival.valid(v))return null;if(v.pass&&!window.LanternPass?.valid(v))return null;if(v.rewards&&!window.LanternRewards?.valid(v))return null;if(v.trials&&!window.LanternTrials.valid(v))return null;if(v.expansion&&window.LanternExpansion&&!window.LanternExpansion.valid(v.expansion))return null;if(v.run?.tower&&(!int(v.run.tower,1,30)||v.next<window.LanternExpansion.towerSpec(v.run.tower).required))return null;if(v.journey&&window.LanternJourney&&!window.LanternJourney.valid(v.journey))return null;if(window.LanternTrophies&&!window.LanternTrophies.valid(v))return null;if(v.guardians&&window.LanternGuardians&&!window.LanternGuardians.valid(v.guardians,v))return null;const out=copy(v);window.LanternGuardians?.ensure(out);window.LanternTrophies?.ensure(out);window.LanternJourney?.ensure(out);window.LanternTrials?.ensure(out);window.LanternRewards?.ensure(out);out.seen=Array.isArray(v.seen)?v.seen.filter(x=>typeof x==='string').slice(-80):[];return out;}
window.LanternRPG=Object.freeze({role,slots,slotNames,chars,rarities,prefixes,difficulties,empty,level,gearName,grant,gearStats,stats,power,total,compare,recommend,equip,upgradeCost,upgrade,salvage,protectedItem,dismantle,rankCost,skillCost,grow,recruit,autoParty,roll,dateKey,dailyReward,claimDaily,validate,copy});
})();
