/* Local sampled scores, real foley, and continuous stereo atmospheres. */
(()=>{'use strict';
const paths={coast:'v17-env-ocean',wind:'v17-env-wind',forest:'forest-canopy',fire:'campfire-hearth'};
const tracks={town:'home',map:'map',expedition:'battle',boss:'stageboss',chapterboss:'chapterboss'};
const musicPlayers=new Set(),musicPool=[];let musicPlayer=null,musicEpoch=0,pendingMusic=null,enableEpoch=0,resumePosition={},combatSpeed=1,duckUntil=0;
const musicFiles=Object.fromEntries(Object.entries(tracks).map(([k,v])=>[k,'audio/tidebell-v10-'+v+'.mp3']));
const cues=['v15-sword_slash','v15-sword_alt','v15-sword_heavy','v15-bow_shot','v15-bow_alt','v15-blunt_hit','v15-magic_snap','v15-magic_alt','v15-magic_burst','v14-melee-1','v14-melee-2','v14-melee-3','v14-bow-1','v14-bow-2','v14-magic-1','v14-magic-2','v14-finish-fire','v14-finish-frost','v14-finish-gale','v14-finish-storm','v14-finish-tide','v14-finish-light','v14-menu','v14-loot','v14-coast-gull-procedural','v13-ward','v13-heal','v13-summon','v13-legend','v13-clear','footstep01'];
let ctx,master,musicBus,effectsBus,ambientBus,voiceBus,muted=true,scene='town',environment='coast',dialogue=false,intensity=0,enablePromise=null,epoch=0,voiceEpoch=0,failed=null;
const cache=new Map(),voices=new Set(),loops={music:null,ambient:null,wind:null},volume={master:.8,music:.65,effects:.8,ambience:.55,voices:.75};
// MP3 first across mobile Safari; retry transient errors and fall back on decode errors.
const codecs=['mp3','ogg'],loadQueue=[];let activeLoads=0,recoveryTimer=null,recoveryScene=null,recoveryCount=0,warmed=false;
const loadStats={retries:0,fallbacks:0,failures:0};
function pump(){while(activeLoads<3&&loadQueue.length){const job=loadQueue.shift();activeLoads++;job().finally(()=>{activeLoads--;pump();});}}
function limited(job){return new Promise((resolve,reject)=>{loadQueue.push(()=>job().then(resolve,reject));pump();});}
function deadline(p,ms){let timer;return Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Audio timeout')),ms);})]).finally(()=>clearTimeout(timer));}
function playable(){return ctx&&!muted&&!document.hidden&&ctx.state==='running';}
function ramp(param,to,seconds){if(!ctx)return;const now=ctx.currentTime;if(param.cancelAndHoldAtTime)param.cancelAndHoldAtTime(now);else{param.cancelScheduledValues(now);param.setValueAtTime(param.value,now);}param.linearRampToValueAtTime(to,now+seconds);}
function setup(){if(ctx)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)throw Error('Audio unavailable');ctx=new C();master=ctx.createGain();master.gain.value=0;musicBus=ctx.createGain();effectsBus=ctx.createGain();ambientBus=ctx.createGain();voiceBus=ctx.createGain();const compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-12;compressor.knee.value=14;compressor.ratio.value=3;compressor.attack.value=.004;compressor.release.value=.22;const safety=ctx.createWaveShaper(),curve=new Float32Array(2048);for(let i=0;i<curve.length;i++){const x=i/(curve.length-1)*2-1;curve[i]=Math.tanh(x*1.15)/Math.tanh(1.15)*.92;}safety.curve=curve;safety.oversample='2x';musicBus.connect(master);effectsBus.connect(master);ambientBus.connect(master);voiceBus.connect(master);master.connect(compressor);compressor.connect(safety);safety.connect(ctx.destination);for(let i=0;i<3;i++){const media=new Audio(),gain=ctx.createGain(),node=ctx.createMediaElementSource(media);media.preload='auto';gain.gain.value=0;node.connect(gain);gain.connect(musicBus);musicPool.push({media,gain,node,owner:null,unlocked:false});}updateLevels();}
async function load(name){if(!cache.has(name)){const promise=limited(async()=>{let error;for(const codec of codecs){for(let attempt=0;attempt<2;attempt++){let timer,controller=typeof AbortController==='function'?new AbortController():null;try{const path='audio/'+name+'.'+codec;if(controller)timer=setTimeout(()=>controller.abort(),7000);const response=await deadline(fetch(window.LanternAssets?.[path]||path,controller?{signal:controller.signal}:{}),7500);if(!response.ok)throw Error('Audio asset '+response.status);const bytes=await deadline(response.arrayBuffer(),7500);try{return await deadline(ctx.decodeAudioData(bytes),5000);}catch(e){error=e;loadStats.fallbacks++;break;}}catch(e){error=e;if(attempt===0)loadStats.retries++;}finally{clearTimeout(timer);}}}loadStats.failures++;throw error;});cache.set(name,promise);promise.catch(()=>{if(cache.get(name)===promise)cache.delete(name);});}return cache.get(name);}
function recoverMusic(name,error){if(!playable()||scene!==name)return;if(error?.name==='NotAllowedError'){failed=null;return;}failed=String(error);if(recoveryScene!==name){recoveryScene=name;recoveryCount=0;}if(recoveryCount>=2||recoveryTimer)return;const request=musicEpoch;recoveryTimer=setTimeout(()=>{recoveryTimer=null;if(playable()&&scene===name&&request===musicEpoch){recoveryCount++;loadStats.retries++;switchMusic(name,true);}},600*(recoveryCount+1));}

function releaseMusic(p){if(!p)return;clearTimeout(p.retireTimer);for(const [name,fn]of p.listeners||[])p.media.removeEventListener?.(name,fn);if(p.slot.owner===p){p.media.pause();p.media.removeAttribute('src');p.media.load();p.slot.owner=null;}musicPlayers.delete(p);}
function acquireMusic(){let slot=musicPool.find(x=>!x.owner&&x.unlocked)||musicPool.find(x=>!x.owner);if(!slot){slot=musicPool.find(x=>x.owner.retiring)||musicPool.find(x=>x.owner!==musicPlayer);if(slot)releaseMusic(slot.owner);}return slot;}
function primeMusic(){for(const slot of musicPool){if(slot.unlocked||slot.owner||slot.priming)continue;slot.priming=true;slot.media.src='audio/unlock-silence.wav';try{const attempt=slot.media.play();Promise.resolve(attempt).then(()=>{slot.unlocked=true;if(!slot.owner)slot.media.pause();},()=>{}).finally(()=>slot.priming=false);}catch{slot.priming=false;}}}
function retireMusic(p,seconds=.8){if(!p||p.retiring)return;p.retiring=true;ramp(p.gain.gain,0,seconds);p.retireTimer=setTimeout(()=>releaseMusic(p),seconds*1000+40);}

function stopMusic(seconds=.8){++musicEpoch;pendingMusic=null;musicPlayer=null;for(const p of musicPlayers)if(!p.retiring)retireMusic(p,seconds);}
function stopLoop(kind,seconds=.8){if(kind==='music'){stopMusic(seconds);return;}const current=loops[kind];if(!current)return;loops[kind]=null;ramp(current.gain.gain,0,seconds);try{current.source.stop(ctx.currentTime+seconds+.03);}catch{}current.source.onended=()=>{current.source.disconnect();current.gain.disconnect();};}
async function switchMusic(name,restart=false){
 if(pendingMusic?.name===name)return;
 if(!restart&&musicPlayer?.name===name&&!musicPlayer.retiring&&!musicPlayer.media.paused&&!musicPlayer.media.error){if(pendingMusic){++musicEpoch;pendingMusic=null;}return;}
 const slot=acquireMusic();if(!slot)return;const request=++musicEpoch,{media,gain,node}=slot;pendingMusic={name,request};
 media.preload='auto';media.src=window.LanternAssets?.[musicFiles[name]]||musicFiles[name];
 gain.gain.value=0;
 const p={name,media,node,gain,slot,retiring:false,listeners:[]};slot.owner=p;musicPlayers.add(p);const listen=(name,fn)=>{p.listeners.push([name,fn]);media.addEventListener(name,fn);};
 if(!restart&&resumePosition[name])listen('loadedmetadata',()=>{if(p.retiring||request!==musicEpoch)return;try{media.currentTime=Math.min(resumePosition[name],Math.max(0,(media.duration||Infinity)-.1));}catch{}},{once:true});
 listen('error',()=>{if(!p.retiring&&request===musicEpoch){if(musicPlayer===p)musicPlayer=null;if(pendingMusic?.request===request)pendingMusic=null;++musicEpoch;retireMusic(p,0);recoverMusic(name,Error('Music stream '+name));}});
 try{await deadline(media.play(),12000);if(!playable()||request!==musicEpoch){retireMusic(p,0);return;}
 slot.unlocked=true;p.stableStart=ctx.currentTime;const old=musicPlayer;musicPlayer=p;failed=null;recoveryScene=name;clearTimeout(recoveryTimer);recoveryTimer=null;retireMusic(old,1.6);ramp(gain.gain,.9,1.6);
 const repeat=()=>{if(musicPlayer===p&&!p.retiring&&playable()&&!pendingMusic)switchMusic(name,true);};
 listen('timeupdate',()=>{if(musicPlayer===p&&ctx.currentTime-(p.stableStart??0)>10)recoveryCount=0;if(Number.isFinite(media.duration)&&media.duration-media.currentTime<=1.6)repeat();});listen('ended',repeat);
 }catch(e){retireMusic(p,0);if(request===musicEpoch&&playable()&&e.name!=='AbortError')recoverMusic(name,e);}
 finally{if(pendingMusic?.request===request)pendingMusic=null;}
}
async function switchLoop(kind,name,requestEpoch){if(loops[kind]?.name===name){ramp(loops[kind].gain.gain,kind==='wind'?.07:scene==='title'?.48:.26,.8);return;}const buffer=await load(paths[name]);if(!playable()||requestEpoch!==epoch)return;stopLoop(kind,1.6);const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=buffer;source.loop=true;gain.gain.value=0;source.connect(gain);gain.connect(kind==='music'?musicBus:ambientBus);source.start();loops[kind]={source,gain,name};ramp(gain.gain,kind==='music'?.78:kind==='wind'?.07:scene==='title'?.48:.26,1.25);}
function updateLevels(){if(!ctx)return;ramp(musicBus.gain,volume.music*(dialogue?.65:1)*(ctx.currentTime<duckUntil?.55:1),.35);ramp(effectsBus.gain,volume.effects,.12);ramp(voiceBus.gain,volume.voices,.12);ramp(ambientBus.gain,volume.ambience*(dialogue?.65:1)*(['expedition','boss','chapterboss'].includes(scene)?.55:1),.35);}
function refresh(){if(!playable())return;const request=++epoch,music=tracks[scene]?scene:'town';if(scene==='title')stopMusic(.3);else switchMusic(music).catch(e=>recoverMusic(music,e));switchLoop('ambient',environment,request).catch(()=>{});if(scene==='title')switchLoop('wind','wind',request).catch(()=>{});else stopLoop('wind',.8);updateLevels();}
function cancelVoices(){for(const n of voices)try{n.stop();}catch{}voices.clear();basicVoices.clear();}
async function enable(){
 // Every gesture calls resume directly, even if a previous autoplay attempt is pending.
 try{setup();}catch(e){failed=String(e);return false;}
 primeMusic();let resumed;try{resumed=ctx.resume();}catch{return false;}
 if(!muted&&ctx.state==='running'&&!enablePromise){refresh();return true;}
 if(enablePromise&&!muted)return enablePromise;
 const request=++enableEpoch;muted=false;
 const job=(async()=>{try{await resumed;if(request!==enableEpoch||muted)return false;failed=null;ramp(master.gain,volume.master,.5);refresh();if(!warmed){warmed=true;for(const name of ['v17-ui-select','v17-slash-clean','v17-slash-low','v17-heavy-hammer','v17-bow-release','v17-skill-fire'])load(name).catch(()=>{});}return true;}catch(e){if(request===enableEpoch){failed=e.name==='NotAllowedError'?null:String(e);muted=true;}return false;}finally{if(request===enableEpoch)enablePromise=null;}})();enablePromise=job;return job;
}
async function mute(){muted=true;++enableEpoch;enablePromise=null;++epoch;++voiceEpoch;if(!ctx)return;if(musicPlayer)resumePosition[musicPlayer.name]=musicPlayer.media.currentTime;ramp(master.gain,0,.25);stopLoop('music',.25);stopLoop('ambient',.25);stopLoop('wind',.25);cancelVoices();}
let lastBasic=-10,quietUntil=0,gullAt=0,lastCue={},playedCues=[];
const basicVoices=new Set();
function variant(group,n){const previous=lastCue[group]??-1,offset=1+Math.floor(Math.random()*(n-1));const pick=previous<0?Math.floor(Math.random()*n):(previous+offset)%n;lastCue[group]=pick;return ({melee:['v15-sword_slash','v15-sword_alt'],bow:['v15-bow_shot','v15-bow_alt'],magic:['v15-magic_snap','v15-magic_alt']})[group][pick];}
const groups={slash:['v17-slash-clean','v17-slash-low','v17-slash-cross'],arrow:['v17-bow-release','v17-bow-bolt'],spark:['v15-magic_snap','v15-magic_alt'],hit:['v17-heavy-hammer','v17-heavy-earth','v17-heavy-shield'],break:['v17-break-armor','v17-break-ward'],counter:['v17-counter-parry','v17-counter-riposte'],gull:['v17-env-gull-near','v17-env-gull-far']};
function pickCue(group){const a=groups[group],last=lastCue[group]??-1;let i=Math.floor(Math.random()*a.length);if(i===last)i=(i+1)%a.length;lastCue[group]=i;return a[i];}
function sample(file,gain=.7,delay=0,options={}){if(!playable())return;const request=voiceEpoch,basic=!!options.basic;load(file).then(buffer=>{if(!playable()||request!==voiceEpoch||voices.size>=12||basic&&(basicVoices.size>=2||ctx.currentTime<quietUntil))return;const node=ctx.createBufferSource(),amp=ctx.createGain();node.buffer=buffer;amp.gain.value=gain;node.connect(amp);const pan=ctx.createStereoPanner?.(),bus=options.ambient?ambientBus:effectsBus;if(pan){pan.pan.value=options.pan||0;amp.connect(pan);pan.connect(bus);}else amp.connect(bus);const v={node,amp};if(basic)basicVoices.add(v);voices.add(node);playedCues.push(file);playedCues=playedCues.slice(-40);node.onended=()=>{basicVoices.delete(v);voices.delete(node);node.disconnect();amp.disconnect();pan?.disconnect();};node.start(ctx.currentTime+delay/combatSpeed);}).catch(()=>{});}
function sfx(name,options={}){
 if(!playable())return;const special=name.startsWith('element-')||name==='ultimate',basic=['slash','combo','arrow','spark','hit','dot','enemy-claw'].includes(name);
 if(basic&&(ctx.currentTime-lastBasic<.09||ctx.currentTime<quietUntil))return;if(basic)lastBasic=ctx.currentTime;
 if(special){quietUntil=ctx.currentTime+.26;for(const v of basicVoices){ramp(v.amp.gain,0,.035);try{v.node.stop(ctx.currentTime+.04);}catch{}}}
 if(special||name.startsWith('summon')||name==='victory'){duckUntil=ctx.currentTime+1.35/combatSpeed;updateLevels();setTimeout(updateLevels,1450/combatSpeed);}
 const map={select:['v17-ui-select',.30],confirm:['v17-ui-confirm',.4],page:['v17-ui-page',.23],cancel:['v17-ui-cancel',.35],travel:['v17-ui-confirm',.22],combo:['v17-slash-critical',.82],dot:['v15-magic_alt',.13],heal:['v17-heal-bloom',.6],barrier:['v17-barrier-dome',.5],guard:['v17-heavy-shield',.35],awaken:['v17-loot-legend',.6],reward:['v17-loot-coins',.6],'reward-bloom':['v17-loot-chest',.36],complete:['v17-victory-party',.65],victory:['v17-victory-party',.67],'victory-boss':['v17-victory-boss',.68],'level-up':['v17-loot-gem',.65],trophy:['v17-loot-legend',.62],defeat:['v17-enemy-dissolve',.3],summon:['v13-summon',.6],'summon-legend':['v17-loot-legend',.7],'boss-entry':['v17-enemy-growl',.55],'enemy-claw':['v17-enemy-claw',.67],'enemy-crush':['v17-enemy-crush',.72],'enemy-cast':['v17-skill-storm',.42],'enemy-death':['v17-enemy-dissolve',.4],footstep:['footstep01',.06], 'loot-rare':['v17-loot-gem',.65]};
 if(special){const element=name==='ultimate'?'light':name.slice(8);if(!['fire','frost','gale','storm','tide','light'].includes(element))return;sample('v17-skill-'+element,.7,0,options);if(element==='fire'){sample('v17-slash-cross',.50,.40,options);sample('v17-slash-low',.46,.70,options);sample('v17-slash-critical',.62,1.0,options);}else if(element==='gale'){sample('v17-bow-volley',.62,.30,options);sample('v17-break-ward',.4,.73,options);}else sample('v17-heavy-earth',.32,.68,options);return;}
 const a=groups[name]?[pickCue(name),name==='gull'?.17:name==='spark'?.58:.72]:map[name];if(!a)return;sample(a[0],a[1],options.delay||0,{...options,basic,ambient:name==='gull'});
}

let reactionNode=null,reactionRequest=0;
function stopReaction(){reactionRequest++;if(reactionNode){try{reactionNode.stop();}catch{}reactionNode=null;}}
const voiceLast={};let nextVoiceAt=0;
function reaction(){return false;}
function voice(character,kind){if(dialogue||['story','surprise','disagree'].includes(kind))return false;if(!character||!playable()||ctx.currentTime<nextVoiceAt&&!['ultimate','victory','defeat'].includes(kind))return false;const pack=window.LanternVoicePack?.[character],pool=pack?.[kind]||[];if(!pool.length)return false;const key=character+':'+kind,last=voiceLast[key]??-1;let index=Math.floor(Math.random()*pool.length);if(index===last)index=(index+1)%pool.length;voiceLast[key]=index;const item=pool[index],file=typeof item==='string'?item:item.file;stopReaction();const token=reactionRequest,request=voiceEpoch;nextVoiceAt=ctx.currentTime+(kind==='story'?1.5:2.2);load(file).then(buffer=>{if(token!==reactionRequest||request!==voiceEpoch||!playable())return;const node=ctx.createBufferSource(),gain=ctx.createGain();node.buffer=buffer;gain.gain.value=.82;node.connect(gain);gain.connect(voiceBus);reactionNode=node;voices.add(node);playedCues.push(file);playedCues=playedCues.slice(-40);node.onended=()=>{voices.delete(node);node.disconnect();gain.disconnect();if(reactionNode===node)reactionNode=null;};node.start();}).catch(()=>{});return true;}

function ambientTick(){if(!playable()||environment!=='coast'||dialogue||ctx.currentTime<duckUntil||!['title','town','map'].includes(scene)||ctx.currentTime<gullAt)return;gullAt=ctx.currentTime+(scene==='title'?8:25)+Math.random()*12;sfx('gull',{pan:.45});}
function setScene(value){if(scene===value)return;scene=value;clearTimeout(recoveryTimer);recoveryTimer=null;recoveryCount=0;recoveryScene=value;++voiceEpoch;cancelVoices();stopReaction();refresh();}function setEnvironment(value){if(!['coast','forest','fire'].includes(value)||environment===value)return;environment=value;refresh();}
function setVolume(value,channel='master'){if(!Number.isFinite(value)||!Object.hasOwn(volume,channel))return;const next=Math.max(0,Math.min(1,value));if(volume[channel]===next)return;volume[channel]=next;if(channel==='master'&&ctx)ramp(master.gain,muted?0:volume.master,.25);updateLevels();}
function suspend(){if(!ctx)return;++epoch;++voiceEpoch;if(musicPlayer)resumePosition[musicPlayer.name]=musicPlayer.media.currentTime;stopMusic(0);stopLoop('ambient',0);stopLoop('wind',0);cancelVoices();ctx.suspend().catch(()=>{});}
function resume(){if(!ctx||muted||document.hidden)return;ctx.resume().then(()=>{if(!muted&&!document.hidden)refresh();}).catch(()=>{});}
window.addEventListener('online',()=>{recoveryCount=0;resume();});
document.addEventListener('visibilitychange',()=>document.hidden?suspend():resume());
window.addEventListener('pagehide',suspend);window.addEventListener('pageshow',resume);
window.HearthAudio=Object.freeze({enable,mute,retry:()=>{stopMusic(.2);stopLoop('ambient',.2);cache.clear();return enable();},setSpeed:value=>combatSpeed=value===2?2:1,toggle:()=>muted?enable():mute(),setScene,setEnvironment,setColor:()=>{},setIntensity:value=>{if(!Number.isFinite(value))return;const next=Math.max(0,Math.min(1,value));if(Math.abs(next-intensity)>.02){intensity=next;updateLevels();}},setDialogue:value=>{if(dialogue===!!value)return;dialogue=!!value;updateLevels();},setVolume,sfx,voice,reaction,stopReaction,ambientTick,get isMuted(){return muted;},getDiagnostics:()=>({muted,scene,environment,volume:{...volume},pending:pendingMusic?.name||null,loaded:cache.size,loadStats:{...loadStats},playedCues:[...playedCues],voices:voices.size,loops:[...Object.values(loops).filter(Boolean).map(x=>x.name),...(musicPlayer?[musicPlayer.name]:[])],music:musicPlayer?{name:musicPlayer.name,file:musicFiles[musicPlayer.name],position:musicPlayer.media.currentTime,duration:musicPlayer.media.duration||null,playing:!musicPlayer.media.paused,streams:musicPlayers.size}:null,failed,state:ctx?.state})});
})();
