/* Original production art, staged as a layered pixel battlefield. */
(()=>{'use strict';
const files={dawn:'assets/title-tidebell-dawn-v10.png',allies14:'assets/allies-v14.png',enemies14:'assets/enemies-v14.png',allies:'assets/allies-v13.png',newEnemies:'assets/enemies-v12.png',arena:'assets/forest-shrine-arena.png',hero:'assets/traveller-hero.png',mina:'assets/mina-ranger.png',rio:'assets/rio-scholar.png',guardian:'assets/stag-guardian.png',warden:'assets/stone-warden.png',town:'assets/town-abandoned.png',restored:'assets/town-restored.png',motion:'assets/party-motion-v04.png',forge:'assets/stone-forge-v05.png',tide:'assets/moon-tide-v05.png',people:'assets/people-v06.png',enemyAtlas:'assets/enemy-atlas-v09.png'},images={},reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const loads={};for(const key of Object.keys(files))images[key]=new Image();
function load(key){if(loads[key])return loads[key];const im=images[key],src=files[key];loads[key]=new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=()=>reject(new Error('素材を読み込めませんでした'));im.src=window.LanternAssets?.[src]||src;});return loads[key];}
const ready=Promise.all([load('dawn'),load('town'),load('motion'),load('people'),load('enemyAtlas'),load('newEnemies'),load('allies'),load('allies14'),load('enemies14')]).then(()=>{prepareFrames();preparePeople();prepareEnemies();prepareAllies();});ready.catch(()=>{});
function needed(s){return s.run&&['battle','result'].includes(s.scene)?[s.run.route==='tide'?'tide':s.run.route==='stone'?'forge':'arena','warden','guardian','enemyAtlas']:['dawn'];}
function prepare(s){return Promise.all(needed(s).map(load));}
function available(s){return needed(s).every(k=>images[k].complete&&images[k].naturalWidth>0);}
let animation=null,points=null,particles=[];
const ease=x=>1-Math.pow(1-Math.min(1,Math.max(0,x)),3),triangle=x=>Math.max(0,1-Math.abs(x-.5)*2);
function action(a){animation={...a};const now=a.start;const n=(['slash','counter'].includes(a.kind)||a.kind==='skill'&&a.unit===0)?24:a.kind==='break'?32:18;for(let i=0;i<n;i++)particles.push({at:now+.15,angle:i*2.399,speed:35+(i%7)*15,life:.35+(i%3)*.11,color:a.marked?'#ffce67':a.kind==='light'?'#ffd07a':a.kind==='shoot'?'#b7ffd7':'#fff0c2'});}
function layout(w,h,battle,floor,ceiling=100){const wide=w>h*1.25,fieldWidth=wide?w*.54:w,bottom=Math.max(ceiling+30,(floor||h-260)-6),space=Math.max(30,bottom-ceiling),scale=Math.min(.54,fieldWidth/600,space/200);return{hero:{x:fieldWidth*.46,y:bottom-2*scale},mina:{x:fieldWidth*.12,y:bottom-10*scale},rio:{x:fieldWidth*.29,y:bottom-6*scale},enemy:{x:fieldWidth*.81,y:bottom-6*scale},scale,wide,bottom,ceiling,fieldWidth,space};}
let frameBounds=[],portraits=[],peopleFrames=[],peoplePortraits=[];
// Component masks isolate each drawn pose even where weapons cross the nominal grid.
const poseMetadata=[{"row":0,"col":0,"bounds":[31,59,187,300],"seed":[135,59]},{"row":0,"col":1,"bounds":[229,59,410,300],"seed":[353,59]},{"row":0,"col":2,"bounds":[456,62,642,300],"seed":[583,62]},{"row":0,"col":3,"bounds":[680,66,857,300],"seed":[804,66]},{"row":0,"col":4,"bounds":[887,34,1080,300],"seed":[1047,34]},{"row":0,"col":5,"bounds":[1095,80,1381,300],"seed":[1254,80]},{"row":0,"col":6,"bounds":[1349,44,1527,300],"seed":[1468,44]},{"row":0,"col":7,"bounds":[1538,86,1748,300],"seed":[1680,86]},{"row":1,"col":0,"bounds":[22,345,207,587],"seed":[127,345]},{"row":1,"col":1,"bounds":[224,345,424,587],"seed":[347,345]},{"row":1,"col":2,"bounds":[435,351,635,587],"seed":[570,351]},{"row":1,"col":3,"bounds":[655,348,857,587],"seed":[783,348]},{"row":1,"col":4,"bounds":[867,332,1087,587],"seed":[1019,332]},{"row":1,"col":5,"bounds":[1092,347,1317,587],"seed":[1283,347]},{"row":1,"col":6,"bounds":[1328,379,1553,587],"seed":[1443,379]},{"row":1,"col":7,"bounds":[1570,360,1753,587],"seed":[1708,360]},{"row":2,"col":0,"bounds":[16,616,213,856],"seed":[124,616]},{"row":2,"col":1,"bounds":[209,616,429,857],"seed":[343,616]},{"row":2,"col":2,"bounds":[440,619,650,856],"seed":[571,619]},{"row":2,"col":3,"bounds":[668,622,871,856],"seed":[793,622]},{"row":2,"col":4,"bounds":[888,588,1093,856],"seed":[986,588]},{"row":2,"col":5,"bounds":[1099,631,1380,856],"seed":[1235,631]},{"row":2,"col":6,"bounds":[1340,618,1527,857],"seed":[1492,618]},{"row":2,"col":7,"bounds":[1527,631,1757,856],"seed":[1715,631]}];
function prepareFrames(){const im=images.motion,c=document.createElement('canvas');c.width=im.width;c.height=im.height;const context=c.getContext('2d',{willReadFrequently:true});context.drawImage(im,0,0);const source=context.getImageData(0,0,c.width,c.height).data,labels=new Uint8Array(c.width*c.height),queue=new Uint32Array(labels.length);frameBounds=Array.from({length:3},()=>[]);
for(const [index,pose]of poseMetadata.entries()){const id=index+1,seed=pose.seed[1]*c.width+pose.seed[0];let head=0,tail=1;queue[0]=seed;labels[seed]=id;while(head<tail){const v=queue[head++],xx=v%c.width,yy=Math.floor(v/c.width);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const x=xx+dx,y=yy+dy;if(x<0||x>=c.width||y<0||y>=c.height)continue;const n=y*c.width+x;if(!labels[n]&&source[n*4+3]>40){labels[n]=id;queue[tail++]=n;}}}
const [left,top,right,bottom]=pose.bounds,atlas=document.createElement('canvas');atlas.width=right-left;atlas.height=bottom-top;const ac=atlas.getContext('2d'),pixels=ac.createImageData(atlas.width,atlas.height);for(let y=top;y<bottom;y++)for(let x=left;x<right;x++){const n=y*c.width+x;if(labels[n]!==id)continue;const a=n*4,b=((y-top)*atlas.width+x-left)*4;for(let k=0;k<4;k++)pixels.data[b+k]=source[a+k];}ac.putImageData(pixels,0,0);frameBounds[pose.row][pose.col]={canvas:atlas,x:left,y:top,w:atlas.width,h:atlas.height};}portraits=frameBounds.map(row=>row[0].canvas.toDataURL());}
function preparePeople(){const im=images.people,cw=im.width/4,ch=im.height/3,source=document.createElement('canvas');source.width=im.width;source.height=im.height;const sc=source.getContext('2d',{willReadFrequently:true});sc.drawImage(im,0,0);const pixels=sc.getImageData(0,0,im.width,im.height).data;for(let n=0;n<12;n++){const ox=Math.floor(n%4*cw),oy=Math.floor(Math.floor(n/4)*ch);let left=ox+cw,top=oy+ch,right=ox,bottom=oy;for(let y=oy;y<Math.min(im.height,Math.floor(oy+ch));y++)for(let x=ox;x<Math.floor(ox+cw);x++)if(pixels[(y*im.width+x)*4+3]>170){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}const tile=document.createElement('canvas');tile.width=Math.max(1,right-left+1);tile.height=Math.max(1,bottom-top+1);tile.getContext('2d').drawImage(im,left,top,tile.width,tile.height,0,0,tile.width,tile.height);peopleFrames[n]={canvas:tile,w:tile.width,h:tile.height};}peoplePortraits=peopleFrames.slice(0,4).map(b=>b.canvas.toDataURL());}
let allyFrames=[];
function prepareAllies(){for(const [im,rows,offset]of [[images.allies,3,0],[images.allies14,2,12]]){const cw=im.width/4,ch=im.height/rows;for(let i=0;i<rows*4;i++){const c=document.createElement('canvas');c.width=Math.floor(cw);c.height=Math.floor(ch);c.getContext('2d').drawImage(im,(i%4)*cw,Math.floor(i/4)*ch,cw,ch,0,0,c.width,c.height);allyFrames[i+offset]={canvas:c,w:c.width,h:c.height,portrait:c.toDataURL()};}}}
function allySprite(c,id,p,size,f,t,alpha){const b=allyFrames[id-4];if(!b)return;const factor=size/b.h,bob=reduced?0:Math.sin(t*3+id)*1.3;c.save();c.globalAlpha=alpha;c.translate(Math.round(p.x),Math.round(p.y+bob));if(!reduced){c.rotate(f===5?-.075:f===7?-.1:Math.sin(t*2+id)*.008);c.scale(f===4?.96:f===5?1.035:1,f===4?.97:1);}c.drawImage(b.canvas,-b.w*factor/2,-size,b.w*factor,size);c.restore();}
function personSprite(c,index,p,size){const b=peopleFrames[index];if(!b)return;const factor=size/b.h;c.drawImage(b.canvas,Math.round(p.x-b.w*factor/2),Math.round(p.y-size),Math.round(b.w*factor),Math.round(size));}
function motionSprite(c,key,p,size,frame,options={}){const row={hero:0,mina:1,rio:2}[key],b=options.noah?peopleFrames[4+frame]:frameBounds[row]?.[frame];if(!b||!b.w)return sprite(c,images[key],p,size,options);const im=b.canvas,scale=size/Math.max(...(options.noah?peopleFrames.slice(4):frameBounds[row]).map(b=>b.h));c.save();c.globalAlpha=options.alpha??1;c.translate(Math.round(p.x),Math.round(p.y));c.drawImage(im,0,0,b.w,b.h,Math.round(-b.w*scale/2),Math.round(-b.h*scale),Math.round(b.w*scale),Math.round(b.h*scale));c.restore();}
function sprite(c,im,p,size,options={}){if(!im?.complete||!im.naturalWidth)return;c.save();c.translate(Math.round(p.x),Math.round(p.y));c.scale(options.flip?-1:1,1);c.rotate(options.angle||0);c.globalAlpha=options.alpha??1;const width=size*im.width/im.height;c.drawImage(im,Math.round(-width/2),Math.round(-size),Math.round(width),Math.round(size));if(options.flash){c.globalCompositeOperation='source-atop';/* confined through a tinted sprite layer, avoids coloring the background */}c.restore();}
function glow(c,x,y,r,color){const g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'#ffe6a000');c.fillStyle=g;c.fillRect(x-r,y-r,r*2,r*2)}
function ring(c,p,r,color,width=2){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.ellipse(p.x,p.y,r,r*.3,0,0,Math.PI*2);c.stroke();}
let enemyFrames=[];
function prepareEnemies(){const im=images.enemyAtlas,cols=[0,386,768,1132,1536],rows=[0,328,645,1024];for(let r=0;r<3;r++){enemyFrames[r]=[];for(let f=0;f<4;f++){const c=document.createElement('canvas');c.width=cols[f+1]-cols[f];c.height=rows[r+1]-rows[r];const cc=c.getContext('2d',{willReadFrequently:true});cc.drawImage(im,cols[f],rows[r],c.width,c.height,0,0,c.width,c.height);const d=cc.getImageData(0,0,c.width,c.height);for(let i=3;i<d.data.length;i+=4)if(d.data[i]<170)d.data[i]=0;cc.putImageData(d,0,0);enemyFrames[r][f]={canvas:c,w:c.width,h:c.height};}}}
function monster(c,enemy,p,size,frame,alpha=1){const row14={crab:0,wisp:1,harpy:2,serpent:3}[enemy.kind];if(row14!==undefined){const im=images.enemies14,cw=im.width/4,ch=im.height/4,w=size*cw/ch;c.save();c.globalAlpha=alpha;c.drawImage(im,(frame%4)*cw,row14*ch,cw,ch,p.x-w/2,p.y-size,w,size);c.restore();return;}const extra={wolf:0,oracle:1,golem:2}[enemy.kind];if(extra!==undefined){const im=images.newEnemies,cw=im.width/4,ch=im.height/3,w=size*cw/ch;c.save();c.globalAlpha=alpha;c.drawImage(im,(frame%4)*cw,extra*ch,cw,ch,p.x-w/2,p.y-size,w,size);c.restore();return;}const row={moth:0,knight:1,wyrm:2}[enemy.kind];if(row===undefined){sprite(c,enemy.kind==='warden'?images.warden:images.guardian,p,size,{alpha});return;}const b=enemyFrames[row]?.[frame%4];if(!b)return;const z=size/b.h;c.save();c.globalAlpha=alpha;c.drawImage(b.canvas,Math.round(p.x-b.w*z/2),Math.round(p.y-size),Math.round(b.w*z),Math.round(size));c.restore();}
function draw(c,{width:w,height:h,time:t,state:s,floor,ceiling}){
 const battle=!!s.run&&['battle','result'].includes(s.scene),l=layout(w,h,battle,floor,ceiling),r=s.run;
 const ids=battle?r.party.map(p=>p.id):s.party||[0],party=battle?r.party:ids.map(id=>({id,hp:1,joined:true}));
 if(battle&&ids.length===4)l.scale=Math.min(l.scale,l.space/254);
 const a=animation,rawAge=a?t-a.start:99,beats=a?.kind==='skill'&&a.actor===0?[.4,.7,1]:a?.kind==='skill'||a?.kind==='burst'?[.7]:[a?.enemyAttack?.46:.25];let age=rawAge;if(a&&!reduced)for(const at of beats)if(rawAge>=at)age-=Math.min(.045,rawAge-at);const active=age>=0&&age<(['skill','burst'].includes(a?.kind)?1.8:.92),response=.46;
 const target=active?(a.targetEnemy??r?.target??0):r?.target??0;
 l.enemies=(r?.enemies||[r?.enemy]).filter(Boolean).map((e,i)=>({x:l.fieldWidth*(r.enemies.length===1?.78:i===0?.67:.85),y:l.bottom-(i===0&&r.enemies.length>1?28*l.scale:0),size:(e.boss?190:154)*l.scale}));l.enemy=l.enemies[target]||l.enemies[0]||l.enemy;
 const positions=ids.length===1?[.27]:ids.length===2?[.35,.13]:ids.length===3?[.36,.11,.24]:[.36,.14,.30,.14];
 const actorKeys=['hero','mina','rio','noah'];for(let i=0;i<4;i++){const p=l[actorKeys[i]]||{};p.x=battle?l.fieldWidth*(positions[i]??.2):l.fieldWidth*[[.5],[.32,.66],[.23,.5,.77],[.13,.38,.63,.86]][ids.length-1][i];p.y=l.bottom-(battle&&ids.length===4&&i>=2?95*l.scale:0);p.size=154*l.scale;l[actorKeys[i]]=p;}
 c.save();c.fillStyle='#071922';c.fillRect(0,0,w,h);const bg=battle?r.route==='tide'?images.tide:r.route==='stone'?images.forge:images.arena:images.dawn;
 if(bg?.complete&&bg.naturalWidth){const z=battle?Math.max(w/bg.width,h/bg.height):Math.max(w/bg.width,(l.bottom+40)/(bg.height*.65)),bw=bg.width*z,bh=bg.height*z;c.drawImage(bg,(w-bw)*.5,battle?(h-bh)*.54:l.bottom+40-bh,bw,bh);}
 if(battle&&r.visual?.tint){c.fillStyle=r.visual.tint;c.fillRect(0,0,w,h);}
 const shade=c.createLinearGradient(0,0,0,h);shade.addColorStop(0,'#061a3550');shade.addColorStop(.45,'#08202210');shade.addColorStop(1,'#071725ee');c.fillStyle=shade;c.fillRect(0,0,w,h);
 const vignette=c.createRadialGradient(w*.5,l.ceiling+l.space*.5,Math.min(w,h)*.15,w*.5,h*.5,Math.max(w,h)*.66);vignette.addColorStop(0,'#04112300');vignette.addColorStop(1,'#020b1ac0');c.fillStyle=vignette;c.fillRect(0,0,w,h);
 if(!reduced)for(let i=0;i<20;i++){const x=(i*83+t*(i%3+1)*2)%w,y=l.ceiling+(i*49)%Math.max(30,l.space)+Math.sin(t+i)*5;c.globalAlpha=.25;c.fillStyle=i%2?'#ffdfa6':'#a2c4ff';c.fillRect(x,y,2,2);}c.globalAlpha=1;
 l.npcs=[];
 c.save();if(battle){c.beginPath();c.rect(0,l.ceiling,l.fieldWidth,l.space+12);c.clip();if(active&&!reduced){const impacts=['skill','burst'].includes(a.kind)?[.4,.7,1]:[a.enemyAttack?.46:.25],shake=impacts.reduce((n,at)=>n+Math.max(0,1-(age-at)/.12)*(age>=at?1:0),0);c.translate(Math.sin(age*100)*shake*(a.heavy||a.kind==='skill'?4:2),Math.cos(age*83)*shake*2);}}
 for(let i=0;i<ids.length;i++){const id=ids[i],key=['hero','mina','rio'][Math.min(id,2)],p={...l[actorKeys[i]]},acting=active&&a.unit===i,ko=party[i].hp===0;let f=reduced?0:Math.floor(t*2+i)%2;if(r?.reason==='won'&&!ko){f=reduced?0:Math.floor(t*1.5)%3===0?6:0;p.y-=reduced?0:Math.max(0,Math.sin(t*4+i))*(4*l.scale);}
 if(acting){f=age<.12?4:age<.38?5:age<.52?6:0;if(a.kind==='skill')f=age<.3?4:age<1.18?Math.floor((age-.3)/.15)%2?6:5:0;if(a.kind==='heal'||a.kind==='guard')f=6;if(!reduced&&window.LanternRPG.role(id)===0&&!['heal','guard'].includes(a.kind)){const dash=Math.sin(Math.min(1,age/(a.kind==='skill'?1.3:.44))*Math.PI);p.x+=dash*(l.enemy.x-p.x)*.55;p.y-=dash*13;}}
 if(active&&a.enemyAttack&&a.targets?.includes(i)&&age>.46&&age<.7){f=7;if(!reduced)p.x-=Math.sin((age-.46)/.24*Math.PI)*6;}
 c.fillStyle='#03181790';c.beginPath();c.ellipse(p.x,p.y+2,27*l.scale,7*l.scale,0,0,Math.PI*2);c.fill();if(battle&&r.cursor===i&&!ko)ring(c,p,25*l.scale,'#f4d27f');if(id>=4)allySprite(c,id,p,154*l.scale,f,t,ko?.35:1);else motionSprite(c,key,p,154*l.scale,f,{noah:id===3,alpha:ko?.35:1});l[actorKeys[i]].frame=f;
 }
 if(battle){r.enemies.forEach((e,i)=>{const p={...l.enemies[i]},killed=active&&a.killed&&a.targetEnemy===i;if(e.hp<=0&&!killed)return;let f=Math.floor(t*2)%2;if(active&&a.enemyAttack&&a.attacker===i){f=age<.46?2:3;if(!reduced&&['strike','heavy','hunt','shatter'].includes(a.enemyType)){const victim=l[['hero','mina','rio','noah'][a.targets?.[0]||0]],dash=Math.sin(Math.min(1,age/.72)*Math.PI);p.x-=dash*(p.x-victim.x)*(a.heavy?.45:.32);p.y-=dash*(a.heavy?12:5);}}if(!reduced)p.y-=Math.sin(t*2+i)*l.scale;if(e.boss)glow(c,p.x,p.y-p.size*.5,p.size*.65,'#99e5f522');monster(c,e,p,p.size,f,killed?Math.max(0,1-(age-.75)*2):1);if(e.marks){for(let n=0;n<e.marks;n++){c.fillStyle='#ffe6a0';c.fillRect(p.x-10+n*9,p.y-p.size-5,4,4);}}});}
 if(active){const p=l[actorKeys[a.unit]||'hero'],e=l.enemy,impact=triangle((age-.12)/.23);if(['shoot','light'].includes(a.kind)&&age<.28){const f=ease(age/.22),x=p.x+(e.x-p.x)*f,y=p.y-50*l.scale+(e.y-p.size*.55-p.y+50*l.scale)*f;glow(c,x,y,12,'#b7f5eeaa');c.strokeStyle='#fff6cc';c.lineWidth=3;c.beginPath();c.moveTo(x-20,y+3);c.lineTo(x+5,y);c.stroke();}if(impact>0)glow(c,e.x,e.y-70*l.scale,95*l.scale,`rgba(255,220,150,${impact*.8})`);}
 if(battle)window.LanternEffects?.draw(c,l,a?a.start+age:t,s,a);
 c.restore();if(battle&&r.visual?.weather==='rain'&&!reduced){c.strokeStyle='#b1cee244';c.lineWidth=1;for(let i=0;i<22;i++){const x=(i*69+t*60)%w,y=l.ceiling+(i*41+t*170)%Math.max(50,l.space);c.beginPath();c.moveTo(x,y);c.lineTo(x-6,y+15);c.stroke();}}
 c.restore();points=l;return l;
}
window.HearthStage=Object.freeze({ready,prepare,available,personPortrait:i=>peoplePortraits[i]||'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',portrait:i=>(i>=4?allyFrames[i-4]?.portrait:i===3?peoplePortraits[3]:portraits[i])||'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',draw,action,clear:()=>{animation=null;particles=[]},getPoints:()=>points,getFrames:()=>frameBounds.map(row=>row.map(({w,h,x,y})=>({w,h,x,y}))),images});
})();
