/* Original encounter rules and visible-control auto tactics. */
(()=>{'use strict';
const difficulties=[{name:'標準',hp:1.05,damage:.85},{name:'HARD',hp:1.50,damage:1.35},{name:'EXPERT',hp:1.95,damage:1.80}];
const patterns={forest:[['strike','charge','heavy','strike'],['brace','charge','heavy','strike'],['charge','heavy','strike','heavy']],stone:[['brace','strike','brace','heavy'],['brace','charge','heavy','strike'],['brace','heavy','hunt','charge']],trial:[['hunt','charge','heavy','brace'],['brace','heavy','hunt','drain'],['charge','heavy','drain','hunt']],tide:[['drain','charge','heavy','hunt'],['brace','drain','hunt','heavy'],['drain','heavy','hunt','charge']]};
function stats(r,route){if(Number.isInteger(r.mission)){const q=window.LanternCampaign.get(r.mission),factor=[1,1.45,1.95][r.difficulty],damageFactor=[1,1.25,1.55][r.difficulty];return{hp:Math.ceil(q.hp*factor),damage:Math.ceil(q.damage*damageFactor),heavy:Math.ceil(q.heavy*damageFactor)};}return r.ruleset===2?{hp:Math.ceil(route.hp[r.node]*difficulties[r.difficulty].hp*(1+r.node*.06)),damage:Math.ceil(route.damage*difficulties[r.difficulty].damage),heavy:Math.ceil(route.heavy*difficulties[r.difficulty].damage)}:{hp:route.hp[r.node],damage:route.damage,heavy:route.heavy};}
function forecast(r,route){const key=r.enemy.pattern[(r.turn+r.enemy.offset)%4],base=stats(r,route),modern=r.ruleset===2,pressure=modern?Math.min(8,Math.max(0,r.turn-3)*2)+(r.enemy.enraged?3:0):0;const living=r.party.map((p,i)=>p.hp>0?i:-1).filter(i=>i>=0);let target=living[(r.turn+r.node)%living.length];if(key==='hunt')target=r.party.reduce((best,p,i)=>p.hp>0&&(r.party[best].hp===0||p.hp/r.party[i].maxHp<r.party[best].hp/r.party[best].maxHp)?i:best,0);const targets=key==='heavy'?living:[target],damage=key==='heavy'?base.heavy+pressure:key==='strike'?base.damage+pressure:key==='hunt'?base.damage+4+pressure:key==='drain'?Math.max(4,base.damage-3)+pressure:key==='brace'?(modern?4:3):0;
const names=r.enemy.kind==='warden'?{strike:'鎚の一撃',charge:'炉の力を溜める',heavy:'地砕き・全員',brace:'反撃の盾',drain:'灯力を2奪う',hunt:'弱った仲間を狙う'}:{strike:'角の一撃',charge:'森の息・自己回復',heavy:'森震い・全員',brace:'護石の盾',drain:'灯力を2奪う',hunt:'弱った仲間を狙う'};return{key,targets,damage,name:names[key],pressure};}
function insight(r){if(r.ruleset!==2)return '弓で隙を作り、灯火の印を剣で斬る';if(r.party.filter(p=>p.joined!==false).length<3)return '必殺技ゲージが満ちると、固有スキルを自動発動';if(r.enemy.enraged)return '覚醒中：攻撃+3　長期戦でも強まる';if(r.enemy.vulnerable)return 'BREAK後の好機：与えるダメージ+25%';if(r.enemy.steadfast)return '立て直し中：崩しが通りづらい';return r.route==='forest'?'溜め中の灯の印・矢の隙で、自己回復を止める':r.route==='stone'?'盾の間は剣に反撃　崩し・貫通で対処':r.route==='tide'?'灯力を奪う敵　癒しと護りの判断が鍵':'大振り・弱点狙い・灯力奪取の連続';}
function auto(s,forecast,skills,preview){const r=s.run,mode=s.settings.autoMode||'balanced',available=[1,2,0].filter(i=>r.party[i].hp>0&&!r.party[i].acted),list=i=>skills(i).filter(x=>x.cost<=r.mana),has=(i,id)=>list(i).some(x=>x.id===id),lowest=Math.min(...r.party.filter(p=>p.joined!==false).map(p=>p.hp/p.maxHp)),dead=r.party.some(p=>p.joined!==false&&p.hp===0),heavy=forecast.key==='heavy',guardNeeded=heavy&&r.poise<3&&mode!=='aggressive';
const charged=available.find(i=>r.skills?.[i]>=100);if(charged!==undefined)return{unit:charged,id:'skill'};
if(r.party.filter(p=>p.joined!==false).length===3&&r.resonance>=100&&(heavy||r.enemy.hp>preview('slash')+8))return{unit:r.active,id:'burst'};
if(available.includes(2)&&(dead||lowest<(mode==='defensive'?.78:.48))){if(has(2,'renew')&&(dead||r.party.filter(p=>p.hp<p.maxHp*.7).length>=2))return{unit:2,id:'renew'};if(has(2,'heal'))return{unit:2,id:'heal'};if(has(2,'focus'))return{unit:2,id:'focus'};}
if(available.includes(1)){if(has(1,'snare')&&(heavy||r.poise>=1)&&mode!=='aggressive')return{unit:1,id:'snare'};if(forecast.key==='brace'&&has(1,'break'))return{unit:1,id:'break'};if(has(1,'pierce')&&(r.enemy.hp<preview('pierce')||mode==='aggressive'))return{unit:1,id:'pierce'};return{unit:1,id:'shoot'};}
if(available.includes(2)){if(r.mana===0)return{unit:2,id:'focus'};if(has(2,'brand')&&mode==='aggressive')return{unit:2,id:'brand'};return{unit:2,id:'light'};}
if(available.includes(0)){if(guardNeeded&&r.enemy.hp>preview('slash'))return{unit:0,id:'guard'};if(forecast.key==='charge'&&r.route==='forest'&&r.marks&&mode==='defensive')return{unit:0,id:'guard'};if(mode==='defensive'&&has(0,'rally')&&lowest<.8)return{unit:0,id:'rally'};return{unit:0,id:'slash'};}return null;}
window.LanternTactics=Object.freeze({difficulties,patterns,stats,forecast,insight,auto});
})();
