'use client';
import {FormEvent,useState} from 'react';
type Change={id:string;title:string;reason:string;action:string;impact:string};
type Analysis={target:string;title:string;summary:string;changes:Change[]};
export default function Page(){
 const [url,setUrl]=useState(''); const [busy,setBusy]=useState(false); const [analysis,setAnalysis]=useState<Analysis|null>(null); const [logs,setLogs]=useState(['SYSTEM READY','AUTHORIZED TARGETS ONLY']);
 const add=(s:string)=>setLogs(v=>[...v,s]);
 const run=async(e:FormEvent)=>{e.preventDefault();if(!url.trim())return;setBusy(true);setAnalysis(null);setLogs(['> TARGET '+url,'> ANALYZE','SCANNING...']);try{const r=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url})});if(!r.ok)throw new Error();const d=await r.json();setAnalysis(d);setLogs(v=>[...v,'ANALYSIS COMPLETE',`${d.changes.length} CHANGES AVAILABLE`]);}catch{add('ERROR: ANALYSIS FAILED')}finally{setBusy(false)}};
 const execute=async()=>{if(!analysis)return;setBusy(true);add('> YES');add('EXECUTION REQUESTED...');try{const r=await fetch('/api/execute',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:analysis.target,changes:analysis.changes})});const d=await r.json();add(d.status||'ERROR');add(d.message||'EXECUTION FAILED')}catch{add('ERROR: EXECUTION FAILED')}finally{setBusy(false)}};
 return <main className="terminal"><header><span className="dot"/><b>HACK TERMINAL AI</b><small>AUTHORIZED SITES ONLY</small></header><section className="screen">{logs.map((l,i)=><div key={i} className={l.startsWith('ERROR')?'err':''}>{l}</div>)}{analysis&&<div className="result"><div className="sep">────────────────────</div><b>{analysis.title}</b><p>{analysis.summary}</p>{analysis.changes.map((c,i)=><article key={c.id}><b>[{i+1}] {c.title}</b><span>{c.action}</span><small>{c.reason} · IMPACT: {c.impact}</small></article>)}<div className="confirm">EXECUTE THESE CHANGES?<button disabled={busy} onClick={execute}>YES</button><button disabled={busy} onClick={()=>{setAnalysis(null);add('> NO')}}>NO</button></div></div>}</section><form onSubmit={run}><span>&gt;</span><input aria-label="Target URL" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com" inputMode="url"/><button disabled={busy}>{busy?'RUNNING':'RUN'}</button></form></main>
}
