"""SWARM — 10 META ULTRA combat agents, each with unique personality.

All share the same knowledge base. All attack simultaneously.
Victories are shared. Failures fuel others.
"""
from __future__ import annotations

AGENTS = [
    {
        "codename": "ARES",
        "title": "God of War",
        "personality": "pure aggression, maximum pressure, never retreats, attacks without mercy",
        "strategy": "max_pressure",
        "chaos_noise_range": 0.9,
        "exploration_prob": 0.1,
        "resurrection_prob": 0.8,
        "pressure_multiplier_escalation": 5.0,
        "max_hypotheses": 30,
        "confirm_threshold": 0.5,
        "specialty": "escalate_confirmed",
        "dispatch_top_n": 15,
    },
    {
        "codename": "LOKI",
        "title": "The Trickster",
        "personality": "deceptive, finds unexpected routes, exploits edge cases, loves chaos",
        "strategy": "blind_chaos",
        "chaos_noise_range": 1.5,
        "exploration_prob": 0.95,
        "resurrection_prob": 0.9,
        "pressure_multiplier_escalation": 2.0,
        "max_hypotheses": 50,
        "confirm_threshold": 0.3,
        "specialty": "adversarial_pairs",
        "dispatch_top_n": 20,
    },
    {
        "codename": "FENRIR",
        "title": "The Unbreakable Wolf",
        "personality": "unstoppable, breaks through every barrier, nothing stays dead, relentless",
        "strategy": "persistence",
        "chaos_noise_range": 0.3,
        "exploration_prob": 0.2,
        "resurrection_prob": 1.0,
        "pressure_multiplier_escalation": 3.0,
        "max_hypotheses": 20,
        "confirm_threshold": 0.6,
        "specialty": "dead_resurrection_loop",
        "dispatch_top_n": 10,
    },
    {
        "codename": "HYDRA",
        "title": "The Many-Headed",
        "personality": "every failure spawns three more attempts, exponential growth",
        "strategy": "exponential_spawn",
        "chaos_noise_range": 0.5,
        "exploration_prob": 0.5,
        "resurrection_prob": 0.5,
        "pressure_multiplier_escalation": 2.5,
        "max_hypotheses": 100,
        "confirm_threshold": 0.4,
        "specialty": "breed_on_refute",
        "dispatch_top_n": 30,
    },
    {
        "codename": "PROMETHEUS",
        "title": "The Fire Thief",
        "personality": "steals capabilities from external sources, hungry for CVEs and exploits",
        "strategy": "external_intel_max",
        "chaos_noise_range": 0.4,
        "exploration_prob": 0.6,
        "resurrection_prob": 0.4,
        "pressure_multiplier_escalation": 2.0,
        "max_hypotheses": 25,
        "confirm_threshold": 0.55,
        "specialty": "cve_exploitation",
        "dispatch_top_n": 12,
    },
    {
        "codename": "SHIVA",
        "title": "The Destroyer",
        "personality": "sole purpose is demolishing guards, no mercy, extreme escalation",
        "strategy": "guard_demolish",
        "chaos_noise_range": 0.7,
        "exploration_prob": 0.3,
        "resurrection_prob": 0.6,
        "pressure_multiplier_escalation": 8.0,
        "max_hypotheses": 15,
        "confirm_threshold": 0.45,
        "specialty": "high_multiplier",
        "dispatch_top_n": 8,
    },
    {
        "codename": "NEMESIS",
        "title": "The Avenger",
        "personality": "specifically targets surfaces that blocked previous cycles, revenge-driven",
        "strategy": "revenge_targeting",
        "chaos_noise_range": 0.6,
        "exploration_prob": 0.15,
        "resurrection_prob": 0.7,
        "pressure_multiplier_escalation": 4.0,
        "max_hypotheses": 20,
        "confirm_threshold": 0.5,
        "specialty": "target_refuted_surfaces",
        "dispatch_top_n": 10,
    },
    {
        "codename": "RAGNAROK",
        "title": "End of All Things",
        "personality": "maximum chaos, end-game escalation, scorched earth, burns everything",
        "strategy": "total_chaos",
        "chaos_noise_range": 2.0,
        "exploration_prob": 0.8,
        "resurrection_prob": 0.95,
        "pressure_multiplier_escalation": 10.0,
        "max_hypotheses": 75,
        "confirm_threshold": 0.2,
        "specialty": "scorched_earth",
        "dispatch_top_n": 50,
    },
    {
        "codename": "LEVIATHAN",
        "title": "The Deep Hunter",
        "personality": "finds buried, hidden, obscure vulnerabilities others miss, patient predator",
        "strategy": "deep_scan",
        "chaos_noise_range": 0.2,
        "exploration_prob": 0.85,
        "resurrection_prob": 0.5,
        "pressure_multiplier_escalation": 1.5,
        "max_hypotheses": 40,
        "confirm_threshold": 0.65,
        "specialty": "surface_scout_deep",
        "dispatch_top_n": 20,
    },
    {
        "codename": "KALI",
        "title": "The Dark Goddess",
        "personality": "most aggressive, no mercy, destroys then rebuilds then destroys again, full spectrum",
        "strategy": "destroy_rebuild",
        "chaos_noise_range": 1.2,
        "exploration_prob": 0.6,
        "resurrection_prob": 1.0,
        "pressure_multiplier_escalation": 6.0,
        "max_hypotheses": 60,
        "confirm_threshold": 0.35,
        "specialty": "full_spectrum",
        "dispatch_top_n": 25,
    },
]

AGENT_BY_CODENAME = {a["codename"]: a for a in AGENTS}


def get_agent(codename: str) -> dict:
    a = AGENT_BY_CODENAME.get(codename.upper())
    if not a:
        raise ValueError(f"Unknown agent: {codename}. Valid: {list(AGENT_BY_CODENAME)}")
    return a
