import { createHash, randomBytes } from 'crypto';
import { router, json, error, db, requireAuth } from '@appdeploy/sdk';

type Deal={company:string;amount:number;stage:string;nextAction:string;dueDate:string;createdAt:string;updatedAt:string};
type EventRecord={source:string;title:string;detail:string;occurredAt:string;createdAt:string};
type TokenRecord={hash:string;createdAt:string};
const clean=(v:unknown,max=500)=>typeof v==='string'?v.trim().slice(0,max):'';
const dealsTable=(u:string)=>`deals:${u}`;const eventsTable=(u:string)=>`events:${u}`;const tokensTable=(u:string)=>`integration_tokens:${u}`;
const allowedStages=['新規','商談予定','提案済','受注','失注'];
const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
export const handler=router({
 'GET /api/_healthcheck':[async()=>json({message:'Success'})],
 'GET /api/dashboard':[requireAuth(),async(ctx)=>{const userId=ctx.user!.userId;const [deals,events,tokens]=await Promise.all([db.list<Deal>(dealsTable(userId),{limit:100}),db.list<EventRecord>(eventsTable(userId),{limit:50}),db.list<TokenRecord>(tokensTable(userId),{limit:1})]);return json({deals:deals.items.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),events:events.items.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),integrationConfigured:tokens.items.length>0})}],
 'POST /api/deals':[requireAuth(),async(ctx)=>{const b=(ctx.body||{}) as Partial<Deal>;const company=clean(b.company,160);const amount=Number(b.amount||0);const stage=allowedStages.includes(clean(b.stage,30))?clean(b.stage,30):'新規';if(!company||!Number.isFinite(amount)||amount<0||amount>1000000000)return error('invalid_deal',400);const now=new Date().toISOString();const [id]=await db.add(dealsTable(ctx.user!.userId),[{company,amount,stage,nextAction:clean(b.nextAction,500),dueDate:clean(b.dueDate,80),createdAt:now,updatedAt:now}]);if(!id)return error('save_failed',500);return json({ok:true,id},201)}],
 'PUT /api/deals/:id':[requireAuth(),async(ctx)=>{const userId=ctx.user!.userId;const [existing]=await db.get<Deal>(dealsTable(userId),[ctx.params.id]);if(!existing)return error('not_found',404);const b=(ctx.body||{}) as Partial<Deal>;const company=clean(b.company,160);const amount=Number(b.amount||0);const stage=allowedStages.includes(clean(b.stage,30))?clean(b.stage,30):existing.stage;if(!company||!Number.isFinite(amount)||amount<0||amount>1000000000)return error('invalid_deal',400);const record={company,amount,stage,nextAction:clean(b.nextAction,500),dueDate:clean(b.dueDate,80),createdAt:existing.createdAt,updatedAt:new Date().toISOString()};const [ok]=await db.update(dealsTable(userId),[{id:ctx.params.id,record}]);if(!ok)return error('update_failed',500);return json({ok:true})}],
 'DELETE /api/deals/:id':[requireAuth(),async(ctx)=>{const [ok]=await db.delete(dealsTable(ctx.user!.userId),[ctx.params.id]);return ok?json({ok:true}):error('delete_failed',404)}],
 'POST /api/integration-token':[requireAuth(),async(ctx)=>{const userId=ctx.user!.userId;const raw=randomBytes(32).toString('hex');const record={hash:hash(raw),createdAt:new Date().toISOString()};const table=tokensTable(userId);const existing=await db.list<TokenRecord>(table,{limit:1});if(existing.items.length){const [ok]=await db.update(table,[{id:existing.items[0].id,record}]);if(!ok)return error('token_update_failed',500)}else{const [id]=await db.add(table,[record]);if(!id)return error('token_create_failed',500)}return json({token:raw,userId})}],
 'POST /api/events/test':[requireAuth(),async(ctx)=>{const now=new Date().toISOString();const [id]=await db.add(eventsTable(ctx.user!.userId),[{source:'system',title:'受信テスト成功',detail:'アプリ内部のイベント保存経路は正常です',occurredAt:now,createdAt:now}]);return id?json({ok:true,id},201):error('save_failed',500)}],
 'POST /api/ingest':[async(ctx)=>{const headers=(ctx.event&&ctx.event.headers?ctx.event.headers:{}) as Record<string,string|undefined>;const userId=clean(headers['x-user-id']||headers['X-User-Id'],120);const token=clean(headers['x-ingest-token']||headers['X-Ingest-Token'],200);if(!userId||!token)return error('unauthorized',401);const tokens=await db.list<TokenRecord>(tokensTable(userId),{limit:1});if(!tokens.items.length||tokens.items[0].hash!==hash(token))return error('unauthorized',401);const b=(ctx.body||{}) as Partial<EventRecord>;const sourceRaw=clean(b.source,30).toLowerCase();const source=['gmail','calendar','slack','system'].includes(sourceRaw)?sourceRaw:'system';const title=clean(b.title,300);if(!title)return error('invalid_event',400);const now=new Date().toISOString();const [id]=await db.add(eventsTable(userId),[{source,title,detail:clean(b.detail,1200),occurredAt:clean(b.occurredAt,80)||now,createdAt:now}]);return id?json({ok:true,id},201):error('save_failed',500)}]
});