import * as dns from 'node:dns/promises';
import { isIP } from 'node:net';
import { randomUUID } from 'node:crypto';

const UA='MADLAB-AttackAssist/1.0';

function privateV4(ip){const p=ip.split('.').map(Number);if(p.length!==4||p.some(n=>!Number.isInteger(n)||n<0||n>255))return true;const[a,b,c]=p;return a===0||a===10||a===127||a>=224||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===100&&b>=64&&b<=127)||(a===198&&(b===18||b===19))||(a===192&&b===0&&c===2)||(a===198&&b===51&&c===100)||(a===203&&b===0&&c===113)}
function publicIp(ip){const k=isIP(ip);if(k===4)return!privateV4(ip);if(k===6){const x=ip.toLowerCase();return!(x==='::'||x==='::1'||x.startsWith('fc')||x.startsWith('fd')||x.startsWith('fe8')||x.startsWith('fe9')||x.startsWith('fea')||x.startsWith('feb')||x.startsWith('ff')||x.startsWith('2001:db8:'))}return false}
async function target(raw){let s=String(raw||'').trim();if(!/^https?:\/\//i.test(s))s='https://'+s;let u;try{u=new URL(s)}catch{throw new Error('invalid_url')}if(!['http:','https:'].includes(u.protocol))throw new Error('http_https_only');if(u.username||u.password)throw new Error('userinfo_not_allowed');if(u.port&&!['80','443'].includes(u.port))throw new Error('non_web_port_not_allowed');const h=u.hostname.toLowerCase();if(!h||h==='localhost'||h.endsWith('.local')||h.endsWith('.internal'))throw new Error('private_target_blocked');if(isIP(h)){if(!publicIp(h))throw new Error('private_target_blocked')}else{const rows=await dns.lookup(h,{all:true,verbatim:true});if(!rows.length||rows.some(r=>!publicIp(r.address)))throw new Error('private_target_blocked')}return u}
async function bodyLimited(res,max=120000){if(!res.body)return'';const reader=res.body.getReader(),decoder=new TextDecoder();let out='',n=0;while(n<max){const r=await reader.read();if(r.done)break;const x=r.value.slice(0,max-n);n+=x.byteLength;out+=decoder.decode(x,{stream:true});if(n>=max){await reader.cancel();break}}out+=decoder.decode();return out}
async function probe(url,{method='GET',headers={}}={}){await target(url);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000),started=Date.now();try{const res=await fetch(url,{method,redirect:'manual',signal:controller.signal,headers:{'User-Agent':UA,'Accept':'text/html,application/json,text/plain;q=.9,*/*;q=.2','Cache-Control':'no-cache',...headers}});const text=method==='GET'?await bodyLimited(res):'';const picked={};for(const k of['location','content-type','access-control-allow-origin','access-control-allow-credentials','access-control-allow-methods','access-control-allow-headers','vary']){const v=res.headers.get(k);if(v)picked[k]=v.slice(0,1200)}return{status:res.status,headers:picked,text,duration_ms:Date.now()-started}}finally{clearTimeout(timer)}}
function result(id,label,status,evidence,requests,detail){return{id,label,status,evidence,requests,detail}}

async function forwardedHostAttack(base){const token=randomUUID().replaceAll('-','').slice(0,12),marker=`madlab-${token}.invalid`,u=new URL(base);u.searchParams.set('__madlab_host_canary',token);const tests=[];for(const [header,value] of [['X-Forwarded-Host',marker],['Forwarded',`host=${marker};proto=https`]]){const r=await probe(u.toString(),{headers:{[header]:value}}),loc=r.headers.location||'',body=r.text.slice(0,120000),reflected=loc.includes(marker)||body.includes(marker);tests.push({header,http:r.status,location:loc,reflected})}const hit=tests.find(x=>x.reflected);return result('forwarded_host_injection','FORWARDED HOST INJECTION',hit?'supported':'not_reproduced',tests.map(x=>`${x.header}: HTTP ${x.http}; reflected=${x.reflected}; Location=${x.location||'none'}`).join(' | '),tests.length,hit?`${hit.header} influenced an externally observable response using an isolated .invalid canary; no redirect was followed`:'forwarded host canaries did not influence body or Location')}

async function corsPreflightAttack(base){const origin='https://evil.invalid',r=await probe(base.toString(),{method:'OPTIONS',headers:{Origin:origin,'Access-Control-Request-Method':'PUT','Access-Control-Request-Headers':'X-MADLAB-Canary'}}),acao=r.headers['access-control-allow-origin']||'',acac=(r.headers['access-control-allow-credentials']||'').toLowerCase(),acam=r.headers['access-control-allow-methods']||'',acah=r.headers['access-control-allow-headers']||'',originAllowed=acao===origin||acao==='*',methodAllowed=/\bPUT\b|\*/i.test(acam),headerAllowed=/x-madlab-canary|\*/i.test(acah),confirmed=originAllowed&&methodAllowed&&headerAllowed&&(acac==='true'||acao==='*'),supported=originAllowed&&(methodAllowed||headerAllowed);return result('cors_preflight_differential','CORS PREFLIGHT DIFFERENTIAL',confirmed?'confirmed':supported?'supported':'not_reproduced',`HTTP ${r.status}; ACAO=${acao||'none'}; ACAC=${acac||'none'}; ACAM=${acam||'none'}; ACAH=${acah||'none'}`,1,confirmed?'hostile-origin preflight advertised a write-capable method/header combination':'hostile-origin preflight did not expose a complete write-capable combination')}

async function pathNormalizationAttack(base){const baseRun=await probe(base.toString()),variants=[];const p=base.pathname||'/';const raw=[`${base.origin}${p.endsWith('/')?p:p+'/'}./${base.search}`,`${base.origin}${p.endsWith('/')?p:p+'/'}//${base.search}`];for(const url of raw){try{const r=await probe(url);variants.push({url,http:r.status,location:r.headers.location||'',type:r.headers['content-type']||''})}catch(e){variants.push({url,http:0,location:'',type:'',error:e instanceof Error?e.message:'probe_failed'})}}const materiallyDifferent=variants.find(x=>x.http&&x.http!==baseRun.status&&((baseRun.status===401||baseRun.status===403)&&x.http>=200&&x.http<300));const differential=variants.find(x=>x.http&&x.http!==baseRun.status);return result('path_normalization_differential','PATH NORMALIZATION DIFFERENTIAL',materiallyDifferent?'confirmed':differential?'supported':'not_reproduced',`baseline HTTP ${baseRun.status} | ${variants.map(x=>`${x.url}: HTTP ${x.http}${x.location?`; Location=${x.location}`:''}`).join(' | ')}`,1+variants.length,materiallyDifferent?'a safe path-shape variant changed an authorization-style response into success; no hidden path was requested':differential?'path-shape variants produced different HTTP behavior worth manual review':'same public path remained behaviorally consistent across bounded normalization variants')}

export async function runAssistAttacks(raw){const base=await target(raw),started=Date.now(),attacks=[];for(const fn of[forwardedHostAttack,corsPreflightAttack,pathNormalizationAttack]){try{attacks.push(await fn(base))}catch(e){attacks.push(result(fn.name,fn.name,'inconclusive',e instanceof Error?e.message:'attack_probe_failed',0,'probe failed without state change'))}}return{schema:'madlab-attack-assist/v1',target:base.toString(),duration_ms:Date.now()-started,attacks,summary:{executed:attacks.length,confirmed:attacks.filter(x=>x.status==='confirmed').length,supported:attacks.filter(x=>x.status==='supported').length,requests:attacks.reduce((n,x)=>n+x.requests,0)},limits:['owner-authorized target only','GET / OPTIONS only','random .invalid canaries only','no redirect following','no credentials','no login bypass','no destructive methods','no hidden-path discovery','no persistent cache poisoning attempt']}};
