import * as dns from 'node:dns/promises';
import { isIP } from 'node:net';
import { randomUUID } from 'node:crypto';
import { runAssistAttacks } from './attack-assist.js';
import { runAdvancedAttacks } from './attack-advanced.js';

const UA='MADLAB-AttackEngine/3.2';
const REDIRECT_PARAMS=['next','url','redirect','return','continue'];
const REFLECT_PARAMS=['q','search','query','name'];

function privateV4(ip){const p=ip.split('.').map(Number);if(p.length!==4||p.some(n=>!Number.isInteger(n)||n<0||n>255))return true;const[a,b,c]=p;return a===0||a===10||a===127||a>=224||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===100&&b>=64&&b<=127)||(a===198&&(b===18||b===19))||(a===192&&b===0&&c===2)||(a===198&&b===51&&c===100)||(a===203&&b===0&&c===113)}
function publicIp(ip){const k=isIP(ip);if(k===4)return!privateV4(ip);if(k===6){const x=ip.toLowerCase();return!(x==='::'||x==='::1'||x.startsWith('fc')||x.startsWith('fd')||x.startsWith('fe8')||x.startsWith('fe9')||x.startsWith('fea')||x.startsWith('feb')||x.startsWith('ff')||x.startsWith('2001:db8:'))}return false}
async function target(raw){let s=String(raw||'').trim();if(!/^https?:\/\//i.test(s))s='https://'+s;let u;try{u=new URL(s)}catch{throw new Error('invalid_url')}if(!['http:','https:'].includes(u.protocol))throw new Error('http_https_only');if(u.username||u.password)throw new Error('userinfo_not_allowed');if(u.port&&!['80','443'].includes(u.port))throw new Error('non_web_port_not_allowed');const h=u.hostname.toLowerCase();if(!h||h==='localhost'||h.endsWith('.local')||h.endsWith('.internal'))throw new Error('private_target_blocked');if(isIP(h)){if(!publicIp(h))throw new Error('private_target_blocked')}else{const rows=await dns.lookup(h,{all:true,verbatim:true});if(!rows.length||rows.some(r=>!publicIp(r.address)))throw new Error('private_target_blocked')}return u}
async function bodyLimited(res,max=180000){if(!res.body)return'';const reader=res.body.getReader(),decoder=new TextDecoder();let out='',n=0;while(n<max){const r=await reader.read();if(r.done)break;const x=r.value.slice(0,max-n);n+=x.byteLength;out+=decoder.decode(x,{stream:true});if(n>=max){await reader.cancel();break}}out+=decoder.decode();return out}
async function probe(url,{method='GET',headers={}}={}){await target(url);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000),started=Date.now();try{const res=await fetch(url,{method,redirect:'manual',signal:controller.signal,headers:{'User-Agent':UA,'Accept':'text/html,application/json,text/plain;q=.9,*/*;q=.2','Cache-Control':'no-cache',...headers}});const text=method==='GET'?await bodyLimited(res):'';const picked={};for(const k of['location','access-control-allow-origin','access-control-allow-credentials','access-control-allow-methods','allow','cache-control','vary','content-type']){const v=res.headers.get(k);if(v)picked[k]=v.slice(0,1000)}return{status:res.status,headers:picked,text,duration_ms:Date.now()-started}}finally{clearTimeout(timer)}}
function result(id,label,status,evidence,requests,detail){return{id,label,status,evidence,requests,detail}}

async function corsAttack(base){const tests=[];for(const origin of['https://evil.invalid','null']){const r=await probe(base.toString(),{headers:{Origin:origin}});const acao=r.headers['access-control-allow-origin']||'',acac=(r.headers['access-control-allow-credentials']||'').toLowerCase();tests.push({origin,http:r.status,acao,acac,duration_ms:r.duration_ms})}const reflected=tests.find(x=>x.origin==='https://evil.invalid'&&x.acao===x.origin),nullCred=tests.find(x=>x.origin==='null'&&x.acao==='null'&&x.acac==='true'),cred=tests.find(x=>x.acao===x.origin&&x.acac==='true');const confirmed=Boolean(cred||nullCred);return result('active_cors','ACTIVE CORS ATTACK',confirmed?'confirmed':reflected?'supported':'not_reproduced',tests.map(x=>`${x.origin}: HTTP ${x.http}; ACAO=${x.acao||'none'}; ACAC=${x.acac||'none'}`).join(' | '),tests.length,confirmed?'credentialed cross-origin response policy accepted a hostile canary origin':'hostile canary origins were not accepted with credentials')}
async function redirectAttack(base){const dest='https://example.invalid/madlab-redirect-canary',tests=[];for(const p of REDIRECT_PARAMS){const u=new URL(base);u.searchParams.set(p,dest);const r=await probe(u.toString());const loc=r.headers.location||'';let external=false;try{external=new URL(loc,u).hostname==='example.invalid'}catch{}tests.push({param:p,http:r.status,location:loc,external})}const hit=tests.find(x=>x.external&&[301,302,303,307,308].includes(x.http));return result('active_redirect','REDIRECT ATTACK',hit?'confirmed':'not_reproduced',tests.map(x=>`${x.param}: HTTP ${x.http}; Location=${x.location||'none'}`).join(' | '),tests.length,hit?`external redirect accepted through ${hit.param}; destination was not followed`:'common redirect parameters did not produce an external redirect')}
async function reflectionAttack(base){const marker=`MADLAB_ATTACK_${randomUUID().replaceAll('-','').slice(0,14)}`,tests=[];for(const p of REFLECT_PARAMS){const u=new URL(base);u.searchParams.set(p,marker);const r=await probe(u.toString());const reflected=r.text.includes(marker);tests.push({param:p,http:r.status,reflected})}const hit=tests.find(x=>x.reflected);return result('active_reflection','REFLECTION ATTACK',hit?'supported':'not_reproduced',tests.map(x=>`${x.param}: HTTP ${x.http}; reflected=${x.reflected}`).join(' | '),tests.length,hit?`inert marker reflected via ${hit.param}; script execution was not attempted`:'inert marker was not reflected through common input names')}
async function methodAttack(base){const r=await probe(base.toString(),{method:'OPTIONS'}),allow=`${r.headers.allow||''},${r.headers['access-control-allow-methods']||''}`.replace(/^,|,$/g,''),write=/\b(PUT|PATCH|DELETE)\b/i.test(allow),trace=/\bTRACE\b/i.test(allow);return result('active_methods','METHOD ATTACK',trace?'supported':write?'supported':'not_reproduced',`HTTP ${r.status}; Allow=${allow||'none'}`,1,trace?'TRACE is advertised; TRACE itself was not executed':write?'write-capable methods are advertised; authorization was not bypassed':'no write-capable methods were advertised by OPTIONS')}

export async function runActiveAttacks(raw){const base=await target(raw),started=Date.now(),attacks=[];for(const fn of[corsAttack,redirectAttack,reflectionAttack,methodAttack]){try{attacks.push(await fn(base))}catch(e){attacks.push(result(fn.name,fn.name,'inconclusive',e instanceof Error?e.message:'attack_probe_failed',0,'probe failed without state change'))}}try{const assist=await runAssistAttacks(base.toString());attacks.push(...assist.attacks)}catch(e){attacks.push(result('attack_assist','ATTACK ASSIST','inconclusive',e instanceof Error?e.message:'attack_assist_failed',0,'assist lane failed without state change'))}try{const advanced=await runAdvancedAttacks(base.toString());attacks.push(...advanced.attacks)}catch(e){attacks.push(result('attack_advanced','ADVANCED ATTACK LANE','inconclusive',e instanceof Error?e.message:'attack_advanced_failed',0,'advanced lane failed without state change'))}return{schema:'madlab-active-attack/v3',target:base.toString(),duration_ms:Date.now()-started,attacks,summary:{executed:attacks.length,confirmed:attacks.filter(x=>x.status==='confirmed').length,supported:attacks.filter(x=>x.status==='supported').length,requests:attacks.reduce((n,x)=>n+x.requests,0)},limits:['owner-authorized target only','bounded crafted requests only','GET / HEAD / OPTIONS / PROPFIND; no destructive methods','reserved-domain canaries are never followed','reflection uses inert random markers','forwarded-host canaries use isolated .invalid names','no credentials','no login bypass','no exploit payload execution','no hidden-path brute force','no persistent cache poisoning attempt']}}
