import { randomUUID } from 'node:crypto';
import { ATTACK_CANARY_ACTIONS } from './contracts.js';

const UA='MADLAB-ControlledImpact/1.1';

async function readLimited(res,max=65536){if(!res.body)return'';const reader=res.body.getReader(),decoder=new TextDecoder();let out='',n=0;while(n<max){const r=await reader.read();if(r.done)break;const x=r.value.slice(0,max-n);n+=x.byteLength;out+=decoder.decode(x,{stream:true});if(n>=max){await reader.cancel();break}}out+=decoder.decode();return out}
function sameOriginHttps(raw,origin){const u=new URL(String(raw||''),origin);if(u.protocol!=='https:'||u.origin!==origin||u.username||u.password||u.hash)throw new Error('verify_url_not_same_origin_https');return u}
async function request(url,init){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const res=await fetch(url,{...init,redirect:'manual',signal:controller.signal,headers:{'User-Agent':UA,...(init.headers||{})}});if([301,302,303,307,308].includes(res.status))throw new Error('impact_redirect_blocked');return{res,text:await readLimited(res)}}finally{clearTimeout(timer)}}
function parseJson(text){try{return JSON.parse(text)}catch{return{message:String(text||'').slice(0,500)}}}
function verifySpec(body,origin,phase){const raw=body?.verify_url||body?.proof_url;if(!raw)return null;const url=sameOriginHttps(raw,origin),restore=phase==='restore';const containsRaw=restore?body?.restore_contains:body?.verify_contains,notContainsRaw=restore?body?.restore_not_contains:body?.verify_not_contains,statusRaw=restore?body?.restore_status:body?.verify_status;const contains=typeof containsRaw==='string'?containsRaw.slice(0,240):'',notContains=typeof notContainsRaw==='string'?notContainsRaw.slice(0,240):'',status=Number.isInteger(Number(statusRaw))?Number(statusRaw):null;return{url:url.toString(),contains,notContains,status}}
async function verifyPublic(spec){if(!spec)return{attempted:false,confirmed:false,reason:'no_public_verify_contract'};const{res,text}=await request(spec.url,{method:'GET',headers:{Accept:'text/html,application/json,text/plain;q=.9,*/*;q=.2','Cache-Control':'no-cache'}});const statusOk=spec.status===null||res.status===spec.status,containsOk=!spec.contains||text.includes(spec.contains),notContainsOk=!spec.notContains||!text.includes(spec.notContains);return{attempted:true,confirmed:statusOk&&containsOk&&notContainsOk,url:spec.url,http_status:res.status,status_expected:spec.status,contains_expected:spec.contains||'',not_contains_expected:spec.notContains||'',contains_observed:spec.contains?containsOk:null,not_contains_observed:spec.notContains?notContainsOk:null,evidence:`GET ${spec.url} -> HTTP ${res.status}${spec.status!==null?` expected=${spec.status}`:''}${spec.contains?`; contains=${containsOk?'yes':'no'}`:''}${spec.notContains?`; absent=${notContainsOk?'yes':'no'}`:''}`}}
async function mutate(channel,actionId,approvalCode,operation,runId,rollbackToken=''){const payload={schema:'madlab-controlled-impact/v1',operation,action_id:actionId,target_origin:channel.target,approval_code:approvalCode,run_id:runId,requested_by:'MADLAB DeepGuard Controlled Impact',requested_at:new Date().toISOString(),intent:'owner-authorized-controlled-impact',canary_only:true,...(rollbackToken?{rollback_token:rollbackToken}:{})};const{res,text}=await request(channel.endpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});const body=parseJson(text);return{ok:res.ok&&body.accepted!==false,http_status:res.status,body,evidence:String(body.evidence||`HTTP ${res.status}`).slice(0,1200),message:String(body.message||body.status||(res.ok?'accepted':'rejected')).slice(0,500)}}

export async function runControlledImpact(channel,actionId,approvalCode,{autoRollback=true}={}){if(!channel?.available||!channel?.endpoint)throw new Error('action_channel_unavailable');if(!ATTACK_CANARY_ACTIONS.has(actionId))throw new Error('controlled_impact_canary_only');if(!channel.actions?.some(x=>x.id===actionId))throw new Error('action_not_advertised');if(!/^[A-Za-z0-9._~\-]{6,160}$/.test(String(approvalCode||'')))throw new Error('invalid_approval_code_format');const runId=randomUUID(),started=Date.now();const apply=await mutate(channel,actionId,approvalCode,'apply',runId);if(!apply.ok)return{schema:'madlab-controlled-impact-result/v1',run_id:runId,target:channel.target,action_id:actionId,status:'rejected',impact_confirmed:false,restored:false,duration_ms:Date.now()-started,apply};const appliedVerify=await verifyPublic(verifySpec(apply.body,channel.target,'apply'));const rollbackToken=String(apply.body?.rollback_token||'').slice(0,200),rollbackSupported=apply.body?.rollback_supported===true||Boolean(rollbackToken);let rollback=null,restoreVerify={attempted:false,confirmed:false,reason:'rollback_not_attempted'};if(autoRollback&&rollbackSupported){rollback=await mutate(channel,actionId,approvalCode,'rollback',runId,rollbackToken);if(rollback.ok){const restoreBody={...apply.body,...rollback.body};restoreVerify=await verifyPublic(verifySpec(restoreBody,channel.target,'restore'))}}const impactConfirmed=appliedVerify.confirmed===true,restored=Boolean(rollback?.ok&&restoreVerify.confirmed);let plain='変更要求は受理されましたが、公開面で影響を確認できませんでした。';if(impactConfirmed&&restored)plain='対象サイトの状態が実際に変わり、外部から確認できました。その後ロールバックし、復旧も外部から確認しました。';else if(impactConfirmed&&rollback?.ok&&!restoreVerify.confirmed)plain='対象サイトの状態が実際に変わったことは外部から確認できました。ロールバック要求は受理されましたが、復旧の外部確認は未完了です。';else if(impactConfirmed&&!rollback)plain='対象サイトの状態が実際に変わったことを外部から確認しました。自動ロールバック契約はありません。';return{schema:'madlab-controlled-impact-result/v1',run_id:runId,target:channel.target,action_id:actionId,status:impactConfirmed?'impact_confirmed':'accepted_unverified',impact_confirmed:impactConfirmed,restored,duration_ms:Date.now()-started,plain_result:plain,apply:{http_status:apply.http_status,message:apply.message,evidence:apply.evidence,verify:appliedVerify,reversible:rollbackSupported},rollback:rollback?{accepted:rollback.ok,http_status:rollback.http_status,message:rollback.message,evidence:rollback.evidence,verify:restoreVerify}:null,boundaries:['owner-authorized target only','target-advertised fixed canary action only','same-origin HTTPS verification only','no redirect following','no arbitrary payload','no credential guessing','no login bypass','automatic rollback only when target provides rollback contract']}}
