import express from 'express';
import * as dns from 'node:dns/promises';
import { isIP } from 'node:net';
import { scan } from './scanner-fixed.js';
import { runActiveAttacks } from './attack.js';
import { ACTIONS, ALLOWED_ACTIONS, ATTACK_CANARY_ACTIONS } from './contracts.js';
import { runControlledImpact } from './controlled-impact.js';

const app=express();
const PORT=Number(process.env.PORT||10000);
const UA='MADLAB-Attack-Orchestrator/3.0';
app.disable('x-powered-by');
app.use(express.json({limit:'32kb'}));
app.use(express.static(new URL('./public',import.meta.url).pathname,{maxAge:0}));

function isPrivateV4(ip){const p=ip.split('.').map(Number);if(p.length!==4||p.some(n=>!Number.isInteger(n)||n<0||n>255))return true;const[a,b,c]=p;return a===0||a===10||a===127||a>=224||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===100&&b>=64&&b<=127)||(a===198&&(b===18||b===19))||(a===192&&b===0&&c===2)||(a===198&&b===51&&c===100)||(a===203&&b===0&&c===113)}
function isPublicIp(ip){const k=isIP(ip);if(k===4)return!isPrivateV4(ip);if(k===6){const x=ip.toLowerCase();return!(x==='::'||x==='::1'||x.startsWith('fc')||x.startsWith('fd')||x.startsWith('fe8')||x.startsWith('fe9')||x.startsWith('fea')||x.startsWith('feb')||x.startsWith('ff')||x.startsWith('2001:db8:'))}return false}
async function publicHttps(raw){let s=String(raw||'').trim();if(!/^https?:\/\//i.test(s))s='https://'+s;let u;try{u=new URL(s)}catch{throw new Error('invalid_url')}if(u.protocol!=='https:')throw new Error('https_required_for_actions');if(u.username||u.password||u.hash)throw new Error('userinfo_or_fragment_not_allowed');if(u.port&&u.port!=='443')throw new Error('https_443_only');const host=u.hostname.toLowerCase();if(!host||host==='localhost'||host.endsWith('.local')||host.endsWith('.internal'))throw new Error('private_target_blocked');if(isIP(host)){if(!isPublicIp(host))throw new Error('private_target_blocked')}else{const rows=await dns.lookup(host,{all:true,verbatim:true});if(!rows.length||rows.some(r=>!isPublicIp(r.address)))throw new Error('private_target_blocked')}return u}
async function readLimited(res,max=65536){if(!res.body)return'';const reader=res.body.getReader(),decoder=new TextDecoder();let out='',n=0;while(n<max){const r=await reader.read();if(r.done)break;const x=r.value.slice(0,max-n);n+=x.byteLength;out+=decoder.decode(x,{stream:true});if(n>=max){await reader.cancel();break}}out+=decoder.decode();return out}
async function noFollow(url,init){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const res=await fetch(url,{...init,redirect:'manual',signal:controller.signal,headers:{'User-Agent':UA,...(init.headers||{})}});if([301,302,303,307,308].includes(res.status))throw new Error('action_redirect_blocked');return{res,text:await readLimited(res)}}finally{clearTimeout(timer)}}
async function discover(raw){const target=await publicHttps(raw),manifestUrl=new URL('/.well-known/madlab-action.json',target.origin),{res,text}=await noFollow(manifestUrl.toString(),{method:'GET',headers:{Accept:'application/json'}});if(res.status===404)return{available:false,target:target.origin,reason:'manifest_not_found',actions:[]};if(!res.ok)return{available:false,target:target.origin,reason:`manifest_http_${res.status}`,actions:[]};let m;try{m=JSON.parse(text)}catch{return{available:false,target:target.origin,reason:'invalid_action_manifest',actions:[]}}if(m?.schema!=='madlab-safe-action/v1'||m?.enabled!==true||m?.owner_only!==true||typeof m?.endpoint!=='string')return{available:false,target:target.origin,reason:'invalid_action_manifest_or_owner_lock',actions:[]};let endpoint;try{endpoint=new URL(m.endpoint,target.origin)}catch{return{available:false,target:target.origin,reason:'invalid_action_endpoint',actions:[]}}if(endpoint.origin!==target.origin||endpoint.protocol!=='https:'||endpoint.username||endpoint.password||endpoint.hash)return{available:false,target:target.origin,reason:'action_endpoint_not_same_origin',actions:[]};const actions=(Array.isArray(m.actions)?m.actions:[]).flatMap(x=>{if(!x||typeof x!=='object')return[];const id=String(x.id||''),label=String(x.label||ACTIONS[id]?.label||id);if(!ALLOWED_ACTIONS.has(id)||!label||label.length>100)return[];return[{id,label,description:String(x.description||'').slice(0,240),kind:ATTACK_CANARY_ACTIONS.has(id)?'attack_canary':'remediation'}]}).slice(0,64);return{available:actions.length>0,target:target.origin,manifest_url:manifestUrl.toString(),endpoint:endpoint.toString(),actions,reason:actions.length?'':'no_supported_actions'}}
async function executeAction(channel,actionId,approvalCode){if(!channel.available||!channel.endpoint)throw new Error('action_channel_unavailable');if(!ALLOWED_ACTIONS.has(actionId))throw new Error('action_not_allowed');if(!/^[A-Za-z0-9._~\-]{6,160}$/.test(String(approvalCode||'')))throw new Error('invalid_approval_code_format');if(!channel.actions.some(x=>x.id===actionId))throw new Error('action_not_advertised');const canary=ATTACK_CANARY_ACTIONS.has(actionId),started=Date.now(),{res,text}=await noFollow(channel.endpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({schema:'madlab-safe-action-request/v1',action_id:actionId,target_origin:channel.target,approval_code:approvalCode,requested_by:'MADLAB DeepGuard Attack Console',requested_at:new Date().toISOString(),intent:canary?'owner-authorized-attack-canary':'owner-authorized-remediation',canary_only:canary})});let body={};try{body=JSON.parse(text)}catch{body={message:text.slice(0,500)}}return{action_id:actionId,label:ACTIONS[actionId]?.label||actionId,kind:canary?'attack_canary':'remediation',accepted:res.ok&&body.accepted!==false,http_status:res.status,duration_ms:Date.now()-started,message:String(body.message||body.status||(res.ok?'action accepted':'action rejected')).slice(0,500),evidence:String(body.evidence||`HTTP ${res.status}`).slice(0,1000),reversible:typeof body.reversible==='boolean'?body.reversible:null}}
function findingResults(before,after,cap,executions){const afterIds=new Set((after?.findings||[]).map(x=>x.id));return(before.findings||[]).map(f=>{const candidates=Array.isArray(f.action_candidates)?f.action_candidates:[],selected=candidates.find(x=>cap.has(x))||candidates[0]||null,connected=Boolean(selected&&cap.has(selected)),execution=selected?executions.find(x=>x.action_id===selected):null,resolved=Boolean(after&&execution?.accepted&&!afterIds.has(f.id)),status=resolved?'resolved':execution?.accepted?'changed_but_still_present':connected?'ready':selected?'actuator_missing':'diagnosis_only';return{...f,selected_action:selected,connected,execution,resolved,status}})}
function remediationPlan(before,cap){const planned=[];for(const f of before.findings||[]){const id=(f.action_candidates||[]).find(x=>cap.has(x));if(id&&!planned.includes(id))planned.push(id)}return planned}
async function runStateActions(channel,ids,code){const executions=[];if(!code)return executions;for(const id of ids){try{const r=await executeAction(channel,id,code);executions.push(r);if(!r.accepted&&[401,403].includes(r.http_status))break}catch(e){const message=e instanceof Error?e.message:'execution_failed';executions.push({action_id:id,label:ACTIONS[id]?.label||id,kind:ATTACK_CANARY_ACTIONS.has(id)?'attack_canary':'remediation',accepted:false,http_status:0,duration_ms:0,message,evidence:'',reversible:null});if(/approval|owner|code/i.test(message))break}}return executions}
async function attackPlan(raw,code=''){const before=await scan(raw),active=await runActiveAttacks(before.target);let channel;try{channel=await discover(before.target)}catch(e){channel={available:false,target:new URL(before.target).origin,reason:e instanceof Error?e.message:'action_discovery_failed',actions:[]}}const cap=new Set((channel.actions||[]).map(x=>x.id)),remediation=remediationPlan(before,cap),canaries=(channel.actions||[]).map(x=>x.id).filter(id=>ATTACK_CANARY_ACTIONS.has(id)),statePlan=[...new Set([...remediation,...canaries])],executions=await runStateActions(channel,statePlan,code);let after=null;try{after=await scan(before.target)}catch{}const findings=findingResults(before,after,cap,executions);return{schema:'madlab-attack-plan/v3',target:before.target,before,after,active_attacks:active,channel:{available:channel.available,reason:channel.reason||'',advertised_actions:[...cap],owner_code_supplied:Boolean(code)},planned_state_actions:statePlan,executions,findings,summary:{findings:findings.length,attackable_findings:findings.filter(x=>(x.action_candidates||[]).length>0).length,active_attacks_executed:active.summary.executed,active_requests:active.summary.requests,active_confirmed:active.summary.confirmed,active_supported:active.summary.supported,state_actions_available:statePlan.length,state_actions_attempted:executions.length,state_actions_accepted:executions.filter(x=>x.accepted).length,canary_actions_attempted:executions.filter(x=>x.kind==='attack_canary').length,canary_actions_accepted:executions.filter(x=>x.kind==='attack_canary'&&x.accepted).length,resolved:findings.filter(x=>x.resolved).length,actuator_missing:findings.filter(x=>x.status==='actuator_missing').length}}}

app.get('/api/health',(req,res)=>res.json({ok:true,version:'madlab-deepguard-v3-attack-impact-assist'}));
app.post('/api/scan',async(req,res)=>{if(req.body?.authorized!==true)return res.status(400).json({error:'authorization_confirmation_required'});try{return res.json(await scan(req.body?.url))}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'scan_failed'})}});
app.post('/api/attack/active',async(req,res)=>{if(req.body?.authorized!==true)return res.status(400).json({error:'authorization_confirmation_required'});try{return res.json(await runActiveAttacks(req.body?.url))}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'active_attack_failed'})}});
app.post('/api/action/discover',async(req,res)=>{if(req.body?.owned!==true)return res.status(400).json({error:'owned_target_confirmation_required'});try{return res.json(await discover(req.body?.url))}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'action_discovery_failed'})}});
app.post('/api/action/execute',async(req,res)=>{if(req.body?.owned!==true)return res.status(400).json({error:'owned_target_confirmation_required'});try{const channel=await discover(req.body?.url);return res.json(await executeAction(channel,String(req.body?.action_id||''),String(req.body?.approval_code||'')))}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'action_execute_failed'})}});
app.post('/api/impact/verify',async(req,res)=>{if(req.body?.owned!==true)return res.status(400).json({error:'owned_target_confirmation_required'});const code=String(req.body?.approval_code||'');if(!code)return res.status(400).json({error:'approval_code_required'});try{const channel=await discover(req.body?.url);return res.json(await runControlledImpact(channel,String(req.body?.action_id||''),code,{autoRollback:req.body?.auto_rollback!==false}))}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'controlled_impact_failed'})}});
app.post('/api/attack-plan',async(req,res)=>{if(req.body?.authorized!==true)return res.status(400).json({error:'authorization_confirmation_required'});try{return res.json(await attackPlan(req.body?.url,String(req.body?.approval_code||''))}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'attack_plan_failed'})}});
app.post('/api/diagnose-and-remediate',async(req,res)=>{if(req.body?.authorized!==true)return res.status(400).json({error:'authorization_confirmation_required'});const code=String(req.body?.approval_code||'');if(!code)return res.status(400).json({error:'approval_code_required'});try{return res.json(await attackPlan(req.body?.url,code))}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'remediation_run_failed'})}});
app.use((req,res)=>res.sendFile(new URL('./public/index.html',import.meta.url).pathname));
app.listen(PORT,'0.0.0.0',()=>console.log(`MADLAB Attack Console v3 listening on ${PORT}`));
