import express from 'express';
import * as dns from 'node:dns/promises';
import { isIP } from 'node:net';
import { scan } from './scanner.js';
import { ACTIONS, ALLOWED_ACTIONS } from './contracts.js';

const app=express();
const PORT=Number(process.env.PORT||10000);
const UA='MADLAB-Action-Orchestrator/2.0';
app.disable('x-powered-by');
app.use(express.json({limit:'32kb'}));
app.use(express.static(new URL('./public',import.meta.url).pathname,{extensions:['html'],maxAge:0}));

function privateV4(ip){const p=ip.split('.').map(Number);if(p.length!==4||p.some(n=>!Number.isInteger(n)||n<0||n>255))return true;const[a,b,c]=p;return a===0||a===10||a===127||a>=224||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===100&&b>=64&&b<=127)||(a===198&&(b===18||b===19))||(a===192&&b===0)||(a===192&&b===0&&c===2)||(a===198&&b===51&&c===100)||(a===203&&b===0&&c===113)}
function publicIp(ip){const k=isIP(ip);if(k===4)return!privateV4(ip);if(k===6){const x=ip.toLowerCase();return!(x==='::'||x==='::1'||x.startsWith('fc')||x.startsWith('fd')||x.startsWith('fe8')||x.startsWith('fe9')||x.startsWith('fea')||x.startsWith('feb')||x.startsWith('ff')||x.startsWith('2001:db8:'))}return false}
async function publicHttps(raw){let s=String(raw||'').trim();if(!/^https?:\/\//i.test(s))s='https://'+s;let u;try{u=new URL(s)}catch{throw new Error('invalid_url')}if(u.protocol!=='https:')throw new Error('https_required_for_actions');if(u.username||u.password||u.hash)throw new Error('userinfo_or_fragment_not_allowed');if(u.port&&u.port!=='443')throw new Error('https_443_only');const h=u.hostname.toLowerCase();if(!h||h==='localhost'||h.endsWith('.local')||h.endsWith('.internal'))throw new Error('private_target_blocked');if(isIP(h)){if(!publicIp(h))throw new Error('private_target_blocked')}else{const rows=await dns.lookup(h,{all:true,verbatim:true});if(!rows.length||rows.some(r=>!publicIp(r.address)))throw new Error('private_target_blocked')}return u}
async function textLimited(res,max=65536){if(!res.body)return'';const reader=res.body.getReader(),decoder=new TextDecoder();let out='',n=0;while(n<max){const r=await reader.read();if(r.done)break;const x=r.value.slice(0,max-n);n+=x.byteLength;out+=decoder.decode(x,{stream:true});if(n>=max){await reader.cancel();break}}out+=decoder.decode();return out}
async function noFollow(url,init){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const res=await fetch(url,{...init,redirect:'manual',signal:controller.signal,headers:{'User-Agent':UA,...(init.headers||{})}});if([301,302,303,307,308].includes(res.status))throw new Error('action_redirect_blocked');return{res,text:await textLimited(res)}}finally{clearTimeout(timer)}}
async function discover(raw){const target=await publicHttps(raw),manifestUrl=new URL('/.well-known/madlab-action.json',target.origin),{res,text}=await noFollow(manifestUrl.toString(),{method:'GET',headers:{Accept:'application/json'}});if(res.status===404)return{available:false,target:target.origin,reason:'manifest_not_found',actions:[]};if(!res.ok)return{available:false,target:target.origin,reason:`manifest_http_${res.status}`,actions:[]};let m;try{m=JSON.parse(text)}catch{return{available:false,target:target.origin,reason:'invalid_action_manifest',actions:[]}}if(m?.schema!=='madlab-safe-action/v1'||m?.enabled!==true||m?.owner_only!==true||typeof m?.endpoint!=='string')return{available:false,target:target.origin,reason:'invalid_action_manifest_or_owner_lock',actions:[]};let endpoint;try{endpoint=new URL(m.endpoint,target.origin)}catch{return{available:false,target:target.origin,reason:'invalid_action_endpoint',actions:[]}}if(endpoint.origin!==target.origin||endpoint.protocol!=='https:'||endpoint.username||endpoint.password||endpoint.hash)return{available:false,target:target.origin,reason:'action_endpoint_not_same_origin',actions:[]};const actions=(Array.isArray(m.actions)?m.actions:[]).flatMap(x=>{if(!x||typeof x!=='object')return[];const id=String(x.id||''),label=String(x.label||ACTIONS[id]?.label||id);if(!ALLOWED_ACTIONS.has(id)||!label||label.length>100)return[];return[{id,label,description:String(x.description||'').slice(0,240)}]}).slice(0,40);return{available:actions.length>0,target:target.origin,manifest_url:manifestUrl.toString(),endpoint:endpoint.toString(),actions,reason:actions.length?'':'no_supported_actions'}}
async function execute(discovered,actionId,approvalCode){if(!discovered.available||!discovered.endpoint)throw new Error('action_channel_unavailable');if(!ALLOWED_ACTIONS.has(actionId))throw new Error('action_not_allowed');if(!/^[A-Za-z0-9._~\-]{6,160}$/.test(String(approvalCode||'')))throw new Error('invalid_approval_code_format');if(!discovered.actions.some(x=>x.id===actionId))throw new Error('action_not_advertised');const started=Date.now(),{res,text}=await noFollow(discovered.endpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({schema:'madlab-safe-action-request/v1',action_id:actionId,target_origin:discovered.target,approval_code:approvalCode,requested_by:'MADLAB DeepGuard v2',requested_at:new Date().toISOString()})});let body={};try{body=JSON.parse(text)}catch{body={message:text.slice(0,500)}}return{action_id:actionId,label:ACTIONS[actionId]?.label||actionId,accepted:res.ok&&body.accepted!==false,http_status:res.status,duration_ms:Date.now()-started,message:String(body.message||body.status||(res.ok?'action accepted':'action rejected')).slice(0,500),evidence:String(body.evidence||`HTTP ${res.status}`).slice(0,1000),reversible:typeof body.reversible==='boolean'?body.reversible:null}}
function perFinding(before,after,cap,executions){const afterIds=new Set((after?.findings||[]).map(x=>x.id));return(before.findings||[]).map(f=>{const candidates=Array.isArray(f.action_candidates)?f.action_candidates:[],action=candidates.find(x=>cap.has(x))||candidates[0]||null,connected=Boolean(action&&cap.has(action)),execution=action?executions.find(x=>x.action_id===action):null,resolved=Boolean(after&&execution?.accepted&&!afterIds.has(f.id));return{id:f.id,title:f.title,severity:f.severity,category:f.category,action_candidates:candidates,selected_action:action,connected,execution,resolved,status:resolved?'resolved':execution?.accepted?'changed_but_still_present':connected?'ready':action?'actuator_missing':'diagnosis_only'}})}

app.get('/api/health',(req,res)=>res.json({ok:true,version:'madlab-deepguard-v2'}));
app.post('/api/scan',async(req,res)=>{if(req.body?.authorized!==true)return res.status(400).json({error:'authorization_confirmation_required'});try{return res.json(await scan(req.body?.url))}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'scan_failed'})}});
app.post('/api/action/discover',async(req,res)=>{if(req.body?.owned!==true)return res.status(400).json({error:'owned_target_confirmation_required'});try{return res.json(await discover(req.body?.url))}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'action_discovery_failed'})}});
app.post('/api/action/execute',async(req,res)=>{if(req.body?.owned!==true)return res.status(400).json({error:'owned_target_confirmation_required'});try{const d=await discover(req.body?.url);return res.json(await execute(d,String(req.body?.action_id||''),String(req.body?.approval_code||'')))}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'action_execute_failed'})}});
app.post('/api/diagnose-and-remediate',async(req,res)=>{if(req.body?.authorized!==true)return res.status(400).json({error:'authorization_confirmation_required'});const code=String(req.body?.approval_code||'');if(!code)return res.status(400).json({error:'approval_code_required'});try{const before=await scan(req.body?.url),d=await discover(before.target),cap=new Set((d.actions||[]).map(x=>x.id)),planned=[];for(const f of before.findings||[]){const id=(f.action_candidates||[]).find(x=>cap.has(x));if(id&&!planned.includes(id))planned.push(id)}const executions=[];for(const id of planned){try{const r=await execute(d,id,code);executions.push(r);if(!r.accepted&&[401,403].includes(r.http_status))break}catch(e){executions.push({action_id:id,label:ACTIONS[id]?.label||id,accepted:false,http_status:0,duration_ms:0,message:e instanceof Error?e.message:'execution_failed',evidence:'',reversible:null});if(/approval|owner|code/i.test(e instanceof Error?e.message:''))break}}let after=null;try{after=await scan(before.target)}catch{}const findings=perFinding(before,after,cap,executions);return res.json({schema:'madlab-remediation-run/v2',target:before.target,before,after,channel:{available:d.available,reason:d.reason||'',advertised_actions:[...cap]},planned_actions:planned,executions,findings,summary:{findings:findings.length,with_action_contract:findings.filter(x=>x.selected_action).length,connected:findings.filter(x=>x.connected).length,actions_attempted:executions.length,actions_accepted:executions.filter(x=>x.accepted).length,resolved:findings.filter(x=>x.resolved).length,still_present:findings.filter(x=>x.status==='changed_but_still_present').length,actuator_missing:findings.filter(x=>x.status==='actuator_missing').length}})}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'remediation_run_failed'})}});

app.get('*',(req,res)=>res.sendFile(new URL('./public/index.html',import.meta.url).pathname));
app.listen(PORT,'0.0.0.0',()=>console.log(`MADLAB DeepGuard v2 listening on ${PORT}`));
