import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(__dirname,'..');
const dist=path.join(root,'dist');
const staticDir=path.join(root,'static');
const articles=JSON.parse(fs.readFileSync(path.join(root,'content','articles.json'),'utf8'));
const siteUrl=(process.env.SITE_URL||'http://localhost:4173').replace(/\/$/,'');

fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(dist,{recursive:true});
function cp(src,dst){fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(src,dst)}
for(const f of fs.readdirSync(staticDir))cp(path.join(staticDir,f),path.join(dist,'assets',f));
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function isoDate(s,lang){return new Intl.DateTimeFormat(lang==='ja'?'ja-JP':'en-US',{year:'numeric',month:lang==='ja'?'numeric':'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Tokyo'}).format(new Date(s))}
const searchData=articles.map(a=>({slug:a.slug,titleJa:a.ja.title,titleEn:a.en.title,categoryJa:a.categoryJa,categoryEn:a.categoryEn}));
function header(lang){const ja=lang==='ja';return `<a class="skip-link" href="#main">${ja?'本文へ移動':'Skip to content'}</a><header class="site-header"><div class="header-inner"><a class="brand" href="/${lang}/">Daily <em>Japan</em> News</a><div class="header-actions"><button class="icon-btn" type="button" data-open-search aria-label="${ja?'検索':'Search'}">⌕</button><div class="lang-toggle" aria-label="Language"><button data-lang-btn="ja" class="${ja?'active':''}">JP</button><button data-lang-btn="en" class="${!ja?'active':''}">EN</button></div></div></div></header><div class="ticker"><div class="ticker-inner"><span class="ticker-label">TODAY</span><span class="ticker-item">${ja?'経済・ビジネス・AI・科学・政治外交を、短時間で深く':'Japan’s economy, business, AI, science and diplomacy — fast, clear, deep'}</span><span class="ticker-item">${ja?'更新 14:00 JST':'Updated 14:00 JST'}</span></div></div>`}
function searchPanel(lang){const ja=lang==='ja';return `<div class="search-panel" id="searchPanel" aria-hidden="true"><div class="search-box" role="dialog" aria-modal="true" aria-label="${ja?'記事検索':'Article search'}"><div class="search-top"><input id="searchInput" class="search-input" type="search" autocomplete="off" placeholder="${ja?'企業名・テーマ・キーワードで検索':'Search companies, topics or keywords'}"><button class="close-search" data-close-search>${ja?'閉じる':'Close'}</button></div><div class="search-results" id="searchResults"></div></div></div><script id="search-data" type="application/json">${JSON.stringify(searchData).replace(/</g,'\\u003c')}</script>`}
function footer(lang){const ja=lang==='ja';return `<footer class="footer"><div class="footer-inner"><div><div class="footer-brand">Daily Japan News</div><div>${ja?'日本の重要ニュースを、美しく、速く、深く':'Understand Japan — beautifully, quickly, deeply'}</div></div><div>${ja?'情報源を明示し、一次資料・公的統計・企業公式情報を優先します':'Sources are shown clearly, with priority given to primary and official material'}<br>© 2026 Music Japan LLC</div></div></footer>${searchPanel(lang)}<script src="/assets/app.js" defer></script>`}
function nav(lang,active='All'){const ja=lang==='ja';const cats=[['All',ja?'すべて':'All'],['Economy',ja?'経済':'Economy'],['Business',ja?'ビジネス':'Business'],['AI','AI'],['Science',ja?'科学':'Science'],['Politics',ja?'政治・外交':'Politics']];return `<nav class="nav-strip" aria-label="${ja?'カテゴリ':'Categories'}">${cats.map(([key,label])=>`<button class="chip ${key===active?'active':''}" data-category="${key}">${label}</button>`).join('')}</nav>`}
function doc({lang,title,description,canonical,alternate,body,schema=''}){return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#f6f4ef"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${siteUrl}${canonical}"><link rel="alternate" hreflang="ja" href="${siteUrl}${alternate.ja}"><link rel="alternate" hreflang="en" href="${siteUrl}${alternate.en}"><link rel="alternate" hreflang="x-default" href="${siteUrl}${alternate.ja}"><meta property="og:type" content="website"><meta property="og:site_name" content="Daily Japan News"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${siteUrl}${canonical}"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/assets/styles.css">${schema}</head><body data-lang="${lang}">${header(lang)}${body}${footer(lang)}<button class="back-top" data-back-top aria-label="Back to top">↑</button></body></html>`}
function storyCard(a,lang){const t=a[lang];return `<a class="story-card" data-story-category="${a.category}" href="/${lang}/articles/${a.slug}/"><img src="/assets/${a.image}" alt="" loading="lazy"><div class="story-body"><span class="eyebrow">${lang==='ja'?a.categoryJa:a.categoryEn}</span><h3 class="story-title">${esc(t.title)}</h3><p class="story-dek">${esc(t.dek)}</p><div class="meta-row"><span>${isoDate(a.published,lang)}</span><span>${a.readMinutes} ${lang==='ja'?'分':'min'}</span></div></div></a>`}
function homepage(lang){const ja=lang==='ja';const featured=articles.find(a=>a.featured)||articles[0];const others=articles.filter(a=>a.slug!==featured.slug);const popular=[...articles].sort((a,b)=>b.popularScore-a.popularScore).slice(0,5);const title=ja?'Daily Japan News｜日本の重要ニュースを、速く深く':'Daily Japan News | Japan, explained fast and clearly';const desc=ja?'日本の経済・ビジネス・AI・科学・政治外交を、5つのポイントとデータで短時間に理解するニュースメディア':'A premium bilingual news briefing on Japan’s economy, business, AI, science and diplomacy, built for fast understanding';
const body=`${nav(lang)}<main id="main" class="page-shell"><section class="edition-line"><div><div class="edition-kicker">DAILY EDITION · JAPAN</div><h1 class="edition-title">${ja?'今日の日本を、\n速く深く':'Japan,\nMade Clear'}</h1></div><div class="edition-meta">September 12, 2026<br>Osaka / Tokyo · JST</div></section><section class="hero-grid"><a class="hero-card" href="/${lang}/articles/${featured.slug}/"><img src="/assets/${featured.image}" alt=""><div class="hero-content"><span class="eyebrow">${ja?featured.categoryJa:featured.categoryEn}</span><h2 class="hero-title">${esc(featured[lang].title)}</h2><p class="hero-dek">${esc(featured[lang].dek)}</p><div class="meta-row"><span>${isoDate(featured.published,lang)}</span><span>${featured.readMinutes} ${ja?'分':'min'}</span><span>${ja?'5つのポイント付き':'5 key points'}</span></div></div></a><div class="hero-side">${others.slice(0,2).map(a=>storyCard(a,lang)).join('')}</div></section><div class="layout-two"><div><section class="section"><div class="section-head"><h2 class="section-title">${ja?'最新ニュース':'Latest'}</h2><span class="section-link">${ja?'短時間で理解':'FAST BRIEFING'}</span></div><div class="story-grid">${others.slice(2).concat(others.slice(0,2)).map(a=>storyCard(a,lang)).join('')}</div></section></div><aside class="section"><div class="section-head"><h2 class="section-title">${ja?'よく読まれている':'Popular'}</h2></div><div class="ranking">${popular.map(a=>`<a class="rank-item" href="/${lang}/articles/${a.slug}/"><div><div class="rank-title">${esc(a[lang].title)}</div><div class="rank-meta">${ja?a.categoryJa:a.categoryEn} · ${a.readMinutes}${ja?'分':' min'}</div></div></a>`).join('')}</div></aside></div><section class="section"><div class="section-head"><h2 class="section-title">${ja?'Daily Japan Newsについて':'About Daily Japan News'}</h2></div><div class="story-card"><div class="story-body"><p class="story-dek">${ja?'すべての記事は、冒頭の「この記事のポイント」5項目で要点を先に把握できる設計です。その後、背景・数字・意味を必要な深さまで読めます。日本語と英語の両方で、同じニュースを同じ論点から理解できる媒体を目指します':'Every story begins with five key points, so readers can understand the essentials before deciding how deeply to read. Japanese and English editions follow the same editorial logic.'}</p></div></div></section></main>`;
const schema=`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebSite',name:'Daily Japan News',url:siteUrl+'/',inLanguage:ja?'ja-JP':'en',publisher:{'@type':'Organization',name:'Music Japan LLC'}}).replace(/</g,'\\u003c')}</script>`;
return doc({lang,title,description:desc,canonical:`/${lang}/`,alternate:{ja:'/ja/',en:'/en/'},body,schema});}
function articlePage(a,lang){const ja=lang==='ja',t=a[lang];const pathName=`/${lang}/articles/${a.slug}/`;const body=`<main id="main" class="page-shell"><article class="article-page"><div class="article-breadcrumb"><a href="/${lang}/">Daily Japan News</a> / ${ja?a.categoryJa:a.categoryEn}</div><header class="article-hero"><div class="article-cat">${ja?a.categoryJa:a.categoryEn}</div><h1 class="article-title">${esc(t.title)}</h1><p class="article-dek">${esc(t.dek)}</p><div class="meta-row"><span>${ja?'公開':'Published'} ${isoDate(a.published,lang)}</span><span>${ja?'更新':'Updated'} ${isoDate(a.updated,lang)}</span><span>${a.readMinutes}${ja?'分で読めます':' min read'}</span></div></header><img class="article-image" src="/assets/${a.image}" alt=""><section class="points-box"><div class="points-kicker">QUICK BRIEF</div><h2 class="points-title">${ja?'この記事のポイント':'Five things to know'}</h2><ol class="points-list">${t.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ol></section><div class="article-content">${t.sections.map(s=>`<section><h2>${esc(s.heading)}</h2><p>${esc(s.body)}</p></section>`).join('')}</div><section class="source-box"><h3>${ja?'主な情報源・確認先':'Primary source types'}</h3><ul>${t.sources.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></section><section class="section"><div class="section-head"><h2 class="section-title">${ja?'次に読む':'Read next'}</h2></div><div class="story-grid">${articles.filter(x=>x.slug!==a.slug).slice(0,3).map(x=>storyCard(x,lang)).join('')}</div></section></article></main>`;
const schemaObj={'@context':'https://schema.org','@type':'NewsArticle',headline:t.title,description:t.dek,datePublished:a.published,dateModified:a.updated,inLanguage:ja?'ja-JP':'en',mainEntityOfPage:siteUrl+pathName,image:[siteUrl+'/assets/'+a.image],author:{'@type':'Organization',name:'Daily Japan News'},publisher:{'@type':'Organization',name:'Music Japan LLC'},articleSection:ja?a.categoryJa:a.categoryEn};
const schema=`<meta property="og:type" content="article"><meta property="og:image" content="${siteUrl}/assets/${a.image}"><script type="application/ld+json">${JSON.stringify(schemaObj).replace(/</g,'\\u003c')}</script>`;
return doc({lang,title:`${t.title} | Daily Japan News`,description:t.dek,canonical:pathName,alternate:{ja:`/ja/articles/${a.slug}/`,en:`/en/articles/${a.slug}/`},body,schema});}
function write(rel,content){const p=path.join(dist,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,content)}
write('index.html',`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0; url=/ja/"><title>Daily Japan News</title><meta name="description" content="Daily Japan News"><link rel="canonical" href="${siteUrl}/ja/"></head><body><a href="/ja/">Daily Japan News</a></body></html>`);
for(const lang of ['ja','en']){write(`${lang}/index.html`,homepage(lang));for(const a of articles)write(`${lang}/articles/${a.slug}/index.html`,articlePage(a,lang));}
write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${siteUrl}/sitemap.xml\n`);
const urls=['/ja/','/en/',...articles.flatMap(a=>[`/ja/articles/${a.slug}/`,`/en/articles/${a.slug}/`])];write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${siteUrl}${u}</loc></url>`).join('')}</urlset>`);
write('404.html',`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>404 | Daily Japan News</title><meta name="description" content="Page not found"><link rel="canonical" href="${siteUrl}/404.html"><link rel="stylesheet" href="/assets/styles.css"><main class="page-shell"><div class="empty-state"><h1>404</h1><p>Page not found</p><a href="/ja/">Daily Japan News</a></div></main>`);
console.log(`Built ${urls.length} pages into ${dist}`);
