import { useEffect, useMemo, useState } from 'react';
import { api, auth } from '@appdeploy/client';
import { Activity, AlertCircle, CalendarDays, CheckCircle2, CircleDollarSign, Copy, LogOut, Mail, Plus, RefreshCw, Settings2, Trash2 } from 'lucide-react';

type User={userId:string;email?:string;name?:string};
type Deal={id:string;company:string;amount:number;stage:string;nextAction:string;dueDate:string;createdAt:string;updatedAt:string};
type EventItem={id:string;source:string;title:string;detail:string;occurredAt:string;createdAt:string};
type Dashboard={deals:Deal[];events:EventItem[];integrationConfigured:boolean};
const stages=['新規','商談予定','提案済','受注','失注'];
const yen=(n:number)=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n);
const dt=(v:string)=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})};

export default function App(){
 const [user,setUser]=useState<User|null>(null);const[loading,setLoading]=useState(true);const[data,setData]=useState<Dashboard>({deals:[],events:[],integrationConfigured:false});const[error,setError]=useState('');const[showAdd,setShowAdd]=useState(false);const[saving,setSaving]=useState(false);const[token,setToken]=useState('');const[form,setForm]=useState({company:'',amount:'',stage:'新規',nextAction:'',dueDate:''});
 const load=async()=>{setError('');try{const r=await api.get('/api/dashboard');setData(r.data as Dashboard)}catch{setError('データを読み込めませんでした')}finally{setLoading(false)}};
 useEffect(()=>{(async()=>{if(!auth.isSignedIn()){setLoading(false);return}const u=await auth.getUser();if(u){setUser({userId:u.userId,email:u.email,name:u.name});await load()}else setLoading(false)})()},[]);
 const signIn=async()=>{setError('');try{const r=await auth.signIn();setUser({userId:r.user.userId,email:r.user.email,name:r.user.name});setLoading(true);await load()}catch(e){const code=(e as {code?:string}).code;setError(code==='popup_blocked'?'ポップアップを許可して再度ログインしてください':'ログインを完了できませんでした')}};
 const signOut=async()=>{await auth.signOut();setUser(null);setData({deals:[],events:[],integrationConfigured:false});setToken('')};
 const openDeals=data.deals.filter(d=>!['受注','失注'].includes(d.stage));const pipeline=useMemo(()=>openDeals.reduce((s,d)=>s+d.amount,0),[data.deals]);const won=useMemo(()=>data.deals.filter(d=>d.stage==='受注').reduce((s,d)=>s+d.amount,0),[data.deals]);const overdue=useMemo(()=>data.deals.filter(d=>d.dueDate&&new Date(d.dueDate)<new Date()&&!['受注','失注'].includes(d.stage)).length,[data.deals]);
 const createDeal=async(e:React.FormEvent)=>{e.preventDefault();setError('');const amount=Number(form.amount||0);if(!form.company.trim()||amount<0){setError('会社名と金額を確認してください');return}setSaving(true);try{await api.post('/api/deals',{...form,amount});setForm({company:'',amount:'',stage:'新規',nextAction:'',dueDate:''});setShowAdd(false);await load()}catch{setError('案件を保存できませんでした')}finally{setSaving(false)}};
 const updateDeal=async(d:Deal,patch:Partial<Deal>)=>{setSaving(true);setError('');try{await api.put('/api/deals/'+d.id,{...d,...patch});await load()}catch{setError('案件を更新できませんでした')}finally{setSaving(false)}};
 const deleteDeal=async(id:string)=>{if(!window.confirm('この案件を削除しますか？'))return;setSaving(true);try{await api.delete('/api/deals/'+id);await load()}catch{setError('案件を削除できませんでした')}finally{setSaving(false)}};
 const issueToken=async()=>{setError('');try{const r=await api.post('/api/integration-token');setToken(String(r.data.token||''));await load()}catch{setError('連携キーを発行できませんでした')}};
 const testEvent=async()=>{setError('');try{await api.post('/api/events/test');await load()}catch{setError('受信テストに失敗しました')}};
 const copy=async(v:string)=>{try{await navigator.clipboard.writeText(v)}catch{setError('コピーできませんでした')}};
 if(loading)return <div className='grid min-h-screen place-items-center bg-[#f7f7f4]'><div className='flex items-center gap-3 text-sm font-bold'><RefreshCw className='animate-spin' size={18}/>読み込み中</div></div>;
 if(!user)return <div className='min-h-screen bg-[#f7f7f4] text-[#161815]'><div className='mx-auto flex min-h-screen max-w-lg items-center px-5'><div className='w-full rounded-[28px] border border-black/10 bg-white p-7 shadow-xl shadow-black/5 sm:p-10'><div className='mb-8 grid h-12 w-12 place-items-center rounded-2xl bg-[#161815] text-white'><Activity/></div><p className='text-xs font-black tracking-[.18em] text-black/40'>SALES OPERATIONS</p><h1 className='mt-3 text-4xl font-black tracking-[-.04em]'>営業司令室 30</h1><p className='mt-4 text-sm leading-7 text-black/55'>これはデモ画面ではありません。ログイン後に登録した案件・追客期限・外部連携イベントが実際に保存されます。</p>{error&&<p className='mt-5 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700'>{error}</p>}<button onClick={signIn} className='mt-7 w-full rounded-xl bg-[#161815] px-5 py-3.5 font-bold text-white'>Googleでログインして開始</button><p className='mt-4 text-center text-[11px] leading-5 text-black/35'>顧客ごとにデータを分離して保存します</p></div></div></div>;
 return <div className='min-h-screen bg-[#f7f7f4] text-[#161815]'><header className='border-b border-black/10 bg-white'><div className='mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4'><div className='flex items-center gap-3'><div className='grid h-10 w-10 place-items-center rounded-xl bg-[#161815] text-white'><Activity size={19}/></div><div><b className='block'>営業司令室 30</b><span className='text-[11px] text-black/40'>Production workspace</span></div></div><div className='flex items-center gap-3'><div className='hidden text-right sm:block'><b className='block text-xs'>{user.name||'User'}</b><span className='text-[11px] text-black/40'>{user.email}</span></div><button onClick={signOut} className='rounded-lg border border-black/10 p-2.5' title='ログアウト'><LogOut size={17}/></button></div></div></header><main className='mx-auto max-w-7xl px-5 py-7'>
 {error&&<div className='mb-5 flex items-center gap-2 rounded-xl border border-red-100 bg-red-50 p-3 text-sm font-semibold text-red-700'><AlertCircle size={17}/>{error}</div>}
 <div className='grid gap-3 sm:grid-cols-2 xl:grid-cols-4'><Metric label='オープン見込' value={yen(pipeline)} sub={openDeals.length+'案件'} icon={<CircleDollarSign/>}/><Metric label='受注' value={yen(won)} sub={data.deals.filter(d=>d.stage==='受注').length+'案件'} icon={<CheckCircle2/>}/><Metric label='期限超過' value={String(overdue)} sub='要フォロー' icon={<AlertCircle/>} warn={overdue>0}/><Metric label='外部イベント' value={String(data.events.length)} sub={data.events.length?'受信済み':'未受信'} icon={<Activity/>}/></div>
 <div className='mt-6 grid gap-5 xl:grid-cols-[1fr_360px]'><section className='overflow-hidden rounded-3xl border border-black/10 bg-white'><div className='flex flex-wrap items-center justify-between gap-3 border-b border-black/8 p-5'><div><h2 className='font-black'>案件・追客</h2><p className='mt-1 text-xs text-black/40'>ここに入れたデータが本番保存されます</p></div><button onClick={()=>setShowAdd(v=>!v)} className='flex items-center gap-2 rounded-xl bg-[#161815] px-4 py-2.5 text-sm font-bold text-white'><Plus size={16}/>案件追加</button></div>{showAdd&&<form onSubmit={createDeal} className='grid gap-3 border-b border-black/8 bg-[#fafaf7] p-5 sm:grid-cols-2 lg:grid-cols-3'><Input label='会社名 *' value={form.company} onChange={v=>setForm({...form,company:v})}/><Input label='見込金額' type='number' value={form.amount} onChange={v=>setForm({...form,amount:v})}/><label className='text-xs font-bold'>ステージ<select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})} className='mt-2 w-full rounded-xl border border-black/10 bg-white px-3 py-3 text-sm'>{stages.map(s=><option key={s}>{s}</option>)}</select></label><Input label='次アクション' value={form.nextAction} onChange={v=>setForm({...form,nextAction:v})}/><Input label='期限' type='datetime-local' value={form.dueDate} onChange={v=>setForm({...form,dueDate:v})}/><div className='flex items-end'><button disabled={saving} className='w-full rounded-xl bg-[#e04b2f] px-4 py-3 text-sm font-bold text-white disabled:opacity-50'>{saving?'保存中':'保存'}</button></div></form>}{data.deals.length===0?<Empty title='案件はまだありません' text='「案件追加」から最初の実案件を登録してください'/>:<div>{data.deals.map(d=><div key={d.id} className='grid gap-3 border-b border-black/8 p-5 last:border-0 lg:grid-cols-[1.1fr_130px_145px_1.3fr_120px_40px] lg:items-center'><div><b className='text-sm'>{d.company}</b><p className='mt-1 text-xs text-black/35'>更新 {dt(d.updatedAt)}</p></div><b className='text-sm'>{yen(d.amount)}</b><select disabled={saving} value={d.stage} onChange={e=>updateDeal(d,{stage:e.target.value})} className='rounded-lg border border-black/10 bg-white px-2 py-2 text-xs font-bold'>{stages.map(s=><option key={s}>{s}</option>)}</select><div><p className='text-sm'>{d.nextAction||'次アクション未設定'}</p><p className={'mt-1 text-xs '+(d.dueDate&&new Date(d.dueDate)<new Date()&&!['受注','失注'].includes(d.stage)?'font-bold text-red-600':'text-black/38')}>{d.dueDate?'期限 '+dt(d.dueDate):'期限未設定'}</p></div><button onClick={()=>{const v=window.prompt('次アクションを更新',d.nextAction);if(v!==null)updateDeal(d,{nextAction:v})}} className='rounded-lg border border-black/10 px-3 py-2 text-xs font-bold'>追客更新</button><button onClick={()=>deleteDeal(d.id)} className='p-2 text-black/35 hover:text-red-600' title='削除'><Trash2 size={16}/></button></div>)}</div>}</section>
 <aside className='space-y-5'><section className='rounded-3xl border border-black/10 bg-[#171916] p-5 text-white'><div className='flex items-center justify-between'><div><h2 className='font-black'>営業イベント</h2><p className='mt-1 text-xs text-white/40'>Gmail / Calendar受信履歴</p></div><button onClick={testEvent} className='rounded-lg bg-white/10 px-3 py-2 text-xs font-bold'>受信テスト</button></div>{data.events.length===0?<p className='mt-6 rounded-2xl bg-white/6 p-4 text-sm leading-6 text-white/50'>まだ外部イベントを受信していません。下の「連携設定」でMakeから接続できます。</p>:<div className='mt-4 space-y-2'>{data.events.slice(0,12).map(ev=><div key={ev.id} className='rounded-2xl bg-white/7 p-3'><div className='flex items-center gap-2 text-[10px] font-bold uppercase text-white/40'>{ev.source==='gmail'?<Mail size={12}/>:ev.source==='calendar'?<CalendarDays size={12}/>:<Activity size={12}/>} {ev.source} · {dt(ev.occurredAt||ev.createdAt)}</div><b className='mt-1.5 block text-sm'>{ev.title}</b>{ev.detail&&<p className='mt-1 line-clamp-2 text-xs leading-5 text-white/50'>{ev.detail}</p>}</div>)}</div>}</section><section className='rounded-3xl border border-black/10 bg-white p-5'><div className='flex items-center gap-2'><Settings2 size={17}/><h2 className='font-black'>連携設定</h2></div><p className='mt-2 text-xs leading-5 text-black/45'>Make等の実行基盤からこのワークスペースへイベントをPOSTします。キーは再表示されません。</p><div className='mt-4 flex items-center justify-between rounded-xl bg-[#f5f5f1] p-3 text-xs'><span>連携キー</span><b>{data.integrationConfigured?'発行済み':'未発行'}</b></div><button onClick={issueToken} className='mt-3 w-full rounded-xl border border-black/12 px-4 py-2.5 text-sm font-bold'>{data.integrationConfigured?'連携キーを再発行':'連携キーを発行'}</button>{token&&<div className='mt-4 space-y-3 rounded-2xl bg-amber-50 p-4 text-xs'><p className='font-black text-amber-900'>このキーは今だけ表示</p><CodeRow label='Endpoint' value={window.location.origin+'/api/ingest'} onCopy={copy}/><CodeRow label='X-User-Id' value={user.userId} onCopy={copy}/><CodeRow label='X-Ingest-Token' value={token} onCopy={copy}/><p className='leading-5 text-amber-900/60'>MakeのHTTP POSTヘッダーへ設定してください。本文は source / title / detail / occurredAt のJSON。</p></div>}</section></aside></div></main></div>;
}
function Metric({label,value,sub,icon,warn=false}:{label:string;value:string;sub:string;icon:React.ReactNode;warn?:boolean}){return <div className='rounded-2xl border border-black/10 bg-white p-5'><div className='flex items-center justify-between text-xs text-black/40'><span>{label}</span><span className={warn?'text-red-600':''}>{icon}</span></div><b className={'mt-2 block text-2xl '+(warn?'text-red-600':'')}>{value}</b><span className='mt-1 block text-xs text-black/35'>{sub}</span></div>}
function Empty({title,text}:{title:string;text:string}){return <div className='p-12 text-center'><b className='text-sm'>{title}</b><p className='mt-2 text-xs text-black/40'>{text}</p></div>}
function Input({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className='text-xs font-bold'>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className='mt-2 w-full rounded-xl border border-black/10 bg-white px-3 py-3 text-sm font-normal outline-none focus:border-black/40'/></label>}
function CodeRow({label,value,onCopy}:{label:string;value:string;onCopy:(v:string)=>void}){return <div><span className='block text-[10px] font-bold text-black/40'>{label}</span><div className='mt-1 flex items-center gap-2 rounded-lg bg-white p-2'><code className='min-w-0 flex-1 break-all text-[10px]'>{value}</code><button onClick={()=>onCopy(value)} className='shrink-0 rounded p-1 text-black/45'><Copy size={13}/></button></div></div>}