import { useMemo, useState } from 'react';
import { api } from '@appdeploy/client';
import { ArrowRight, BellRing, CalendarDays, Check, ChevronRight, CircleDollarSign, Database, Gauge, Mail, MessageSquare, ShieldCheck, Sparkles, Users, X } from 'lucide-react';

type Deal = { company:string; stage:string; amount:number; next:string; overdue?:boolean };
const deals: Deal[] = [
  {company:'株式会社サンプルA',stage:'提案済',amount:180000,next:'9/1 見積フォロー',overdue:true},
  {company:'合同会社サンプルB',stage:'商談予定',amount:90000,next:'9/2 14:00 商談'},
  {company:'株式会社サンプルC',stage:'ヒアリング',amount:120000,next:'9/3 課題整理を送付'},
  {company:'株式会社サンプルD',stage:'受注',amount:300000,next:'9/5 キックオフ'}
];
const fmt=(n:number)=>new Intl.NumberFormat('ja-JP').format(n);

function App(){
 const [view,setView]=useState<'lp'|'demo'>('lp');
 const [form,setForm]=useState({company:'',name:'',email:'',note:''});
 const [sending,setSending]=useState(false); const [sent,setSent]=useState(false); const [err,setErr]=useState('');
 const pipeline=useMemo(()=>deals.reduce((s,d)=>s+d.amount,0),[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setErr('');setSent(false);if(!form.company.trim()||!form.name.trim()||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(form.email)){setErr('会社名・お名前・正しいメールアドレスを入力してください');return;}setSending(true);try{await api.post('/api/inquiries',form);setSent(true);setForm({company:'',name:'',email:'',note:''});}catch{setErr('送信できませんでした。時間をおいて再度お試しください');}finally{setSending(false)}};
 return <div className='min-h-screen bg-[#f7f7f4] text-[#161815]'>
  <header className='sticky top-0 z-40 border-b border-black/10 bg-[#f7f7f4]/95 backdrop-blur'><div className='mx-auto flex max-w-6xl items-center justify-between px-5 py-4'><button onClick={()=>setView('lp')} className='flex items-center gap-2 text-left'><div className='grid h-9 w-9 place-items-center rounded-xl bg-[#161815] text-white'><Gauge size={18}/></div><div><b className='block text-sm'>営業司令室 30</b><span className='text-[11px] text-black/45'>Managed Sales Ops</span></div></button><div className='flex items-center gap-2'><button onClick={()=>setView('demo')} className='hidden rounded-full border border-black/15 px-4 py-2 text-sm font-semibold sm:block'>デモを見る</button><a href='#contact' onClick={()=>setView('lp')} className='rounded-full bg-[#161815] px-4 py-2 text-sm font-semibold text-white'>相談する</a></div></div></header>
  {view==='demo'?<Demo pipeline={pipeline} onBack={()=>setView('lp')}/>:<main>
   <section className='mx-auto grid max-w-6xl gap-10 px-5 pb-16 pt-14 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:pt-24'><div><div className='mb-5 inline-flex items-center gap-2 rounded-full border border-black/10 bg-white px-3 py-1.5 text-xs font-semibold'><Sparkles size={14}/> 営業担当を増やす前に、漏れを止める</div><h1 className='max-w-3xl text-[42px] font-black leading-[1.06] tracking-[-.045em] sm:text-6xl'>メール、予定、Slack。<br/>散らばった営業を<br/><span className='text-[#e04b2f]'>1つの司令室へ。</span></h1><p className='mt-6 max-w-2xl text-base leading-8 text-black/62 sm:text-lg'>2〜20名のB2B企業向け。Gmail・Google Calendar・Slackをつなぎ、追客漏れ、次アクション忘れ、見込の見えなさを減らす「構築＋運用」サービスです。</p><div className='mt-8 flex flex-wrap gap-3'><button onClick={()=>setView('demo')} className='flex items-center gap-2 rounded-full bg-[#161815] px-6 py-3.5 font-bold text-white'>実際の画面を見る <ArrowRight size={18}/></button><a href='#price' className='rounded-full border border-black/15 bg-white px-6 py-3.5 font-bold'>月額3万円の範囲</a></div><p className='mt-4 text-xs text-black/45'>※デモ画面の会社名・金額は架空データです。実績として表示していません。</p></div><div className='rounded-[28px] border border-black/10 bg-[#171916] p-4 shadow-2xl shadow-black/15'><div className='mb-3 flex items-center justify-between px-2 text-xs text-white/55'><span>営業司令室 / 今日</span><span className='rounded-full bg-emerald-400/15 px-2 py-1 text-emerald-300'>運用中</span></div><div className='grid gap-3 sm:grid-cols-2'><Metric label='今月見込' value='¥690,000' icon={<CircleDollarSign/>}/><Metric label='追客遅延' value='1件' icon={<BellRing/>}/></div><div className='mt-3 rounded-2xl bg-white p-4'><div className='mb-4 flex items-center justify-between'><b className='text-sm'>次に動く案件</b><span className='text-xs text-black/40'>自動集約イメージ</span></div>{deals.slice(0,3).map(d=><div key={d.company} className='flex items-center gap-3 border-t border-black/8 py-3 first:border-0'><div className={'h-2.5 w-2.5 rounded-full '+(d.overdue?'bg-[#e04b2f]':'bg-emerald-500')}/><div className='min-w-0 flex-1'><b className='block truncate text-sm'>{d.company}</b><span className='text-xs text-black/45'>{d.next}</span></div><span className='text-sm font-bold'>¥{fmt(d.amount)}</span></div>)}</div></div></section>
   <section className='border-y border-black/10 bg-white'><div className='mx-auto grid max-w-6xl gap-4 px-5 py-10 sm:grid-cols-3'><Mini icon={<Mail/>} title='Gmail' text='指定条件の営業メールを監視。重要メールをSlackへ'/><Mini icon={<CalendarDays/>} title='Calendar' text='商談予定とフォロー期限を集約。次アクションを見える化'/><Mini icon={<MessageSquare/>} title='Slack' text='営業通知を1チャンネルへ。日次で見る場所を固定'/></div></section>
   <section className='mx-auto max-w-6xl px-5 py-20'><div className='mb-10 max-w-2xl'><p className='text-sm font-bold text-[#e04b2f]'>WHAT YOU BUY</p><h2 className='mt-2 text-3xl font-black tracking-tight sm:text-4xl'>SaaSをもう1個増やすサービスではない</h2><p className='mt-4 leading-7 text-black/55'>ツールを渡して終わりではなく、最初の連携設計と月次の運用調整まで含めます。</p></div><div className='grid gap-4 md:grid-cols-2'><Feature num='01' title='営業通知の一本化' text='Gmail・Calendarの指定条件をもとに、Slackの営業チャンネルへ必要情報を集約'/><Feature num='02' title='追客漏れアラート' text='次アクション期限を持たせ、期限超過を一覧化。勝手な自動送信はしません'/><Feature num='03' title='営業KPIボード' text='商談数・見込金額・受注・次アクションを1画面で確認できる状態を構築'/><Feature num='04' title='月1回の運用調整' text='通知条件、項目、ルールの軽微な変更を月1回まで反映'/></div></section>
   <section id='price' className='bg-[#171916] text-white'><div className='mx-auto grid max-w-6xl gap-10 px-5 py-20 lg:grid-cols-2'><div><p className='text-sm font-bold text-[#ff7a61]'>PRICE</p><h2 className='mt-2 text-4xl font-black'>月額 30,000円<span className='text-base font-normal text-white/45'>（税別）</span></h2><p className='mt-5 leading-7 text-white/58'>初期費用 50,000円（税別）。初回ヒアリング、連携設定、Slack司令室、KPI初期設計を含みます。</p><div className='mt-8 space-y-3'>{['Google Workspace 1組織','Slack 1ワークスペース・1営業チャンネル','自動化フロー 最大5本','KPIボード 1つ','月1回・30分の運用レビュー','軽微なルール変更 月1回'].map(x=><div key={x} className='flex gap-3 text-sm'><Check className='mt-0.5 text-emerald-400' size={17}/><span>{x}</span></div>)}</div></div><div className='rounded-3xl bg-white p-6 text-[#171916]'><b>対応範囲外</b><div className='mt-4 space-y-3 text-sm leading-6 text-black/58'>{['LinkedInの規約に反する自動DM・大量送信','メールの無断自動返信・契約判断','CRM全体の移行・大規模データクレンジング','独自基幹システムの開発','24時間有人監視・即時障害復旧保証','API従量費・有料SaaS利用料の立替'].map(x=><div key={x} className='flex gap-2'><X className='mt-1 shrink-0 text-[#e04b2f]' size={15}/><span>{x}</span></div>)}</div><div className='mt-6 rounded-2xl bg-[#f4f3ef] p-4 text-xs leading-5 text-black/55'><b className='text-black'>データ方針</b><br/>顧客データを当社の学習データとして二次利用しません。解約時は契約で定めた期間内に当社管理分を削除し、顧客所有アカウント側のデータは顧客側で保持します。</div></div></div></section>
   <section className='mx-auto max-w-6xl px-5 py-20'><div className='grid gap-8 lg:grid-cols-[.8fr_1.2fr]'><div><p className='text-sm font-bold text-[#e04b2f]'>ONBOARDING</p><h2 className='mt-2 text-3xl font-black'>導入は4段階</h2></div><div className='space-y-3'>{[['1','30分ヒアリング','営業フロー、追客条件、利用ツールを確認'],['2','権限接続','顧客自身のGoogle / SlackアカウントでOAuth接続'],['3','初期構築','通知・KPI・次アクションのルールを設定'],['4','テスト運用','テストデータで確認後、本番切替']].map(s=><div key={s[0]} className='grid grid-cols-[44px_1fr] gap-3 rounded-2xl border border-black/10 bg-white p-4'><div className='grid h-10 w-10 place-items-center rounded-full bg-[#171916] font-bold text-white'>{s[0]}</div><div><b>{s[1]}</b><p className='mt-1 text-sm text-black/50'>{s[2]}</p></div></div>)}</div></div></section>
   <section id='contact' className='border-t border-black/10 bg-white'><div className='mx-auto grid max-w-6xl gap-10 px-5 py-20 lg:grid-cols-2'><div><p className='text-sm font-bold text-[#e04b2f]'>CONTACT</p><h2 className='mt-2 text-4xl font-black'>まず、今の営業導線を<br/>30分で見ます</h2><p className='mt-5 max-w-lg leading-7 text-black/55'>販売前提でなくても大丈夫です。Gmail・Calendar・Slackのどこで情報が止まっているかを確認し、3万円で収まるかを先に判断します。</p><div className='mt-8 grid gap-3 text-sm'><div className='flex gap-3'><ShieldCheck size={18}/><span>勝手なメール送信なし</span></div><div className='flex gap-3'><Database size={18}/><span>顧客データの学習利用なし</span></div><div className='flex gap-3'><Users size={18}/><span>人の確認が必要な工程は残す</span></div></div></div><form onSubmit={submit} className='rounded-3xl border border-black/10 bg-[#f7f7f4] p-6'><div className='grid gap-4 sm:grid-cols-2'><Field label='会社名 *' value={form.company} onChange={v=>setForm({...form,company:v})}/><Field label='お名前 *' value={form.name} onChange={v=>setForm({...form,name:v})}/></div><div className='mt-4'><Field label='メールアドレス *' type='email' value={form.email} onChange={v=>setForm({...form,email:v})}/></div><label className='mt-4 block text-sm font-bold'>今困っていること<textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} className='mt-2 min-h-28 w-full rounded-xl border border-black/10 bg-white px-3 py-3 font-normal outline-none focus:border-black/40' placeholder='例：商談後の追客が漏れる、見込がスプレッドシートに散らばる'/></label>{err&&<p className='mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700'>{err}</p>}{sent&&<p className='mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700'>送信しました。お問い合わせを受け付けました。</p>}<button disabled={sending} className='mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#171916] px-5 py-3.5 font-bold text-white disabled:opacity-50'>{sending?'送信中':'30分相談を申し込む'} <ChevronRight size={17}/></button><p className='mt-3 text-center text-[11px] text-black/40'>送信内容はお問い合わせ対応のために保存されます。</p></form></div></section>
  </main>}
  <footer className='border-t border-black/10 px-5 py-8 text-center text-xs text-black/40'>営業司令室 30 — Demo / Product MVP</footer>
 </div>
}
function Metric({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className='rounded-2xl bg-[#242724] p-4 text-white'><div className='flex items-center justify-between text-xs text-white/45'><span>{label}</span><span className='[&>svg]:h-4 [&>svg]:w-4'>{icon}</span></div><b className='mt-3 block text-2xl'>{value}</b></div>}
function Mini({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className='rounded-2xl border border-black/10 bg-[#fafaf8] p-5'><div className='mb-4 grid h-10 w-10 place-items-center rounded-xl bg-[#171916] text-white [&>svg]:h-5 [&>svg]:w-5'>{icon}</div><b>{title}</b><p className='mt-2 text-sm leading-6 text-black/50'>{text}</p></div>}
function Feature({num,title,text}:{num:string;title:string;text:string}){return <div className='rounded-3xl border border-black/10 bg-white p-6'><span className='text-xs font-black text-[#e04b2f]'>{num}</span><h3 className='mt-3 text-xl font-black'>{title}</h3><p className='mt-2 text-sm leading-6 text-black/52'>{text}</p></div>}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className='block text-sm font-bold'>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className='mt-2 w-full rounded-xl border border-black/10 bg-white px-3 py-3 font-normal outline-none focus:border-black/40'/></label>}
function Demo({pipeline,onBack}:{pipeline:number;onBack:()=>void}){const [filter,setFilter]=useState('全件');const shown=filter==='全件'?deals:deals.filter(d=>d.stage===filter);return <main className='mx-auto max-w-6xl px-5 py-8'><div className='mb-6 flex flex-wrap items-center justify-between gap-3'><div><button onClick={onBack} className='mb-2 text-xs font-bold text-black/45'>← LPに戻る</button><h1 className='text-2xl font-black'>営業KPIデモ</h1><p className='mt-1 text-xs text-black/45'>すべて架空データ。操作イメージ確認用です。</p></div><div className='rounded-full bg-amber-100 px-3 py-1.5 text-xs font-bold text-amber-800'>DEMO DATA</div></div><div className='grid gap-3 sm:grid-cols-2 lg:grid-cols-4'><DashCard label='パイプライン' value={'¥'+fmt(pipeline)} sub='4案件'/><DashCard label='今月受注' value='¥300,000' sub='1件'/><DashCard label='商談予定' value='3件' sub='次回 9/2'/><DashCard label='追客遅延' value='1件' sub='要対応' warn/></div><div className='mt-6 grid gap-5 lg:grid-cols-[1fr_330px]'><div className='overflow-hidden rounded-3xl border border-black/10 bg-white'><div className='flex flex-wrap items-center justify-between gap-3 border-b border-black/8 p-5'><b>案件一覧</b><div className='flex gap-2'>{['全件','提案済','商談予定','受注'].map(x=><button key={x} onClick={()=>setFilter(x)} className={'rounded-full px-3 py-1.5 text-xs font-bold '+(filter===x?'bg-[#171916] text-white':'bg-black/5')}>{x}</button>)}</div></div><div>{shown.map(d=><div key={d.company} className='grid gap-2 border-b border-black/8 p-5 last:border-0 sm:grid-cols-[1fr_110px_110px_1fr] sm:items-center'><div><b className='text-sm'>{d.company}</b><p className='mt-1 text-xs text-black/40'>{d.stage}</p></div><b className='text-sm'>¥{fmt(d.amount)}</b><span className={'w-fit rounded-full px-2 py-1 text-[11px] font-bold '+(d.overdue?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700')}>{d.overdue?'期限超過':'正常'}</span><span className='text-xs text-black/55'>{d.next}</span></div>)}</div></div><div className='space-y-4'><div className='rounded-3xl border border-black/10 bg-[#171916] p-5 text-white'><div className='flex items-center gap-2'><BellRing size={17}/><b>今日の通知例</b></div><div className='mt-4 space-y-3 text-sm'><Notice time='09:00' text='本日14:00 商談：サンプルB'/><Notice time='11:30' text='サンプルAの追客期限が超過'/><Notice time='17:00' text='今日の見込 ¥690,000'/></div></div><div className='rounded-3xl border border-black/10 bg-white p-5'><b>本番で接続するもの</b><div className='mt-4 space-y-3 text-sm'><Connect icon={<Mail/>} name='Gmail' status='OAuth'/><Connect icon={<CalendarDays/>} name='Google Calendar' status='OAuth'/><Connect icon={<MessageSquare/>} name='Slack' status='OAuth'/></div><p className='mt-4 text-[11px] leading-5 text-black/40'>この公開デモ自体は各サービスへ接続していません。顧客導入時に本人権限で接続します。</p></div></div></div></main>}
function DashCard({label,value,sub,warn=false}:{label:string;value:string;sub:string;warn?:boolean}){return <div className='rounded-2xl border border-black/10 bg-white p-5'><span className='text-xs text-black/42'>{label}</span><b className={'mt-2 block text-2xl '+(warn?'text-[#e04b2f]':'')}>{value}</b><span className='mt-1 block text-xs text-black/38'>{sub}</span></div>}
function Notice({time,text}:{time:string;text:string}){return <div className='rounded-xl bg-white/7 p-3'><span className='text-[10px] text-white/35'>{time}</span><p className='mt-1 text-xs leading-5 text-white/82'>{text}</p></div>}
function Connect({icon,name,status}:{icon:React.ReactNode;name:string;status:string}){return <div className='flex items-center gap-3'><span className='[&>svg]:h-4 [&>svg]:w-4'>{icon}</span><span className='flex-1'>{name}</span><span className='rounded-full bg-black/5 px-2 py-1 text-[10px] font-bold'>{status}</span></div>}
export default App;