import { useEffect,useMemo,useState } from 'react';
import { api,auth } from '@appdeploy/client';
import { AlertTriangle,Brain,CheckCircle2,CircleDollarSign,Copy,Flame,LogOut,Mail,Plus,RefreshCw,Sparkles,Trash2,XCircle } from 'lucide-react';
type User={userId:string;email?:string;name?:string};
type Deal={id:string;company:string;contact?:string;email?:string;amount:number;stage:string;nextAction:string;dueDate:string;lastContactAt?:string;notes?:string;updatedAt:string;recoveryScore?:number;recoveryReason?:string;recoveryAction?:string;recoveryDraft?:string;lastOutcome?:string};
type EventItem={id:string;source:string;title:string;detail:string;occurredAt:string};
type Metrics={todayAmount:number;atRisk:number;revivedPipeline:number;learningCount:number};
type Dashboard={deals:Deal[];events:EventItem[];integrationConfigured:boolean;metrics:Metrics};
const stages=['新規','商談予定','提案済','休眠','受注','失注'];
const empty:Dashboard={deals:[],events:[],integrationConfigured:false,metrics:{todayAmount:0,atRisk:0,revivedPipeline:0,learningCount:0}};
const yen=(n:number)=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n||0);
const dt=(v?:string)=>{if(!v)return '未設定';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})};
export default function App(){
 const[user,setUser]=useState<User|null>(null);const[data,setData]=useState<Dashboard>(empty);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[showAdd,setShowAdd]=useState(false);const[showImport,setShowImport]=useState(false);const[importText,setImportText]=useState('');const[importResult,setImportResult]=useState('');const[token,setToken]=useState('');
 const[form,setForm]=useState({company:'',contact:'',email:'',amount:'',stage:'休眠',lastContactAt:'',dueDate:'',notes:''});
 const load=async()=>{setError('');try{const r=await api.get('/api/dashboard');setData(r.data as Dashboard)}catch{setError('データを読み込めませんでした')}finally{setLoading(false)}};
 useEffect(()=>{(async()=>{if(!auth.isSignedIn()){setLoading(false);return}const u=await auth.getUser();if(u){setUser({userId:u.userId,email:u.email,name:u.name});await load()}else setLoading(false)})()},[]);
 const signIn=async()=>{try{const r=await auth.signIn();setUser({userId:r.user.userId,email:r.user.email,name:r.user.name});setLoading(true);await load()}catch(e){const c=(e as{code?:string}).code;setError(c==='popup_blocked'?'ポップアップを許可してください':'ログインできませんでした')}};
 const signOut=async()=>{await auth.signOut();setUser(null);setData(empty);setToken('')};
 const queue=useMemo(()=>data.deals.filter(d=>!['受注','失注'].includes(d.stage)).slice(0,12),[data.deals]);
 const createDeal=async(e:React.FormEvent)=>{e.preventDefault();const amount=Number(form.amount||0);if(!form.company.trim()||amount<0){setError('会社名と金額を確認してください');return}setBusy(true);try{await api.post('/api/deals',{...form,amount});setForm({company:'',contact:'',email:'',amount:'',stage:'休眠',lastContactAt:'',dueDate:'',notes:''});setShowAdd(false);await load()}catch{setError('案件を保存できませんでした')}finally{setBusy(false)}};const importDeals=async()=>{const lines=importText.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);const rows=lines.map((line,i)=>{const p=line.split(line.includes('\t')?'\t':',').map(v=>v.trim());if(i===0&&/会社|company/i.test(p[0]||''))return null;return{company:p[0]||'',contact:p[1]||'',email:p[2]||'',amount:Number((p[3]||'0').replace(/[^0-9.-]/g,''))||0,stage:stages.includes(p[4]||'')?p[4]:'休眠',lastContactAt:p[5]||'',notes:p.slice(6).join(' ')}}).filter(Boolean);if(!rows.length){setError('貼り付けデータを確認してください');return}setBusy(true);setImportResult('');try{const r=await api.post('/api/deals/import',{rows});setImportResult(`${r.data.added||0}件追加 / ${r.data.skipped||0}件スキップ`);setImportText('');await load()}catch{setError('一括追加に失敗しました')}finally{setBusy(false)}};
 const scan=async()=>{setBusy(true);setError('');try{await api.post('/api/recovery/scan');await load()}catch{setError('AIスキャンに失敗しました。少し内容を増やして再実行してください')}finally{setBusy(false)}};
 const outcome=async(d:Deal,value:'contacted'|'revived'|'lost'|'snoozed')=>{if(value==='lost'&&!window.confirm(d.company+' を失注にしますか？'))return;setBusy(true);try{await api.post('/api/deals/'+d.id+'/outcome',{outcome:value});await load()}catch{setError('結果を保存できませんでした')}finally{setBusy(false)}};
 const updateStage=async(d:Deal,stage:string)=>{setBusy(true);try{await api.put('/api/deals/'+d.id,{...d,stage});await load()}catch{setError('ステージを更新できませんでした')}finally{setBusy(false)}};
 const remove=async(d:Deal)=>{if(!window.confirm(d.company+' を削除しますか？'))return;setBusy(true);try{await api.delete('/api/deals/'+d.id);await load()}catch{setError('削除できませんでした')}finally{setBusy(false)}};
 const issueToken=async()=>{try{const r=await api.post('/api/integration-token');setToken(String(r.data.token||''));await load()}catch{setError('連携キーを発行できませんでした')}};
 const testEvent=async()=>{try{await api.post('/api/events/test');await load()}catch{setError('受信テストに失敗しました')}};
 const copy=async(v:string)=>{try{await navigator.clipboard.writeText(v)}catch{setError('コピーできませんでした')}};
 if(loading)return <div className='grid min-h-screen place-items-center bg-[#f6f6f2]'><RefreshCw className='animate-spin'/></div>;
 if(!user)return <div className='min-h-screen bg-[#f6f6f2] px-5 text-[#171816]'><div className='mx-auto flex min-h-screen max-w-md items-center'><div className='w-full rounded-[28px] border border-black/10 bg-white p-8 shadow-xl shadow-black/5'><div className='mb-6 grid h-12 w-12 place-items-center rounded-2xl bg-[#171816] text-white'><Flame/></div><p className='text-xs font-black tracking-[.18em] text-black/35'>REVENUE RECOVERY</p><h1 className='mt-2 text-3xl font-black tracking-[-.04em]'>取りこぼした売上を拾う</h1><p className='mt-4 text-sm leading-7 text-black/55'>案件を管理するためのCRMではありません。止まった商談を見つけ、追う順番と次の一手を出すための実働ツールです。</p>{error&&<p className='mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700'>{error}</p>}<button onClick={signIn} className='mt-6 w-full rounded-xl bg-[#171816] px-5 py-3.5 font-bold text-white'>Googleでログイン</button></div></div></div>;
 return <div className='min-h-screen bg-[#f6f6f2] text-[#171816]'><header className='border-b border-black/10 bg-white'><div className='mx-auto flex max-w-7xl items-center justify-between px-5 py-4'><div className='flex items-center gap-3'><div className='grid h-10 w-10 place-items-center rounded-xl bg-[#171816] text-white'><Flame size={18}/></div><div><b className='block'>Revenue Recovery AI</b><span className='text-[11px] text-black/40'>止まった売上を、今日の行動に戻す</span></div></div><button onClick={signOut} className='rounded-lg border border-black/10 p-2.5'><LogOut size={17}/></button></div></header><main className='mx-auto max-w-7xl px-5 py-7'>
 {error&&<div className='mb-5 flex items-center gap-2 rounded-xl border border-red-100 bg-red-50 p-3 text-sm font-bold text-red-700'><AlertTriangle size={17}/>{error}</div>}
 <div className='grid gap-3 sm:grid-cols-2 xl:grid-cols-4'><Metric label='今日追う見込額' value={yen(data.metrics.todayAmount)} sub='上位5案件' icon={<CircleDollarSign/>}/><Metric label='危険案件' value={String(data.metrics.atRisk)} sub='回収スコア60以上' icon={<AlertTriangle/>}/><Metric label='復活見込額' value={yen(data.metrics.revivedPipeline)} sub='復活判定した案件' icon={<CheckCircle2/>}/><Metric label='学習ログ' value={String(data.metrics.learningCount)} sub='結果を次回判断へ反映' icon={<Brain/>}/></div>
 <div className='mt-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-black/10 bg-[#171816] p-4 text-white'><div><b className='text-sm'>AIに任せるのは「誰を追うか」と「何を送るか」</b><p className='mt-1 text-xs text-white/45'>成功した追客文と復活結果を次のスキャンに再利用します</p></div><button disabled={busy||queue.length===0} onClick={scan} className='flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-black text-black disabled:opacity-40'><Sparkles size={16}/>{busy?'処理中':'AIで回収候補を更新'}</button></div>
 <div className='mt-5 grid gap-5 xl:grid-cols-[1fr_340px]'><section className='overflow-hidden rounded-3xl border border-black/10 bg-white'><div className='flex items-center justify-between border-b border-black/8 p-5'><div><h2 className='font-black'>今日の回収キュー</h2><p className='mt-1 text-xs text-black/40'>金額・放置日数・ステージ・過去の復活率から自動順位付け</p></div><div className='flex gap-2'><button onClick={()=>setShowImport(v=>!v)} className='rounded-xl border border-black/10 px-3 py-2 text-xs font-bold'>まとめて追加</button><button onClick={()=>setShowAdd(v=>!v)} className='flex items-center gap-2 rounded-xl border border-black/10 px-3 py-2 text-xs font-bold'><Plus size={15}/>1件追加</button></div></div>
 {showImport&&<div className='border-b border-black/8 bg-[#fafaf7] p-5'><div className='flex flex-wrap items-center justify-between gap-3'><div><b className='text-sm'>過去案件を貼り付け</b><p className='mt-1 text-xs text-black/40'>1行1案件：会社名 / 担当者 / メール / 金額 / 状態 / 最終接触 / メモ。タブ区切りかCSV。</p></div><button disabled={busy||!importText.trim()} onClick={importDeals} className='rounded-xl bg-[#171816] px-4 py-2.5 text-xs font-black text-white disabled:opacity-40'>回収キューへ追加</button></div><textarea value={importText} onChange={e=>setImportText(e.target.value)} className='mt-3 min-h-36 w-full rounded-xl border border-black/10 bg-white p-3 font-mono text-xs leading-6' placeholder={'株式会社ABC\t田中様\ttanaka@example.com\t300000\t休眠\t2026-07-01\t見積送付後に停止\n株式会社XYZ\t佐藤様\t\t150000\t提案済\t2026-08-01\t再提案余地あり'}/>{importResult&&<p className='mt-2 text-xs font-bold text-emerald-700'>{importResult}</p>}</div>}{showAdd&&<form onSubmit={createDeal} className='grid gap-3 border-b border-black/8 bg-[#fafaf7] p-5 sm:grid-cols-2 lg:grid-cols-3'><Input label='会社名 *' value={form.company} onChange={v=>setForm({...form,company:v})}/><Input label='担当者' value={form.contact} onChange={v=>setForm({...form,contact:v})}/><Input label='メール' type='email' value={form.email} onChange={v=>setForm({...form,email:v})}/><Input label='見込金額' type='number' value={form.amount} onChange={v=>setForm({...form,amount:v})}/><label className='text-xs font-bold'>状態<select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})} className='mt-2 w-full rounded-xl border border-black/10 bg-white px-3 py-3 text-sm'>{stages.map(s=><option key={s}>{s}</option>)}</select></label><Input label='最終接触' type='datetime-local' value={form.lastContactAt} onChange={v=>setForm({...form,lastContactAt:v})}/><Input label='次回期限' type='datetime-local' value={form.dueDate} onChange={v=>setForm({...form,dueDate:v})}/><label className='text-xs font-bold sm:col-span-2'>メモ<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className='mt-2 min-h-20 w-full rounded-xl border border-black/10 bg-white px-3 py-3 text-sm' placeholder='相手の課題、前回の会話、止まった理由'/></label><div className='flex items-end'><button disabled={busy} className='w-full rounded-xl bg-[#e24b2d] px-4 py-3 text-sm font-bold text-white'>保存</button></div></form>}
 {queue.length===0?<Empty/>:<div>{queue.map((d,i)=><div key={d.id} className='border-b border-black/8 p-5 last:border-0'><div className='flex flex-wrap items-start justify-between gap-4'><div className='flex min-w-0 gap-3'><div className={'grid h-12 w-12 shrink-0 place-items-center rounded-2xl text-sm font-black '+((d.recoveryScore||0)>=70?'bg-red-50 text-red-600':(d.recoveryScore||0)>=50?'bg-amber-50 text-amber-700':'bg-black/5 text-black/55')}>{d.recoveryScore||0}</div><div className='min-w-0'><div className='flex flex-wrap items-center gap-2'><span className='text-[10px] font-black text-black/30'>#{i+1}</span><b>{d.company}</b>{d.contact&&<span className='text-xs text-black/40'>{d.contact}</span>}</div><b className='mt-1 block text-lg'>{yen(d.amount)}</b><p className='mt-1 text-xs text-black/40'>最終接触 {dt(d.lastContactAt)} · {d.stage}</p></div></div><div className='flex gap-2'><button disabled={busy} onClick={()=>outcome(d,'revived')} className='rounded-lg bg-emerald-50 px-3 py-2 text-xs font-black text-emerald-700'>復活</button><button disabled={busy} onClick={()=>outcome(d,'contacted')} className='rounded-lg bg-black px-3 py-2 text-xs font-black text-white'>追客済み</button><button disabled={busy} onClick={()=>outcome(d,'lost')} className='rounded-lg border border-black/10 px-3 py-2 text-xs font-bold text-black/45'>失注</button></div></div><div className='mt-4 grid gap-3 lg:grid-cols-2'><div className='rounded-2xl bg-[#f6f6f2] p-4'><span className='text-[10px] font-black tracking-wider text-black/35'>なぜ今追うか</span><p className='mt-2 text-sm font-semibold leading-6'>{d.recoveryReason||'放置期間・金額・ステージから回収優先度を計算しています'}</p><span className='mt-3 block text-[10px] font-black tracking-wider text-black/35'>次の一手</span><p className='mt-2 text-sm leading-6'>{d.recoveryAction||d.nextAction||'AIスキャンで具体化'}</p></div><div className='rounded-2xl border border-black/10 p-4'><div className='flex items-center justify-between'><span className='text-[10px] font-black tracking-wider text-black/35'>送信ドラフト</span>{d.recoveryDraft&&<button onClick={()=>copy(d.recoveryDraft||'')} className='flex items-center gap-1 text-xs font-bold'><Copy size={13}/>コピー</button>}</div><p className='mt-2 whitespace-pre-wrap text-sm leading-6 text-black/70'>{d.recoveryDraft||'AIスキャン後、前回文脈に合わせた短い追客文をここへ出します'}</p></div></div></div>)}</div>}</section>
 <aside className='space-y-5'><section className='rounded-3xl border border-black/10 bg-white p-5'><div className='flex items-center gap-2'><Brain size={17}/><h2 className='font-black'>学習の仕組み</h2></div><div className='mt-4 space-y-3 text-sm leading-6 text-black/55'><p><b className='text-black'>1.</b> 放置日数・金額・期限・ステージで候補抽出</p><p><b className='text-black'>2.</b> AIが次アクションと追客文を作成</p><p><b className='text-black'>3.</b> 「復活 / 失注 / 追客済み」を保存</p><p><b className='text-black'>4.</b> 復活率と成功文面を次回スキャンへ反映</p></div><div className='mt-5 rounded-2xl bg-emerald-50 p-4'><span className='text-xs font-black text-emerald-800'>目的は管理ではない</span><p className='mt-1 text-xs leading-5 text-emerald-900/70'>毎朝ここを開いた時、今日どこへ連絡すれば売上に一番近いかが分かる状態を作る。</p></div></section><section className='rounded-3xl border border-black/10 bg-white p-5'><details><summary className='cursor-pointer text-sm font-black'>Gmail / Calendar連携</summary><p className='mt-3 text-xs leading-5 text-black/45'>Makeなどから営業イベントを送ると、会社名が一致した案件の最終接触日時を自動更新します。</p><div className='mt-3 flex gap-2'><button onClick={issueToken} className='flex-1 rounded-lg border border-black/10 px-3 py-2 text-xs font-bold'>{data.integrationConfigured?'キー再発行':'キー発行'}</button><button onClick={testEvent} className='rounded-lg border border-black/10 px-3 py-2 text-xs font-bold'>受信テスト</button></div>{token&&<div className='mt-3 space-y-2 rounded-xl bg-amber-50 p-3 text-[11px]'><Code label='Endpoint' value={location.origin+'/api/ingest'} copy={copy}/><Code label='X-User-Id' value={user.userId} copy={copy}/><Code label='X-Ingest-Token' value={token} copy={copy}/></div>}</details></section><section className='rounded-3xl bg-[#171816] p-5 text-white'><div className='flex items-center gap-2'><Mail size={16}/><h2 className='font-black'>直近イベント</h2></div>{data.events.length===0?<p className='mt-3 text-xs leading-5 text-white/45'>まだイベントはありません</p>:<div className='mt-3 space-y-2'>{data.events.slice(0,6).map(e=><div key={e.id} className='rounded-xl bg-white/7 p-3'><span className='text-[10px] font-bold uppercase text-white/35'>{e.source} · {dt(e.occurredAt)}</span><b className='mt-1 block text-xs'>{e.title}</b></div>)}</div>}</section></aside></div>
 <section className='mt-5 overflow-hidden rounded-3xl border border-black/10 bg-white'><div className='border-b border-black/8 p-5'><h2 className='font-black'>全案件</h2><p className='mt-1 text-xs text-black/40'>ここは管理画面ではなく、AI判断の材料を直す場所</p></div>{data.deals.length===0?<Empty/>:<div className='divide-y divide-black/8'>{data.deals.map(d=><div key={d.id} className='grid gap-3 p-4 sm:grid-cols-[1fr_140px_150px_48px] sm:items-center'><div><b className='text-sm'>{d.company}</b><span className='ml-2 text-xs text-black/35'>{yen(d.amount)}</span></div><select disabled={busy} value={d.stage} onChange={e=>updateStage(d,e.target.value)} className='rounded-lg border border-black/10 px-2 py-2 text-xs font-bold'>{stages.map(s=><option key={s}>{s}</option>)}</select><span className='text-xs text-black/40'>最終接触 {dt(d.lastContactAt)}</span><button onClick={()=>remove(d)} className='p-2 text-black/25 hover:text-red-600'><Trash2 size={16}/></button></div>)}</div>}</section></main></div>;
}
function Metric({label,value,sub,icon}:{label:string;value:string;sub:string;icon:React.ReactNode}){return <div className='rounded-2xl border border-black/10 bg-white p-5'><div className='flex items-center justify-between text-xs text-black/40'><span>{label}</span>{icon}</div><b className='mt-2 block text-2xl'>{value}</b><span className='mt-1 block text-xs text-black/35'>{sub}</span></div>}
function Input({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className='text-xs font-bold'>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className='mt-2 w-full rounded-xl border border-black/10 bg-white px-3 py-3 text-sm'/></label>}
function Empty(){return <div className='p-10 text-center'><Flame className='mx-auto text-black/15'/><b className='mt-3 block text-sm'>回収候補はまだありません</b><p className='mt-1 text-xs text-black/40'>過去案件を入れるほど、この画面の価値が上がります</p></div>}
function Code({label,value,copy}:{label:string;value:string;copy:(v:string)=>void}){return <div><b className='block text-amber-900'>{label}</b><div className='mt-1 flex items-center gap-2'><code className='min-w-0 flex-1 break-all text-amber-900/65'>{value}</code><button onClick={()=>copy(value)}><Copy size={12}/></button></div></div>}